<?xml version = "1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE GEO_LINKS [
<!ELEMENT GEO_LINKS (ITEM)*>
<!ELEMENT ITEM (ID, LFDNR, URL?, NORM_ID?, QUELLE?, QUELLE_ZUSATZ?)>
<!ATTLIST ITEM num CDATA #REQUIRED>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT LFDNR (#PCDATA)>
<!ELEMENT URL (#PCDATA)>
<!ELEMENT NORM_ID (#PCDATA)>
<!ELEMENT QUELLE (#PCDATA)>
<!ELEMENT QUELLE_ZUSATZ (#PCDATA)>
]>
<GEO_LINKS>
   <ITEM num="1">
      <ID>77200</ID>
      <LFDNR>15732</LFDNR>
      <URL>https://www.geonames.org/2661881/aarau.html</URL>
      <NORM_ID>2661881</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="2">
      <ID>77200</ID>
      <LFDNR>9428</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Aarau</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="3">
      <ID>77200</ID>
      <LFDNR>9429</LFDNR>
      <URL>https://d-nb.info/gnd/4000018-7</URL>
      <NORM_ID>4000018-7</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="4">
      <ID>77200</ID>
      <LFDNR>9430</LFDNR>
      <URL>https://hls-dhs-dss.ch/de/articles/001620/2016-11-25/</URL>
      <QUELLE>Historisches Lexikon der Schweiz</QUELLE>
   </ITEM>
   <ITEM num="5">
      <ID>77201</ID>
      <LFDNR>14157</LFDNR>
      <URL>http://gov.genealogy.net/ABAHINJN69IX</URL>
      <QUELLE>GOV</QUELLE>
   </ITEM>
   <ITEM num="6">
      <ID>77201</ID>
      <LFDNR>14158</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Z%C3%A1dub-Z%C3%A1vi%C5%A1%C3%ADn</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="7">
      <ID>77201</ID>
      <LFDNR>14159</LFDNR>
      <URL>https://d-nb.info/gnd/7861798-4</URL>
      <NORM_ID>7861798-4</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="8">
      <ID>77201</ID>
      <LFDNR>15733</LFDNR>
      <URL>https://www.geonames.org/3061802/zadub-zavisin.html</URL>
      <NORM_ID>3061802</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="9">
      <ID>77204</ID>
      <LFDNR>15734</LFDNR>
      <URL>https://www.geonames.org/633679/turku.html</URL>
      <NORM_ID>633679</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="10">
      <ID>77204</ID>
      <LFDNR>9089</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Turku</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="11">
      <ID>77204</ID>
      <LFDNR>9090</LFDNR>
      <URL>https://d-nb.info/gnd/4061256-9</URL>
      <NORM_ID>4061256-9</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="12">
      <ID>77214</ID>
      <LFDNR>17065</LFDNR>
      <URL>https://www.geonames.org/2959485/adenberg.html</URL>
      <NORM_ID>2959485</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="13">
      <ID>77215</ID>
      <LFDNR>8542</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Adr%C5%A1pach</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="14">
      <ID>77215</ID>
      <LFDNR>8543</LFDNR>
      <URL>http://d-nb.info/gnd/4564320-9</URL>
      <NORM_ID>4564320-9</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="15">
      <ID>77215</ID>
      <LFDNR>8544</LFDNR>
      <URL>https://www.geonames.org/3079834/adrspach.html</URL>
      <NORM_ID>3079834</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="16">
      <ID>77216</ID>
      <LFDNR>14480</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Etsch</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="17">
      <ID>77216</ID>
      <LFDNR>14481</LFDNR>
      <URL>https://d-nb.info/gnd/4015629-1</URL>
      <NORM_ID>4015629-1</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="18">
      <ID>77216</ID>
      <LFDNR>15735</LFDNR>
      <URL>https://www.geonames.org/3183470/fiume-adige.html</URL>
      <NORM_ID>3183470</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="19">
      <ID>77217</ID>
      <LFDNR>14478</LFDNR>
      <URL>https://d-nb.info/gnd/4000533-1</URL>
      <NORM_ID>4000533-1</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="20">
      <ID>77217</ID>
      <LFDNR>14479</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Adriatisches_Meer</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="21">
      <ID>77217</ID>
      <LFDNR>15736</LFDNR>
      <URL>https://www.geonames.org/3183462/adriatic-sea.html</URL>
      <NORM_ID>3183462</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="22">
      <ID>77218</ID>
      <LFDNR>12164</LFDNR>
      <URL>https://www.geonames.org/6255146/africa.html</URL>
      <NORM_ID>6255146</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="23">
      <ID>77218</ID>
      <LFDNR>9111</LFDNR>
      <URL>https://d-nb.info/gnd/4000695-5</URL>
      <NORM_ID>4000695-5</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="24">
      <ID>77219</ID>
      <LFDNR>9112</LFDNR>
      <URL>https://d-nb.info/gnd/4068425-8</URL>
      <NORM_ID>4068425-8</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="25">
      <ID>77219</ID>
      <LFDNR>15316</LFDNR>
      <URL>https://de.wikipedia.org/wiki/%C3%84g%C3%A4isches_Meer</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="26">
      <ID>77219</ID>
      <LFDNR>15737</LFDNR>
      <URL>https://www.geonames.org/265695/aegean-sea.html</URL>
      <NORM_ID>265695</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="27">
      <ID>77220</ID>
      <LFDNR>7723</LFDNR>
      <URL>https://www.geonames.org/2525764/</URL>
      <NORM_ID>2525764</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="28">
      <ID>77220</ID>
      <LFDNR>7727</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Agrigent</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="29">
      <ID>77220</ID>
      <LFDNR>8545</LFDNR>
      <URL>http://d-nb.info/gnd/4068475-1</URL>
      <NORM_ID>4068475-1</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="30">
      <ID>77221</ID>
      <LFDNR>13679</LFDNR>
      <URL>https://de.wikipedia.org/wiki/%C3%84gypten</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="31">
      <ID>77221</ID>
      <LFDNR>13680</LFDNR>
      <URL>https://d-nb.info/gnd/4000556-2</URL>
      <NORM_ID>4000556-2</NORM_ID>
      <QUELLE>GND</QUELLE>
      <QUELLE_ZUSATZ>Ägypten</QUELLE_ZUSATZ>
   </ITEM>
   <ITEM num="32">
      <ID>77221</ID>
      <LFDNR>13681</LFDNR>
      <URL>https://d-nb.info/gnd/4068430-1</URL>
      <NORM_ID>4068430-1</NORM_ID>
      <QUELLE>GND</QUELLE>
      <QUELLE_ZUSATZ>Ägypten (Altertum)</QUELLE_ZUSATZ>
   </ITEM>
   <ITEM num="33">
      <ID>77221</ID>
      <LFDNR>13682</LFDNR>
      <URL>https://www.geonames.org/357994/arab-republic-of-egypt.html</URL>
      <NORM_ID>357994</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="34">
      <ID>77222</ID>
      <LFDNR>9113</LFDNR>
      <URL>https://d-nb.info/gnd/4000816-2</URL>
      <NORM_ID>4000816-2</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="35">
      <ID>77222</ID>
      <LFDNR>15738</LFDNR>
      <URL>https://www.geonames.org/2959121/ahr.html</URL>
      <NORM_ID>2959121</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="36">
      <ID>77226</ID>
      <LFDNR>18591</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Doub%C3%AD_(Karlovy_Vary)</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="37">
      <ID>77226</ID>
      <LFDNR>18592</LFDNR>
      <URL>http://d-nb.info/gnd/4084816-4</URL>
      <NORM_ID>4084816-4</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="38">
      <ID>77226</ID>
      <LFDNR>18593</LFDNR>
      <URL>http://www.geonames.org/3076565/doubi.html</URL>
      <NORM_ID>3076565</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="39">
      <ID>77227</ID>
      <LFDNR>15341</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Airolo</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="40">
      <ID>77227</ID>
      <LFDNR>15342</LFDNR>
      <URL>https://d-nb.info/gnd/4453169-2</URL>
      <NORM_ID>4453169-2</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="41">
      <ID>77227</ID>
      <LFDNR>15343</LFDNR>
      <URL>https://www.geonames.org/2661830/airolo.html</URL>
      <NORM_ID>2661830</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="42">
      <ID>77227</ID>
      <LFDNR>15344</LFDNR>
      <URL>https://hls-dhs-dss.ch/de/articles/002065/2022-03-18/</URL>
      <QUELLE>Historisches Lexikon der Schweiz</QUELLE>
   </ITEM>
   <ITEM num="43">
      <ID>77228</ID>
      <LFDNR>14160</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Albaner_Berge</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="44">
      <ID>77228</ID>
      <LFDNR>14161</LFDNR>
      <URL>https://d-nb.info/gnd/4068518-4</URL>
      <NORM_ID>4068518-4</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="45">
      <ID>77228</ID>
      <LFDNR>10461</LFDNR>
      <URL>https://www.geonames.org/3183359/colli-albani.html</URL>
      <NORM_ID>3183359</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="46">
      <ID>77229</ID>
      <LFDNR>8546</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Albano_Laziale</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="47">
      <ID>77229</ID>
      <LFDNR>8547</LFDNR>
      <URL>http://d-nb.info/gnd/4079681-4</URL>
      <NORM_ID>4079681-4</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="48">
      <ID>77229</ID>
      <LFDNR>8548</LFDNR>
      <URL>https://www.geonames.org/3183356/albano-laziale.html</URL>
      <NORM_ID>3183356</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="49">
      <ID>77231</ID>
      <LFDNR>14162</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Alcamo</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="50">
      <ID>77231</ID>
      <LFDNR>14163</LFDNR>
      <URL>https://d-nb.info/gnd/4209552-9</URL>
      <NORM_ID>4209552-9</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="51">
      <ID>77231</ID>
      <LFDNR>14164</LFDNR>
      <URL>https://www.geonames.org/2525755/alcamo.html</URL>
      <NORM_ID>2525755</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="52">
      <ID>77232</ID>
      <LFDNR>17141</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Aldingen</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="53">
      <ID>77232</ID>
      <LFDNR>17142</LFDNR>
      <URL>https://d-nb.info/gnd/4441399-3</URL>
      <NORM_ID>4441399-3</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="54">
      <ID>77232</ID>
      <LFDNR>17143</LFDNR>
      <URL>https://www.geonames.org/2958575/aldingen.html</URL>
      <NORM_ID>2958575</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="55">
      <ID>77234</ID>
      <LFDNR>15739</LFDNR>
      <URL>https://www.geonames.org/2958545/bad-alexandersbad.html</URL>
      <NORM_ID>2958545</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="56">
      <ID>77234</ID>
      <LFDNR>9091</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Bad_Alexandersbad</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="57">
      <ID>77234</ID>
      <LFDNR>9092</LFDNR>
      <URL>https://d-nb.info/gnd/4079699-1</URL>
      <NORM_ID>4079699-1</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="58">
      <ID>77235</ID>
      <LFDNR>9114</LFDNR>
      <URL>https://d-nb.info/gnd/4001138-0</URL>
      <NORM_ID>4001138-0</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="59">
      <ID>77235</ID>
      <LFDNR>9944</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Alexandria</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="60">
      <ID>77235</ID>
      <LFDNR>9945</LFDNR>
      <URL>https://www.geonames.org/361058/alexandria.html</URL>
      <NORM_ID>361058</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="61">
      <ID>77237</ID>
      <LFDNR>9252</LFDNR>
      <URL>https://d-nb.info/gnd/4079709-0</URL>
      <NORM_ID>4079709-0</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="62">
      <ID>77237</ID>
      <LFDNR>7724</LFDNR>
      <URL>https://www.geonames.org/2958266/</URL>
      <NORM_ID>2958266</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="63">
      <ID>77237</ID>
      <LFDNR>7728</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Allstedt</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="64">
      <ID>77238</ID>
      <LFDNR>15345</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Alp_(Fluss)</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="65">
      <ID>77238</ID>
      <LFDNR>15346</LFDNR>
      <URL>https://www.geonames.org/2661809/alp.html</URL>
      <NORM_ID>2661809</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="66">
      <ID>77238</ID>
      <LFDNR>15347</LFDNR>
      <URL>https://d-nb.info/gnd/4581037-0</URL>
      <NORM_ID>4581037-0</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="67">
      <ID>77239</ID>
      <LFDNR>18198</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Alpen</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="68">
      <ID>77239</ID>
      <LFDNR>18199</LFDNR>
      <URL>https://d-nb.info/gnd/4001328-5</URL>
      <NORM_ID>4001328-5</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="69">
      <ID>77239</ID>
      <LFDNR>18200</LFDNR>
      <URL>https://www.geonames.org/2661786/alps.html</URL>
      <NORM_ID>2661786</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="70">
      <ID>77243</ID>
      <LFDNR>8041</LFDNR>
      <URL>https://hls-dhs-dss.ch/de/articles/000690/2021-01-15/</URL>
      <QUELLE>Historisches Lexikon der Schweiz</QUELLE>
   </ITEM>
   <ITEM num="71">
      <ID>77243</ID>
      <LFDNR>8042</LFDNR>
      <URL>http://d-nb.info/gnd/4001389-3</URL>
      <NORM_ID>4001389-3</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="72">
      <ID>77243</ID>
      <LFDNR>8043</LFDNR>
      <URL>http://www.geonames.org/2661780/altdorf.html</URL>
      <NORM_ID>2661780</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="73">
      <ID>77244</ID>
      <LFDNR>9115</LFDNR>
      <URL>https://d-nb.info/gnd/4001388-1</URL>
      <NORM_ID>4001388-1</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="74">
      <ID>77244</ID>
      <LFDNR>9116</LFDNR>
      <URL>http://www.geonames.org/2958024/altdorf-bei-nuernberg.html</URL>
      <NORM_ID>2958024</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="75">
      <ID>77247</ID>
      <LFDNR>14167</LFDNR>
      <URL>https://www.geonames.org/2957880/altenau.html</URL>
      <NORM_ID>2957880</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="76">
      <ID>77247</ID>
      <LFDNR>14165</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Altenau</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="77">
      <ID>77247</ID>
      <LFDNR>14166</LFDNR>
      <URL>https://d-nb.info/gnd/4085026-2</URL>
      <NORM_ID>4085026-2</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="78">
      <ID>77248</ID>
      <LFDNR>11602</LFDNR>
      <URL>https://d-nb.info/gnd/4238828-4</URL>
      <NORM_ID>4238828-4</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="79">
      <ID>77248</ID>
      <LFDNR>11601</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Altenberg_(Erzgebirge)</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="80">
      <ID>77248</ID>
      <LFDNR>11605</LFDNR>
      <URL>https://hov.isgv.de/Altenberg_(1)</URL>
      <QUELLE>Historisches Ortsverzeichnis Sachsen</QUELLE>
   </ITEM>
   <ITEM num="81">
      <ID>77248</ID>
      <LFDNR>11603</LFDNR>
      <URL>https://www.geonames.org/2957834/altenberg.html</URL>
      <NORM_ID>2957834</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="82">
      <ID>77248</ID>
      <LFDNR>11604</LFDNR>
      <URL>https://gov.genealogy.net/item/show/ALTERGJO60VS</URL>
      <QUELLE>GOV</QUELLE>
   </ITEM>
   <ITEM num="83">
      <ID>77250</ID>
      <LFDNR>13869</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Altenkirchen_(Braunfels)</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="84">
      <ID>77250</ID>
      <LFDNR>13870</LFDNR>
      <URL>https://d-nb.info/gnd/4704532-2</URL>
      <NORM_ID>4704532-2</NORM_ID>
      <QUELLE>GND</QUELLE>
      <QUELLE_ZUSATZ>Braunfels-Altenkirchen</QUELLE_ZUSATZ>
   </ITEM>
   <ITEM num="85">
      <ID>77250</ID>
      <LFDNR>15740</LFDNR>
      <URL>https://www.geonames.org/2957569/altenkirchen.html</URL>
      <NORM_ID>2957569</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="86">
      <ID>77256</ID>
      <LFDNR>9117</LFDNR>
      <URL>https://d-nb.info/gnd/4085080-8</URL>
      <NORM_ID>4085080-8</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="87">
      <ID>77256</ID>
      <LFDNR>9118</LFDNR>
      <URL>http://www.geonames.org/2911296/altona.html</URL>
      <NORM_ID>2911296</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="88">
      <ID>77258</ID>
      <LFDNR>15274</LFDNR>
      <URL>http://d-nb.info/gnd/4609709-0</URL>
      <NORM_ID>4609709-0</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="89">
      <ID>77258</ID>
      <LFDNR>15741</LFDNR>
      <URL>https://www.geonames.org/3065307/stare-sedlo.html</URL>
      <NORM_ID>3065307</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="90">
      <ID>77259</ID>
      <LFDNR>7726</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Star%C3%A1_Voda_u_Mari%C3%A1nsk%C3%BDch_L%C3%A1zn%C3%AD</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="91">
      <ID>77259</ID>
      <LFDNR>7725</LFDNR>
      <URL>https://www.geonames.org/3065377/stara-voda.html</URL>
      <NORM_ID>3065377</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="92">
      <ID>77260</ID>
      <LFDNR>12769</LFDNR>
      <URL>https://www.geonames.org/2956710/alzey.html</URL>
      <NORM_ID>2956710</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="93">
      <ID>77260</ID>
      <LFDNR>12768</LFDNR>
      <URL>https://d-nb.info/gnd/4001606-7</URL>
      <NORM_ID>4001606-7</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="94">
      <ID>77260</ID>
      <LFDNR>12767</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Alzey</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="95">
      <ID>77262</ID>
      <LFDNR>19040</LFDNR>
      <URL>https://www.geonames.org/10861432/america.html</URL>
      <NORM_ID>10861432</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="96">
      <ID>77262</ID>
      <LFDNR>18845</LFDNR>
      <URL>https://d-nb.info/gnd/4001670-5</URL>
      <NORM_ID>4001670-5</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="97">
      <ID>77262</ID>
      <LFDNR>18844</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Amerika</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="98">
      <ID>77264</ID>
      <LFDNR>8045</LFDNR>
      <URL>http://d-nb.info/gnd/4567656-2</URL>
      <NORM_ID>4567656-2</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="99">
      <ID>77264</ID>
      <LFDNR>8044</LFDNR>
      <URL>https://hls-dhs-dss.ch/de/articles/007470/2001-07-09/</URL>
      <QUELLE>Historisches Lexikon der Schweiz</QUELLE>
   </ITEM>
   <ITEM num="100">
      <ID>77264</ID>
      <LFDNR>14170</LFDNR>
      <URL>https://www.geonames.org/2661753/amsteg.html</URL>
      <NORM_ID>2661753</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="101">
      <ID>77265</ID>
      <LFDNR>15318</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Amsterdam</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="102">
      <ID>77265</ID>
      <LFDNR>15317</LFDNR>
      <URL>https://www.geonames.org/2759794/amsterdam.html</URL>
      <NORM_ID>2759794</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="103">
      <ID>77265</ID>
      <LFDNR>9119</LFDNR>
      <URL>https://d-nb.info/gnd/4001783-7</URL>
      <NORM_ID>4001783-7</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="104">
      <ID>77269</ID>
      <LFDNR>14171</LFDNR>
      <URL>https://www.geonames.org/2661750/andermatt.html</URL>
      <NORM_ID>2661750</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="105">
      <ID>77269</ID>
      <LFDNR>8046</LFDNR>
      <URL>https://hls-dhs-dss.ch/de/articles/000691/2009-07-21/</URL>
      <QUELLE>Historisches Lexikon der Schweiz</QUELLE>
   </ITEM>
   <ITEM num="106">
      <ID>77269</ID>
      <LFDNR>8047</LFDNR>
      <URL>http://d-nb.info/gnd/4270624-5</URL>
      <NORM_ID>4270624-5</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="107">
      <ID>77270</ID>
      <LFDNR>12604</LFDNR>
      <URL>https://d-nb.info/gnd/4001919-6</URL>
      <NORM_ID>4001919-6</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="108">
      <ID>77270</ID>
      <LFDNR>12603</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Andernach</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="109">
      <ID>77270</ID>
      <LFDNR>12605</LFDNR>
      <URL>http://www.geonames.org/2956206/andernach.html</URL>
      <NORM_ID>2956206</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="110">
      <ID>77272</ID>
      <LFDNR>9564</LFDNR>
      <URL>https://d-nb.info/gnd/4002113-0</URL>
      <NORM_ID>4002113-0</NORM_ID>
      <QUELLE>GND</QUELLE>
      <QUELLE_ZUSATZ>Annaberg (Erzgebirge)</QUELLE_ZUSATZ>
   </ITEM>
   <ITEM num="111">
      <ID>77272</ID>
      <LFDNR>9562</LFDNR>
      <URL>https://d-nb.info/gnd/4085813-3</URL>
      <NORM_ID>4085813-3</NORM_ID>
      <QUELLE>GND</QUELLE>
      <QUELLE_ZUSATZ>Annaberg-Buchholz</QUELLE_ZUSATZ>
   </ITEM>
   <ITEM num="112">
      <ID>77272</ID>
      <LFDNR>9561</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Annaberg-Buchholz</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="113">
      <ID>77272</ID>
      <LFDNR>9563</LFDNR>
      <URL>http://www.geonames.org/2956005/annaberg-buchholz.html</URL>
      <NORM_ID>2956005</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="114">
      <ID>77273</ID>
      <LFDNR>9170</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Ansbach</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="115">
      <ID>77273</ID>
      <LFDNR>9172</LFDNR>
      <URL>https://www.geonames.org/2955936/ansbach.html</URL>
      <NORM_ID>2955936</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="116">
      <ID>77273</ID>
      <LFDNR>9171</LFDNR>
      <URL>https://d-nb.info/gnd/4002170-1</URL>
      <NORM_ID>4002170-1</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="117">
      <ID>77277</ID>
      <LFDNR>9216</LFDNR>
      <URL>https://www.geonames.org/2803138/antwerpen.html</URL>
      <NORM_ID>2803138</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="118">
      <ID>77277</ID>
      <LFDNR>9215</LFDNR>
      <URL>https://d-nb.info/gnd/4002364-3</URL>
      <NORM_ID>4002364-3</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="119">
      <ID>77277</ID>
      <LFDNR>9214</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Antwerpen</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="120">
      <ID>77280</ID>
      <LFDNR>7729</LFDNR>
      <URL>https://www.geonames.org/2955770/</URL>
      <NORM_ID>2955770</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="121">
      <ID>77280</ID>
      <LFDNR>7730</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Apolda</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="122">
      <ID>77280</ID>
      <LFDNR>9274</LFDNR>
      <URL>https://d-nb.info/gnd/4002435-0</URL>
      <NORM_ID>4002435-0</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="123">
      <ID>77281</ID>
      <LFDNR>14312</LFDNR>
      <URL>http://www.geonames.org/2661740/appenzell.html</URL>
      <NORM_ID>2661740</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="124">
      <ID>77281</ID>
      <LFDNR>14310</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Appenzell_(Ort)</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="125">
      <ID>77281</ID>
      <LFDNR>14311</LFDNR>
      <URL>https://d-nb.info/gnd/4002485-4</URL>
      <NORM_ID>4002485-4</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="126">
      <ID>77291</ID>
      <LFDNR>14313</LFDNR>
      <URL>https://d-nb.info/gnd/1101391448</URL>
      <NORM_ID>1101391448</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="127">
      <ID>77291</ID>
      <LFDNR>14315</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Glacier_d%E2%80%99Argenti%C3%A8re</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="128">
      <ID>77291</ID>
      <LFDNR>14314</LFDNR>
      <URL>http://www.geonames.org/3037038/glacier-d-argentiere.html</URL>
      <NORM_ID>3037038</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="129">
      <ID>77298</ID>
      <LFDNR>9289</LFDNR>
      <URL>https://www.geonames.org/6551002/arnstadt.html</URL>
      <NORM_ID>6551002</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="130">
      <ID>77298</ID>
      <LFDNR>9288</LFDNR>
      <URL>https://d-nb.info/gnd/4003011-8</URL>
      <NORM_ID>4003011-8</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="131">
      <ID>77298</ID>
      <LFDNR>9287</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Arnstadt</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="132">
      <ID>77300</ID>
      <LFDNR>10008</LFDNR>
      <URL>https://www.geonames.org/2955394/artern.html</URL>
      <NORM_ID>2955394</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="133">
      <ID>77300</ID>
      <LFDNR>10007</LFDNR>
      <URL>http://gov.genealogy.net/ARTERNJO51PI</URL>
      <NORM_ID>ARTERNJO51PI</NORM_ID>
      <QUELLE>GOV</QUELLE>
   </ITEM>
   <ITEM num="134">
      <ID>77300</ID>
      <LFDNR>10006</LFDNR>
      <URL>https://d-nb.info/gnd/4300124-5</URL>
      <NORM_ID>4300124-5</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="135">
      <ID>77300</ID>
      <LFDNR>10005</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Artern</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="136">
      <ID>77301</ID>
      <LFDNR>14317</LFDNR>
      <URL>https://d-nb.info/gnd/4235933-8</URL>
      <NORM_ID>4235933-8</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="137">
      <ID>77301</ID>
      <LFDNR>14316</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Arve_(Fluss)</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="138">
      <ID>77301</ID>
      <LFDNR>14318</LFDNR>
      <URL>https://www.geonames.org/2661706/arve.html</URL>
      <NORM_ID>2661706</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="139">
      <ID>77303</ID>
      <LFDNR>10048</LFDNR>
      <URL>https://de.wikipedia.org/wiki/A%C5%A1</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="140">
      <ID>77303</ID>
      <LFDNR>10049</LFDNR>
      <URL>https://d-nb.info/gnd/5031471-3</URL>
      <NORM_ID>5031471-3</NORM_ID>
      <QUELLE>GND</QUELLE>
      <QUELLE_ZUSATZ>Aš</QUELLE_ZUSATZ>
   </ITEM>
   <ITEM num="141">
      <ID>77303</ID>
      <LFDNR>10050</LFDNR>
      <URL>https://d-nb.info/gnd/122909-6</URL>
      <NORM_ID>122909-6</NORM_ID>
      <QUELLE>GND</QUELLE>
      <QUELLE_ZUSATZ>Asch</QUELLE_ZUSATZ>
   </ITEM>
   <ITEM num="142">
      <ID>77303</ID>
      <LFDNR>10051</LFDNR>
      <URL>https://www.geonames.org/3079751/as.html</URL>
      <NORM_ID>3079751</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="143">
      <ID>77304</ID>
      <LFDNR>9263</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Aschaffenburg</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="144">
      <ID>77304</ID>
      <LFDNR>9264</LFDNR>
      <URL>https://d-nb.info/gnd/4003191-3</URL>
      <NORM_ID>4003191-3</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="145">
      <ID>77304</ID>
      <LFDNR>9265</LFDNR>
      <URL>http://www.geonames.org/2955272/aschaffenburg.html</URL>
      <NORM_ID>2955272</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="146">
      <ID>77307</ID>
      <LFDNR>9432</LFDNR>
      <URL>https://d-nb.info/gnd/4003366-1</URL>
      <NORM_ID>4003366-1</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="147">
      <ID>77307</ID>
      <LFDNR>9433</LFDNR>
      <URL>https://www.geonames.org/264371/athens.html</URL>
      <NORM_ID>264371</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="148">
      <ID>77307</ID>
      <LFDNR>9431</LFDNR>
      <URL>https://de.wikipedia.org/wiki/Athen</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="149">
      <ID>77311</ID>
      <LFDNR>11545</LFDNR>
      <URL>https://d-nb.info/gnd/4084764-0</URL>
      <NORM_ID>4084764-0</NORM_ID>
      <QUELLE>GND</QUELLE>
   </ITEM>
   <ITEM num="150">
      <ID>77311</ID>
      <LFDNR>11546</LFDNR>
      <URL>https://www.geonames.org/2524810/monte-etna.html</URL>
      <NORM_ID>2524810</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="151">
      <ID>77311</ID>
      <LFDNR>11544</LFDNR>
      <URL>https://de.wikipedia.org/wiki/%C3%84tna</URL>
      <QUELLE>Wikipedia</QUELLE>
   </ITEM>
   <ITEM num="152">
      <ID>77314</ID>
      <LFDNR>8560</LFDNR>
      <URL>http://gov.genealogy.net/AUGURGJN58KI</URL>
      <QUELLE>GOV</QUELLE>
   </ITEM>
   <ITEM num="153">
      <ID>77314</ID>
      <LFDNR>8561</LFDNR>
      <URL>https://www.geonames.org/2954172/augsburg.html</URL>
      <NORM_ID>2954172</NORM_ID>
      <QUELLE>GeoNames</QUELLE>
   </ITEM>
   <ITEM num="154">
      <ID>77314</ID>
      <LFDNR>8559</LFDNR>
      <URL>http://d-nb.info/gnd/4003614-5</URL>