<?xml version = "1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE GEO_MAIN [
<!ELEMENT GEO_MAIN (ITEM)*>
<!ELEMENT ITEM (ID, LFDNR, BEZEICHNUNG?, INDEXNAME?, VON_DATUM_TAG?, VON_DATUM_MONAT?, VON_DATUM_JAHR?, BIS_DATUM_TAG?, BIS_DATUM_MONAT?, BIS_DATUM_JAHR?)>
<!ATTLIST ITEM num CDATA #REQUIRED>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT LFDNR (#PCDATA)>
<!ELEMENT BEZEICHNUNG (#PCDATA)>
<!ELEMENT INDEXNAME (#PCDATA)>
<!ELEMENT VON_DATUM_TAG (#PCDATA)>
<!ELEMENT VON_DATUM_MONAT (#PCDATA)>
<!ELEMENT VON_DATUM_JAHR (#PCDATA)>
<!ELEMENT BIS_DATUM_TAG (#PCDATA)>
<!ELEMENT BIS_DATUM_MONAT (#PCDATA)>
<!ELEMENT BIS_DATUM_JAHR (#PCDATA)>
]>
<GEO_MAIN>
   <ITEM num="1">
      <ID>77200</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Aarau</BEZEICHNUNG>
      <INDEXNAME>aarau</INDEXNAME>
   </ITEM>
   <ITEM num="2">
      <ID>77201</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Abaschin</BEZEICHNUNG>
      <INDEXNAME>abaschin</INDEXNAME>
   </ITEM>
   <ITEM num="3">
      <ID>77201</ID>
      <LFDNR>2481</LFDNR>
      <BEZEICHNUNG>Závišín</BEZEICHNUNG>
      <INDEXNAME>zavisin</INDEXNAME>
   </ITEM>
   <ITEM num="4">
      <ID>77201</ID>
      <LFDNR>41</LFDNR>
      <BEZEICHNUNG>Aboschin</BEZEICHNUNG>
      <INDEXNAME>aboschin</INDEXNAME>
   </ITEM>
   <ITEM num="5">
      <ID>77204</ID>
      <LFDNR>670</LFDNR>
      <BEZEICHNUNG>Turku</BEZEICHNUNG>
      <INDEXNAME>turku</INDEXNAME>
   </ITEM>
   <ITEM num="6">
      <ID>77204</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Åbo</BEZEICHNUNG>
      <INDEXNAME>abo</INDEXNAME>
   </ITEM>
   <ITEM num="7">
      <ID>77214</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Adenberg</BEZEICHNUNG>
      <INDEXNAME>adenberg</INDEXNAME>
   </ITEM>
   <ITEM num="8">
      <ID>77215</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Adersbach</BEZEICHNUNG>
      <INDEXNAME>adersbach</INDEXNAME>
   </ITEM>
   <ITEM num="9">
      <ID>77216</ID>
      <LFDNR>459</LFDNR>
      <BEZEICHNUNG>Etsch</BEZEICHNUNG>
      <INDEXNAME>etsch</INDEXNAME>
   </ITEM>
   <ITEM num="10">
      <ID>77216</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Adige</BEZEICHNUNG>
      <INDEXNAME>adige</INDEXNAME>
   </ITEM>
   <ITEM num="11">
      <ID>77217</ID>
      <LFDNR>2170</LFDNR>
      <BEZEICHNUNG>Adria</BEZEICHNUNG>
      <INDEXNAME>adria</INDEXNAME>
   </ITEM>
   <ITEM num="12">
      <ID>77217</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Adriatisches Meer</BEZEICHNUNG>
      <INDEXNAME>adriatisches meer</INDEXNAME>
   </ITEM>
   <ITEM num="13">
      <ID>77218</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Afrika</BEZEICHNUNG>
      <INDEXNAME>afrika</INDEXNAME>
   </ITEM>
   <ITEM num="14">
      <ID>77219</ID>
      <LFDNR>682</LFDNR>
      <BEZEICHNUNG>Ägäis</BEZEICHNUNG>
      <INDEXNAME>aegaeis</INDEXNAME>
   </ITEM>
   <ITEM num="15">
      <ID>77219</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Ägäisches Meer (Aegeum mare)</BEZEICHNUNG>
      <INDEXNAME>aegaeisches meer aegeum mare</INDEXNAME>
   </ITEM>
   <ITEM num="16">
      <ID>77220</ID>
      <LFDNR>302</LFDNR>
      <BEZEICHNUNG>Girgenti</BEZEICHNUNG>
      <INDEXNAME>girgenti</INDEXNAME>
   </ITEM>
   <ITEM num="17">
      <ID>77220</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Agrigent</BEZEICHNUNG>
      <INDEXNAME>agrigent</INDEXNAME>
   </ITEM>
   <ITEM num="18">
      <ID>77220</ID>
      <LFDNR>2105</LFDNR>
      <BEZEICHNUNG>Akragas</BEZEICHNUNG>
      <INDEXNAME>akragas</INDEXNAME>
   </ITEM>
   <ITEM num="19">
      <ID>77221</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Ägypten</BEZEICHNUNG>
      <INDEXNAME>aegypten</INDEXNAME>
   </ITEM>
   <ITEM num="20">
      <ID>77222</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Ahr</BEZEICHNUNG>
      <INDEXNAME>ahr</INDEXNAME>
   </ITEM>
   <ITEM num="21">
      <ID>77226</ID>
      <LFDNR>3604</LFDNR>
      <BEZEICHNUNG>Doubí</BEZEICHNUNG>
      <INDEXNAME>doubi</INDEXNAME>
   </ITEM>
   <ITEM num="22">
      <ID>77226</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Aich</BEZEICHNUNG>
      <INDEXNAME>aich</INDEXNAME>
   </ITEM>
   <ITEM num="23">
      <ID>77227</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Airolo</BEZEICHNUNG>
      <INDEXNAME>airolo</INDEXNAME>
   </ITEM>
   <ITEM num="24">
      <ID>77228</ID>
      <LFDNR>2106</LFDNR>
      <BEZEICHNUNG>Colli Albani</BEZEICHNUNG>
      <INDEXNAME>colli albani</INDEXNAME>
   </ITEM>
   <ITEM num="25">
      <ID>77228</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Albaner Berge</BEZEICHNUNG>
      <INDEXNAME>albaner berge</INDEXNAME>
   </ITEM>
   <ITEM num="26">
      <ID>77229</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Albano</BEZEICHNUNG>
      <INDEXNAME>albano</INDEXNAME>
   </ITEM>
   <ITEM num="27">
      <ID>77231</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Alcamo</BEZEICHNUNG>
      <INDEXNAME>alcamo</INDEXNAME>
   </ITEM>
   <ITEM num="28">
      <ID>77232</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Aldingen</BEZEICHNUNG>
      <INDEXNAME>aldingen</INDEXNAME>
   </ITEM>
   <ITEM num="29">
      <ID>77234</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Alexandersbad</BEZEICHNUNG>
      <INDEXNAME>alexandersbad</INDEXNAME>
      <BIS_DATUM_JAHR>1979</BIS_DATUM_JAHR>
   </ITEM>
   <ITEM num="30">
      <ID>77234</ID>
      <LFDNR>2482</LFDNR>
      <BEZEICHNUNG>Bad Alexandersbad</BEZEICHNUNG>
      <INDEXNAME>bad alexandersbad</INDEXNAME>
      <VON_DATUM_JAHR>1979</VON_DATUM_JAHR>
   </ITEM>
   <ITEM num="31">
      <ID>77235</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Alexandria</BEZEICHNUNG>
      <INDEXNAME>alexandria</INDEXNAME>
   </ITEM>
   <ITEM num="32">
      <ID>77237</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Allstedt</BEZEICHNUNG>
      <INDEXNAME>allstedt</INDEXNAME>
   </ITEM>
   <ITEM num="33">
      <ID>77238</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Alp</BEZEICHNUNG>
      <INDEXNAME>alp</INDEXNAME>
   </ITEM>
   <ITEM num="34">
      <ID>77239</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Alpen</BEZEICHNUNG>
      <INDEXNAME>alpen</INDEXNAME>
   </ITEM>
   <ITEM num="35">
      <ID>77243</ID>
      <LFDNR>211</LFDNR>
      <BEZEICHNUNG>Altorf</BEZEICHNUNG>
      <INDEXNAME>altorf</INDEXNAME>
   </ITEM>
   <ITEM num="36">
      <ID>77243</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Altdorf</BEZEICHNUNG>
      <INDEXNAME>altdorf</INDEXNAME>
   </ITEM>
   <ITEM num="37">
      <ID>77244</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Altdorf b. Nürnberg</BEZEICHNUNG>
      <INDEXNAME>altdorf b nuernberg</INDEXNAME>
   </ITEM>
   <ITEM num="38">
      <ID>77247</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Altenau</BEZEICHNUNG>
      <INDEXNAME>altenau</INDEXNAME>
   </ITEM>
   <ITEM num="39">
      <ID>77248</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Altenberg</BEZEICHNUNG>
      <INDEXNAME>altenberg</INDEXNAME>
   </ITEM>
   <ITEM num="40">
      <ID>77250</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Altenkirchen</BEZEICHNUNG>
      <INDEXNAME>altenkirchen</INDEXNAME>
      <BIS_DATUM_TAG>1</BIS_DATUM_TAG>
      <BIS_DATUM_MONAT>7</BIS_DATUM_MONAT>
      <BIS_DATUM_JAHR>1974</BIS_DATUM_JAHR>
   </ITEM>
   <ITEM num="41">
      <ID>77256</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Altona</BEZEICHNUNG>
      <INDEXNAME>altona</INDEXNAME>
      <BIS_DATUM_TAG>31</BIS_DATUM_TAG>
      <BIS_DATUM_MONAT>3</BIS_DATUM_MONAT>
      <BIS_DATUM_JAHR>1938</BIS_DATUM_JAHR>
   </ITEM>
   <ITEM num="42">
      <ID>77256</ID>
      <LFDNR>713</LFDNR>
      <BEZEICHNUNG>Hamburg-Altona</BEZEICHNUNG>
      <INDEXNAME>hamburg-altona</INDEXNAME>
      <VON_DATUM_TAG>1</VON_DATUM_TAG>
      <VON_DATUM_MONAT>4</VON_DATUM_MONAT>
      <VON_DATUM_JAHR>1938</VON_DATUM_JAHR>
   </ITEM>
   <ITEM num="43">
      <ID>77258</ID>
      <LFDNR>2385</LFDNR>
      <BEZEICHNUNG>Alt Sattl</BEZEICHNUNG>
      <INDEXNAME>alt sattl</INDEXNAME>
   </ITEM>
   <ITEM num="44">
      <ID>77258</ID>
      <LFDNR>2386</LFDNR>
      <BEZEICHNUNG>Staré Sedlo</BEZEICHNUNG>
      <INDEXNAME>stare sedlo</INDEXNAME>
   </ITEM>
   <ITEM num="45">
      <ID>77258</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Altsattel (Altsatl)</BEZEICHNUNG>
      <INDEXNAME>altsattel (altsatl)</INDEXNAME>
   </ITEM>
   <ITEM num="46">
      <ID>77259</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Altwasser</BEZEICHNUNG>
      <INDEXNAME>altwasser</INDEXNAME>
   </ITEM>
   <ITEM num="47">
      <ID>77260</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Alzey</BEZEICHNUNG>
      <INDEXNAME>alzey</INDEXNAME>
   </ITEM>
   <ITEM num="48">
      <ID>77262</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Amerika</BEZEICHNUNG>
      <INDEXNAME>amerika</INDEXNAME>
   </ITEM>
   <ITEM num="49">
      <ID>77264</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Amsteg</BEZEICHNUNG>
      <INDEXNAME>amsteg</INDEXNAME>
   </ITEM>
   <ITEM num="50">
      <ID>77265</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Amsterdam</BEZEICHNUNG>
      <INDEXNAME>amsterdam</INDEXNAME>
   </ITEM>
   <ITEM num="51">
      <ID>77269</ID>
      <LFDNR>671</LFDNR>
      <BEZEICHNUNG>Ursern an der Matt</BEZEICHNUNG>
      <INDEXNAME>ursern an der matt</INDEXNAME>
   </ITEM>
   <ITEM num="52">
      <ID>77269</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Andermatt</BEZEICHNUNG>
      <INDEXNAME>andermatt</INDEXNAME>
   </ITEM>
   <ITEM num="53">
      <ID>77270</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Andernach</BEZEICHNUNG>
      <INDEXNAME>andernach</INDEXNAME>
   </ITEM>
   <ITEM num="54">
      <ID>77272</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Annaberg (Erzgebirge)</BEZEICHNUNG>
      <INDEXNAME>annaberg erzgebirge</INDEXNAME>
      <BIS_DATUM_TAG>9</BIS_DATUM_TAG>
      <BIS_DATUM_MONAT>12</BIS_DATUM_MONAT>
      <BIS_DATUM_JAHR>1948</BIS_DATUM_JAHR>
   </ITEM>
   <ITEM num="55">
      <ID>77272</ID>
      <LFDNR>2741</LFDNR>
      <BEZEICHNUNG>Buchholz (Erzgebirge)</BEZEICHNUNG>
      <INDEXNAME>buchholz erzgebirge</INDEXNAME>
      <VON_DATUM_JAHR>1501</VON_DATUM_JAHR>
      <BIS_DATUM_JAHR>1948</BIS_DATUM_JAHR>
   </ITEM>
   <ITEM num="56">
      <ID>77272</ID>
      <LFDNR>797</LFDNR>
      <BEZEICHNUNG>Annaberg-Buchholz</BEZEICHNUNG>
      <INDEXNAME>annaberg-buchholz</INDEXNAME>
      <VON_DATUM_TAG>10</VON_DATUM_TAG>
      <VON_DATUM_MONAT>12</VON_DATUM_MONAT>
      <VON_DATUM_JAHR>1948</VON_DATUM_JAHR>
   </ITEM>
   <ITEM num="57">
      <ID>77273</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Ansbach</BEZEICHNUNG>
      <INDEXNAME>ansbach</INDEXNAME>
   </ITEM>
   <ITEM num="58">
      <ID>77277</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Antwerpen</BEZEICHNUNG>
      <INDEXNAME>antwerpen</INDEXNAME>
   </ITEM>
   <ITEM num="59">
      <ID>77280</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Apolda</BEZEICHNUNG>
      <INDEXNAME>apolda</INDEXNAME>
   </ITEM>
   <ITEM num="60">
      <ID>77281</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Appenzell</BEZEICHNUNG>
      <INDEXNAME>appenzell</INDEXNAME>
   </ITEM>
   <ITEM num="61">
      <ID>77291</ID>
      <LFDNR>2123</LFDNR>
      <BEZEICHNUNG>Argentière, Glacier d'</BEZEICHNUNG>
      <INDEXNAME>argentiere, glacier d</INDEXNAME>
   </ITEM>
   <ITEM num="62">
      <ID>77291</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Glacier d’Argentière</BEZEICHNUNG>
      <INDEXNAME>glacier d’argentiere</INDEXNAME>
   </ITEM>
   <ITEM num="63">
      <ID>77298</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Arnstadt</BEZEICHNUNG>
      <INDEXNAME>arnstadt</INDEXNAME>
   </ITEM>
   <ITEM num="64">
      <ID>77300</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Artern</BEZEICHNUNG>
      <INDEXNAME>artern</INDEXNAME>
   </ITEM>
   <ITEM num="65">
      <ID>77301</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Arve</BEZEICHNUNG>
      <INDEXNAME>arve</INDEXNAME>
   </ITEM>
   <ITEM num="66">
      <ID>77303</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Asch</BEZEICHNUNG>
      <INDEXNAME>asch</INDEXNAME>
      <BIS_DATUM_JAHR>1945</BIS_DATUM_JAHR>
   </ITEM>
   <ITEM num="67">
      <ID>77303</ID>
      <LFDNR>948</LFDNR>
      <BEZEICHNUNG>Aš</BEZEICHNUNG>
      <INDEXNAME>as</INDEXNAME>
      <VON_DATUM_JAHR>1945</VON_DATUM_JAHR>
   </ITEM>
   <ITEM num="68">
      <ID>77304</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Aschaffenburg</BEZEICHNUNG>
      <INDEXNAME>aschaffenburg</INDEXNAME>
   </ITEM>
   <ITEM num="69">
      <ID>77307</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Athen</BEZEICHNUNG>
      <INDEXNAME>athen</INDEXNAME>
   </ITEM>
   <ITEM num="70">
      <ID>77311</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Ätna</BEZEICHNUNG>
      <INDEXNAME>aetna</INDEXNAME>
   </ITEM>
   <ITEM num="71">
      <ID>77311</ID>
      <LFDNR>458</LFDNR>
      <BEZEICHNUNG>Etna</BEZEICHNUNG>
      <INDEXNAME>etna</INDEXNAME>
   </ITEM>
   <ITEM num="72">
      <ID>77314</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Augsburg</BEZEICHNUNG>
      <INDEXNAME>augsburg</INDEXNAME>
   </ITEM>
   <ITEM num="73">
      <ID>77318</ID>
      <LFDNR>1902</LFDNR>
      <BEZEICHNUNG>Aussig</BEZEICHNUNG>
      <INDEXNAME>aussig</INDEXNAME>
   </ITEM>
   <ITEM num="74">
      <ID>77318</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Außig</BEZEICHNUNG>
      <INDEXNAME>aussig</INDEXNAME>
   </ITEM>
   <ITEM num="75">
      <ID>77318</ID>
      <LFDNR>2682</LFDNR>
      <BEZEICHNUNG>Ústí nad Labem</BEZEICHNUNG>
      <INDEXNAME>usti nad labem</INDEXNAME>
   </ITEM>
   <ITEM num="76">
      <ID>77330</ID>
      <LFDNR>1281</LFDNR>
      <BEZEICHNUNG>Nauheim</BEZEICHNUNG>
      <INDEXNAME>nauheim</INDEXNAME>
      <BIS_DATUM_JAHR>1867</BIS_DATUM_JAHR>
   </ITEM>
   <ITEM num="77">
      <ID>77330</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Bad Nauheim</BEZEICHNUNG>
      <INDEXNAME>bad nauheim</INDEXNAME>
   </ITEM>
   <ITEM num="78">
      <ID>77340</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Balingen</BEZEICHNUNG>
      <INDEXNAME>balingen</INDEXNAME>
   </ITEM>
   <ITEM num="79">
      <ID>77342</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Balme</BEZEICHNUNG>
      <INDEXNAME>balme</INDEXNAME>
   </ITEM>
   <ITEM num="80">
      <ID>77344</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Bamberg</BEZEICHNUNG>
      <INDEXNAME>bamberg</INDEXNAME>
   </ITEM>
   <ITEM num="81">
      <ID>77352</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Bärenwalde</BEZEICHNUNG>
      <INDEXNAME>baerenwalde</INDEXNAME>
      <BIS_DATUM_JAHR>1994</BIS_DATUM_JAHR>
   </ITEM>
   <ITEM num="82">
      <ID>77357</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Basel</BEZEICHNUNG>
      <INDEXNAME>basel</INDEXNAME>
   </ITEM>
   <ITEM num="83">
      <ID>77362</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Baumannshöhle</BEZEICHNUNG>
      <INDEXNAME>baumannshoehle</INDEXNAME>
   </ITEM>
   <ITEM num="84">
      <ID>77365</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Bayreuth</BEZEICHNUNG>
      <INDEXNAME>bayreuth</INDEXNAME>
   </ITEM>
   <ITEM num="85">
      <ID>77367</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Beckenried</BEZEICHNUNG>
      <INDEXNAME>beckenried</INDEXNAME>
   </ITEM>
   <ITEM num="86">
      <ID>77369</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Belgrad</BEZEICHNUNG>
      <INDEXNAME>belgrad</INDEXNAME>
   </ITEM>
   <ITEM num="87">
      <ID>77371</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Belvedere (Weimar)</BEZEICHNUNG>
      <INDEXNAME>belvedere weimar</INDEXNAME>
   </ITEM>
   <ITEM num="88">
      <ID>77371</ID>
      <LFDNR>2290</LFDNR>
      <BEZEICHNUNG>Schloss Belvedere (Weimar)</BEZEICHNUNG>
      <INDEXNAME>schloss belvedere weimar</INDEXNAME>
   </ITEM>
   <ITEM num="89">
      <ID>77373</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Bendorf</BEZEICHNUNG>
      <INDEXNAME>bendorf</INDEXNAME>
   </ITEM>
   <ITEM num="90">
      <ID>77378</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Berchtesgaden</BEZEICHNUNG>
      <INDEXNAME>berchtesgaden</INDEXNAME>
   </ITEM>
   <ITEM num="91">
      <ID>77378</ID>
      <LFDNR>1276</LFDNR>
      <BEZEICHNUNG>Berchtoldsgaden</BEZEICHNUNG>
      <INDEXNAME>berchtoldsgaden</INDEXNAME>
   </ITEM>
   <ITEM num="92">
      <ID>77383</ID>
      <LFDNR>772</LFDNR>
      <BEZEICHNUNG>Bad Berka</BEZEICHNUNG>
      <INDEXNAME>bad berka</INDEXNAME>
   </ITEM>
   <ITEM num="93">
      <ID>77383</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Berka (Ilm)</BEZEICHNUNG>
      <INDEXNAME>berka ilm</INDEXNAME>
   </ITEM>
   <ITEM num="94">
      <ID>77384</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Berka (Werra)</BEZEICHNUNG>
      <INDEXNAME>berka werra</INDEXNAME>
      <BIS_DATUM_TAG>31</BIS_DATUM_TAG>
      <BIS_DATUM_MONAT>12</BIS_DATUM_MONAT>
      <BIS_DATUM_JAHR>2018</BIS_DATUM_JAHR>
   </ITEM>
   <ITEM num="95">
      <ID>77386</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Berlin</BEZEICHNUNG>
      <INDEXNAME>berlin</INDEXNAME>
   </ITEM>
   <ITEM num="96">
      <ID>77387</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Bern</BEZEICHNUNG>
      <INDEXNAME>bern</INDEXNAME>
   </ITEM>
   <ITEM num="97">
      <ID>77388</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Bern (Kanton)</BEZEICHNUNG>
      <INDEXNAME>bern kanton</INDEXNAME>
   </ITEM>
   <ITEM num="98">
      <ID>77393</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Bernstadt</BEZEICHNUNG>
      <INDEXNAME>bernstadt</INDEXNAME>
   </ITEM>
   <ITEM num="99">
      <ID>77393</ID>
      <LFDNR>2483</LFDNR>
      <BEZEICHNUNG>Bierutów</BEZEICHNUNG>
      <INDEXNAME>bierutow</INDEXNAME>
   </ITEM>
   <ITEM num="100">
      <ID>77399</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Bethmannischer Garten (Frankfurt)</BEZEICHNUNG>
      <INDEXNAME>bethmannischer garten frankfurt</INDEXNAME>
   </ITEM>
   <ITEM num="101">
      <ID>77401</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Bex</BEZEICHNUNG>
      <INDEXNAME>bex</INDEXNAME>
   </ITEM>
   <ITEM num="102">
      <ID>77402</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Bieber (Offenbach)</BEZEICHNUNG>
      <INDEXNAME>bieber offenbach</INDEXNAME>
      <BIS_DATUM_JAHR>1938</BIS_DATUM_JAHR>
   </ITEM>
   <ITEM num="103">
      <ID>77403</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Biebrich</BEZEICHNUNG>
      <INDEXNAME>biebrich</INDEXNAME>
      <BIS_DATUM_JAHR>1926</BIS_DATUM_JAHR>
   </ITEM>
   <ITEM num="104">
      <ID>77404</ID>
      <LFDNR>646</LFDNR>
      <BEZEICHNUNG>Pöhlberg</BEZEICHNUNG>
      <INDEXNAME>poehlberg</INDEXNAME>
   </ITEM>
   <ITEM num="105">
      <ID>77404</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Bielberg</BEZEICHNUNG>
      <INDEXNAME>bielberg</INDEXNAME>
   </ITEM>
   <ITEM num="106">
      <ID>77405</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Bielersee</BEZEICHNUNG>
      <INDEXNAME>bielersee</INDEXNAME>
   </ITEM>
   <ITEM num="107">
      <ID>77408</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Bilin</BEZEICHNUNG>
      <INDEXNAME>bilin</INDEXNAME>
   </ITEM>
   <ITEM num="108">
      <ID>77408</ID>
      <LFDNR>1641</LFDNR>
      <BEZEICHNUNG>Bílina</BEZEICHNUNG>
      <INDEXNAME>bilina</INDEXNAME>
   </ITEM>
   <ITEM num="109">
      <ID>77409</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Bingen am Rhein</BEZEICHNUNG>
      <INDEXNAME>bingen am rhein</INDEXNAME>
   </ITEM>
   <ITEM num="110">
      <ID>77410</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Binger Loch</BEZEICHNUNG>
      <INDEXNAME>binger loch</INDEXNAME>
   </ITEM>
   <ITEM num="111">
      <ID>77416</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Birs</BEZEICHNUNG>
      <INDEXNAME>birs</INDEXNAME>
   </ITEM>
   <ITEM num="112">
      <ID>77416</ID>
      <LFDNR>420</LFDNR>
      <BEZEICHNUNG>Birsch</BEZEICHNUNG>
      <INDEXNAME>birsch</INDEXNAME>
   </ITEM>
   <ITEM num="113">
      <ID>77422</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Blankenburg (Harz)</BEZEICHNUNG>
      <INDEXNAME>blankenburg harz</INDEXNAME>
   </ITEM>
   <ITEM num="114">
      <ID>77425</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Bleiberg</BEZEICHNUNG>
      <INDEXNAME>bleiberg</INDEXNAME>
   </ITEM>
   <ITEM num="115">
      <ID>77425</ID>
      <LFDNR>1666</LFDNR>
      <BEZEICHNUNG>Bad Bleiberg</BEZEICHNUNG>
      <INDEXNAME>bad bleiberg</INDEXNAME>
   </ITEM>
   <ITEM num="116">
      <ID>77427</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Bleystadt</BEZEICHNUNG>
      <INDEXNAME>bleystadt</INDEXNAME>
   </ITEM>
   <ITEM num="117">
      <ID>77427</ID>
      <LFDNR>421</LFDNR>
      <BEZEICHNUNG>Bleistadt</BEZEICHNUNG>
      <INDEXNAME>bleistadt</INDEXNAME>
   </ITEM>
   <ITEM num="118">
      <ID>77429</ID>
      <LFDNR>1362</LFDNR>
      <BEZEICHNUNG>Frankfurt-Bockenheim</BEZEICHNUNG>
      <INDEXNAME>frankfurt-bockenheim</INDEXNAME>
   </ITEM>
   <ITEM num="119">
      <ID>77429</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Bockenheim (Frankfurt am Main)</BEZEICHNUNG>
      <INDEXNAME>bockenheim frankfurt am main</INDEXNAME>
      <BIS_DATUM_TAG>31</BIS_DATUM_TAG>
      <BIS_DATUM_MONAT>3</BIS_DATUM_MONAT>
      <BIS_DATUM_JAHR>1895</BIS_DATUM_JAHR>
   </ITEM>
   <ITEM num="120">
      <ID>77431</ID>
      <LFDNR>222</LFDNR>
      <BEZEICHNUNG>Bude</BEZEICHNUNG>
      <INDEXNAME>bude</INDEXNAME>
   </ITEM>
   <ITEM num="121">
      <ID>77431</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Bode</BEZEICHNUNG>
      <INDEXNAME>bode</INDEXNAME>
   </ITEM>
   <ITEM num="122">
      <ID>77433</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Bodensee</BEZEICHNUNG>
      <INDEXNAME>bodensee</INDEXNAME>
   </ITEM>
   <ITEM num="123">
      <ID>77439</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Böhmen</BEZEICHNUNG>
      <INDEXNAME>boehmen</INDEXNAME>
      <BIS_DATUM_TAG>27</BIS_DATUM_TAG>
      <BIS_DATUM_MONAT>10</BIS_DATUM_MONAT>
      <BIS_DATUM_JAHR>1918</BIS_DATUM_JAHR>
   </ITEM>
   <ITEM num="124">
      <ID>77446</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Bologna</BEZEICHNUNG>
      <INDEXNAME>bologna</INDEXNAME>
   </ITEM>
   <ITEM num="125">
      <ID>77448</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Bonn</BEZEICHNUNG>
      <INDEXNAME>bonn</INDEXNAME>
   </ITEM>
   <ITEM num="126">
      <ID>77454</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Boston</BEZEICHNUNG>
      <INDEXNAME>boston</INDEXNAME>
   </ITEM>
   <ITEM num="127">
      <ID>77460</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Bozen</BEZEICHNUNG>
      <INDEXNAME>bozen</INDEXNAME>
   </ITEM>
   <ITEM num="128">
      <ID>77468</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Braubach</BEZEICHNUNG>
      <INDEXNAME>braubach</INDEXNAME>
   </ITEM>
   <ITEM num="129">
      <ID>77471</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Braunschweig</BEZEICHNUNG>
      <INDEXNAME>braunschweig</INDEXNAME>
   </ITEM>
   <ITEM num="130">
      <ID>77473</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Bregenz</BEZEICHNUNG>
      <INDEXNAME>bregenz</INDEXNAME>
   </ITEM>
   <ITEM num="131">
      <ID>77476</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Breitenbrunn</BEZEICHNUNG>
      <INDEXNAME>breitenbrunn</INDEXNAME>
   </ITEM>
   <ITEM num="132">
      <ID>77477</ID>
      <LFDNR>523</LFDNR>
      <BEZEICHNUNG>Giesbach</BEZEICHNUNG>
      <INDEXNAME>giesbach</INDEXNAME>
   </ITEM>
   <ITEM num="133">
      <ID>77477</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Breitengüßbach</BEZEICHNUNG>
      <INDEXNAME>breitenguessbach</INDEXNAME>
   </ITEM>
   <ITEM num="134">
      <ID>77479</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Bremen</BEZEICHNUNG>
      <INDEXNAME>bremen</INDEXNAME>
   </ITEM>
   <ITEM num="135">
      <ID>77483</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Brenner</BEZEICHNUNG>
      <INDEXNAME>brenner</INDEXNAME>
   </ITEM>
   <ITEM num="136">
      <ID>77484</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Brescia</BEZEICHNUNG>
      <INDEXNAME>brescia</INDEXNAME>
   </ITEM>
   <ITEM num="137">
      <ID>77485</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Breslau</BEZEICHNUNG>
      <INDEXNAME>breslau</INDEXNAME>
   </ITEM>
   <ITEM num="138">
      <ID>77485</ID>
      <LFDNR>1841</LFDNR>
      <BEZEICHNUNG>Wroclaw</BEZEICHNUNG>
      <INDEXNAME>wroclaw</INDEXNAME>
   </ITEM>
   <ITEM num="139">
      <ID>77490</ID>
      <LFDNR>422</LFDNR>
      <BEZEICHNUNG>Blocksberg (Brocken)</BEZEICHNUNG>
      <INDEXNAME>blocksberg brocken</INDEXNAME>
   </ITEM>
   <ITEM num="140">
      <ID>77490</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Brocken</BEZEICHNUNG>
      <INDEXNAME>brocken</INDEXNAME>
   </ITEM>
   <ITEM num="141">
      <ID>77493</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Bruchsal</BEZEICHNUNG>
      <INDEXNAME>bruchsal</INDEXNAME>
   </ITEM>
   <ITEM num="142">
      <ID>77496</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Brunnen</BEZEICHNUNG>
      <INDEXNAME>brunnen</INDEXNAME>
   </ITEM>
   <ITEM num="143">
      <ID>77498</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Brüssel</BEZEICHNUNG>
      <INDEXNAME>bruessel</INDEXNAME>
   </ITEM>
   <ITEM num="144">
      <ID>77499</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Brezina</BEZEICHNUNG>
      <INDEXNAME>brezina</INDEXNAME>
   </ITEM>
   <ITEM num="145">
      <ID>77499</ID>
      <LFDNR>2315</LFDNR>
      <BEZEICHNUNG>Brzezina</BEZEICHNUNG>
      <INDEXNAME>brzezina</INDEXNAME>
   </ITEM>
   <ITEM num="146">
      <ID>77505</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Buchsweiler</BEZEICHNUNG>
      <INDEXNAME>buchsweiler</INDEXNAME>
   </ITEM>
   <ITEM num="147">
      <ID>77505</ID>
      <LFDNR>622</LFDNR>
      <BEZEICHNUNG>Bouxwiller</BEZEICHNUNG>
      <INDEXNAME>bouxwiller</INDEXNAME>
   </ITEM>
   <ITEM num="148">
      <ID>77506</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Budapest</BEZEICHNUNG>
      <INDEXNAME>budapest</INDEXNAME>
      <VON_DATUM_JAHR>1873</VON_DATUM_JAHR>
   </ITEM>
   <ITEM num="149">
      <ID>77509</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Budweis</BEZEICHNUNG>
      <INDEXNAME>budweis</INDEXNAME>
   </ITEM>
   <ITEM num="150">
      <ID>77512</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Bufleben</BEZEICHNUNG>
      <INDEXNAME>bufleben</INDEXNAME>
   </ITEM>
   <ITEM num="151">
      <ID>77513</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Bühl</BEZEICHNUNG>
      <INDEXNAME>buehl</INDEXNAME>
   </ITEM>
   <ITEM num="152">
      <ID>77513</ID>
      <LFDNR>2409</LFDNR>
      <BEZEICHNUNG>Bühl b. Aarberg</BEZEICHNUNG>
      <INDEXNAME>buehl b aarberg</INDEXNAME>
   </ITEM>
   <ITEM num="153">
      <ID>77515</ID>
      <LFDNR>631</LFDNR>
      <BEZEICHNUNG>Jungbunzlau</BEZEICHNUNG>
      <INDEXNAME>jungbunzlau</INDEXNAME>
      <BIS_DATUM_JAHR>1945</BIS_DATUM_JAHR>
   </ITEM>
   <ITEM num="154">
      <ID>77515</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Bunzlau</BEZEICHNUNG>
      <INDEXNAME>bunzlau</INDEXNAME>
   </ITEM>
   <ITEM num="155">
      <ID>77518</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Bürgel</BEZEICHNUNG>
      <INDEXNAME>buergel</INDEXNAME>
   </ITEM>
   <ITEM num="156">
      <ID>77524</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Buttelstedt</BEZEICHNUNG>
      <INDEXNAME>buttelstedt</INDEXNAME>
      <BIS_DATUM_TAG>31</BIS_DATUM_TAG>
      <BIS_DATUM_MONAT>12</BIS_DATUM_MONAT>
      <BIS_DATUM_JAHR>2018</BIS_DATUM_JAHR>
   </ITEM>
   <ITEM num="157">
      <ID>77525</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Buttstädt</BEZEICHNUNG>
      <INDEXNAME>buttstaedt</INDEXNAME>
   </ITEM>
   <ITEM num="158">
      <ID>77527</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Calais</BEZEICHNUNG>
      <INDEXNAME>calais</INDEXNAME>
   </ITEM>
   <ITEM num="159">
      <ID>77529</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Caltanisetta</BEZEICHNUNG>
      <INDEXNAME>caltanisetta</INDEXNAME>
   </ITEM>
   <ITEM num="160">
      <ID>77530</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Cambridge</BEZEICHNUNG>
      <INDEXNAME>cambridge</INDEXNAME>
   </ITEM>
   <ITEM num="161">
      <ID>77534</ID>
      <LFDNR>623</LFDNR>
      <BEZEICHNUNG>Phlegräische Felder</BEZEICHNUNG>
      <INDEXNAME>phlegraeische felder</INDEXNAME>
   </ITEM>
   <ITEM num="162">
      <ID>77534</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Campi Phlegraei</BEZEICHNUNG>
      <INDEXNAME>campi phlegraei</INDEXNAME>
   </ITEM>
   <ITEM num="163">
      <ID>77537</ID>
      <LFDNR>1088</LFDNR>
      <BEZEICHNUNG>Kamsdorf</BEZEICHNUNG>
      <INDEXNAME>kamsdorf</INDEXNAME>
   </ITEM>
   <ITEM num="164">
      <ID>77537</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Camsdorf</BEZEICHNUNG>
      <INDEXNAME>camsdorf</INDEXNAME>
   </ITEM>
   <ITEM num="165">
      <ID>77541</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Cannstadt</BEZEICHNUNG>
      <INDEXNAME>cannstadt</INDEXNAME>
      <BIS_DATUM_TAG>31</BIS_DATUM_TAG>
      <BIS_DATUM_MONAT>3</BIS_DATUM_MONAT>
      <BIS_DATUM_JAHR>1905</BIS_DATUM_JAHR>
   </ITEM>
   <ITEM num="166">
      <ID>77541</ID>
      <LFDNR>809</LFDNR>
      <BEZEICHNUNG>Cannstatt</BEZEICHNUNG>
      <INDEXNAME>cannstatt</INDEXNAME>
   </ITEM>
   <ITEM num="167">
      <ID>77541</ID>
      <LFDNR>2502</LFDNR>
      <BEZEICHNUNG>Kannstadt</BEZEICHNUNG>
      <INDEXNAME>kannstadt</INDEXNAME>
   </ITEM>
   <ITEM num="168">
      <ID>77547</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Caravaggio</BEZEICHNUNG>
      <INDEXNAME>caravaggio</INDEXNAME>
   </ITEM>
   <ITEM num="169">
      <ID>77551</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Carrara</BEZEICHNUNG>
      <INDEXNAME>carrara</INDEXNAME>
   </ITEM>
   <ITEM num="170">
      <ID>77554</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Caserta</BEZEICHNUNG>
      <INDEXNAME>caserta</INDEXNAME>
   </ITEM>
   <ITEM num="171">
      <ID>77557</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Castelvetrano</BEZEICHNUNG>
      <INDEXNAME>castelvetrano</INDEXNAME>
   </ITEM>
   <ITEM num="172">
      <ID>77558</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Castro Giovanni</BEZEICHNUNG>
      <INDEXNAME>castro giovanni</INDEXNAME>
   </ITEM>
   <ITEM num="173">
      <ID>77558</ID>
      <LFDNR>345</LFDNR>
      <BEZEICHNUNG>Enna</BEZEICHNUNG>
      <INDEXNAME>enna</INDEXNAME>
   </ITEM>
   <ITEM num="174">
      <ID>77561</ID>
      <LFDNR>0</LFDNR>
      <BEZEICHNUNG>Catania</BEZEICHNUNG>
      <INDEXNAME>catania</INDEXNAME>
   </ITEM>
   <ITEM num="175">
      <ID>77566</ID>
      <LFDNR>0</LFDNR>