<?xml version = "1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE NSL_AGRELON [
<!ELEMENT NSL_AGRELON (ITEM)*>
<!ELEMENT ITEM (IDENT, KATEGORIE?, BEZIEHUNG?, URI?, CORRIDENT?)>
<!ATTLIST ITEM num CDATA #REQUIRED>
<!ELEMENT IDENT (#PCDATA)>
<!ELEMENT KATEGORIE (#PCDATA)>
<!ELEMENT BEZIEHUNG (#PCDATA)>
<!ELEMENT URI (#PCDATA)>
<!ELEMENT CORRIDENT (#PCDATA)>
]>
<NSL_AGRELON>
   <ITEM num="1">
      <IDENT>5030</IDENT>
      <KATEGORIE>Vitaler/letaler Kontakt</KATEGORIE>
      <BEZIEHUNG>hat Mordopfer</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#hasMurderee</URI>
      <CORRIDENT>5040</CORRIDENT>
   </ITEM>
   <ITEM num="2">
      <IDENT>5040</IDENT>
      <KATEGORIE>Vitaler/letaler Kontakt</KATEGORIE>
      <BEZIEHUNG>hat Mörder</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#hasMurderer</URI>
      <CORRIDENT>5030</CORRIDENT>
   </ITEM>
   <ITEM num="3">
      <IDENT>2060</IDENT>
      <KATEGORIE>Gruppenbeteiligung</KATEGORIE>
      <BEZIEHUNG>ist Besitzer von</BEZIEHUNG>
      <CORRIDENT>2050</CORRIDENT>
   </ITEM>
   <ITEM num="4">
      <IDENT>4012</IDENT>
      <KATEGORIE>Verwandtschaft</KATEGORIE>
      <BEZIEHUNG>hat Pflegeelternteil</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#hasFosterParent</URI>
      <CORRIDENT>4032</CORRIDENT>
   </ITEM>
   <ITEM num="5">
      <IDENT>4032</IDENT>
      <KATEGORIE>Verwandtschaft</KATEGORIE>
      <BEZIEHUNG>hat Pflegekind</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#hasFosterChild</URI>
      <CORRIDENT>4012</CORRIDENT>
   </ITEM>
   <ITEM num="6">
      <IDENT>2050</IDENT>
      <KATEGORIE>Gruppenbeteiligung</KATEGORIE>
      <BEZIEHUNG>hat Besitzer</BEZIEHUNG>
      <CORRIDENT>2060</CORRIDENT>
   </ITEM>
   <ITEM num="7">
      <IDENT>1010</IDENT>
      <KATEGORIE>Private Bekanntschaft</KATEGORIE>
      <BEZIEHUNG>hat Freund</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#hasFriend</URI>
      <CORRIDENT>1010</CORRIDENT>
   </ITEM>
   <ITEM num="8">
      <IDENT>2010</IDENT>
      <KATEGORIE>Gruppenbeteiligung</KATEGORIE>
      <BEZIEHUNG>hat Gründer</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#hasFounder</URI>
      <CORRIDENT>2020</CORRIDENT>
   </ITEM>
   <ITEM num="9">
      <IDENT>2020</IDENT>
      <KATEGORIE>Gruppenbeteiligung</KATEGORIE>
      <BEZIEHUNG>ist Gründer von</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#isFounderOf</URI>
      <CORRIDENT>2010</CORRIDENT>
   </ITEM>
   <ITEM num="10">
      <IDENT>2030</IDENT>
      <KATEGORIE>Gruppenbeteiligung</KATEGORIE>
      <BEZIEHUNG>hat Mitglied</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#hasMember</URI>
      <CORRIDENT>2040</CORRIDENT>
   </ITEM>
   <ITEM num="11">
      <IDENT>2040</IDENT>
      <KATEGORIE>Gruppenbeteiligung</KATEGORIE>
      <BEZIEHUNG>ist Mitglied von</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#isMemberOf</URI>
      <CORRIDENT>2030</CORRIDENT>
   </ITEM>
   <ITEM num="12">
      <IDENT>3010</IDENT>
      <KATEGORIE>Beruflicher Kontakt</KATEGORIE>
      <BEZIEHUNG>hat Kollaborator</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#hasCooperator</URI>
      <CORRIDENT>3010</CORRIDENT>
   </ITEM>
   <ITEM num="13">
      <IDENT>3020</IDENT>
      <KATEGORIE>Beruflicher Kontakt</KATEGORIE>
      <BEZIEHUNG>hat Einfluss auf</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#hasInfluenceDonee</URI>
      <CORRIDENT>3030</CORRIDENT>
   </ITEM>
   <ITEM num="14">
      <IDENT>3030</IDENT>
      <KATEGORIE>Beruflicher Kontakt</KATEGORIE>
      <BEZIEHUNG>ist beeinflusst durch</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#hasInfluenceDonor</URI>
      <CORRIDENT>3020</CORRIDENT>
   </ITEM>
   <ITEM num="15">
      <IDENT>3040</IDENT>
      <KATEGORIE>Beruflicher Kontakt</KATEGORIE>
      <BEZIEHUNG>hat Muse</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#hasMuse</URI>
      <CORRIDENT>3050</CORRIDENT>
   </ITEM>
   <ITEM num="16">
      <IDENT>3050</IDENT>
      <KATEGORIE>Beruflicher Kontakt</KATEGORIE>
      <BEZIEHUNG>ist Muse von</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#isMuseOf</URI>
      <CORRIDENT>3040</CORRIDENT>
   </ITEM>
   <ITEM num="17">
      <IDENT>3060</IDENT>
      <KATEGORIE>Beruflicher Kontakt</KATEGORIE>
      <BEZIEHUNG>hat Mäzen</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#hasPatron</URI>
      <CORRIDENT>3070</CORRIDENT>
   </ITEM>
   <ITEM num="18">
      <IDENT>3070</IDENT>
      <KATEGORIE>Beruflicher Kontakt</KATEGORIE>
      <BEZIEHUNG>ist Mäzen von</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#isPatronOf</URI>
      <CORRIDENT>3060</CORRIDENT>
   </ITEM>
   <ITEM num="19">
      <IDENT>3080</IDENT>
      <KATEGORIE>Beruflicher Kontakt</KATEGORIE>
      <BEZIEHUNG>hat Schüler</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#hasStudent</URI>
      <CORRIDENT>3090</CORRIDENT>
   </ITEM>
   <ITEM num="20">
      <IDENT>3090</IDENT>
      <KATEGORIE>Beruflicher Kontakt</KATEGORIE>
      <BEZIEHUNG>hat Lehrer</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#hasTeacher</URI>
      <CORRIDENT>3080</CORRIDENT>
   </ITEM>
   <ITEM num="21">
      <IDENT>4010</IDENT>
      <KATEGORIE>Verwandtschaft</KATEGORIE>
      <BEZIEHUNG>hat Elternteil</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#hasParent</URI>
      <CORRIDENT>4030</CORRIDENT>
   </ITEM>
   <ITEM num="22">
      <IDENT>4020</IDENT>
      <KATEGORIE>Verwandtschaft</KATEGORIE>
      <BEZIEHUNG>hat Großelternteil</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#hasGrandParent</URI>
      <CORRIDENT>4040</CORRIDENT>
   </ITEM>
   <ITEM num="23">
      <IDENT>4030</IDENT>
      <KATEGORIE>Verwandtschaft</KATEGORIE>
      <BEZIEHUNG>hat Kind</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#hasChild</URI>
      <CORRIDENT>4010</CORRIDENT>
   </ITEM>
   <ITEM num="24">
      <IDENT>4040</IDENT>
      <KATEGORIE>Verwandtschaft</KATEGORIE>
      <BEZIEHUNG>hat Enkel</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#hasGrandChild</URI>
      <CORRIDENT>4020</CORRIDENT>
   </ITEM>
   <ITEM num="25">
      <IDENT>4050</IDENT>
      <KATEGORIE>Verwandtschaft</KATEGORIE>
      <BEZIEHUNG>hat Tante/Onkel</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#hasAuntUncle</URI>
      <CORRIDENT>4110</CORRIDENT>
   </ITEM>
   <ITEM num="26">
      <IDENT>4060</IDENT>
      <KATEGORIE>Verwandtschaft</KATEGORIE>
      <BEZIEHUNG>hat Cousin</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#hasCousin</URI>
      <CORRIDENT>4060</CORRIDENT>
   </ITEM>
   <ITEM num="27">
      <IDENT>4070</IDENT>
      <KATEGORIE>Verwandtschaft</KATEGORIE>
      <BEZIEHUNG>hat Patenkind</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#hasGodChild</URI>
      <CORRIDENT>4080</CORRIDENT>
   </ITEM>
   <ITEM num="28">
      <IDENT>4080</IDENT>
      <KATEGORIE>Verwandtschaft</KATEGORIE>
      <BEZIEHUNG>hat Pate</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#hasGodParent</URI>
      <CORRIDENT>4070</CORRIDENT>
   </ITEM>
   <ITEM num="29">
      <IDENT>4090</IDENT>
      <KATEGORIE>Verwandtschaft</KATEGORIE>
      <BEZIEHUNG>hat Schwager/Schwägerin</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#hasSiblingInlaw</URI>
      <CORRIDENT>4090</CORRIDENT>
   </ITEM>
   <ITEM num="30">
      <IDENT>4100</IDENT>
      <KATEGORIE>Verwandtschaft</KATEGORIE>
      <BEZIEHUNG>hat Ehepartner</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#hasSpouse</URI>
      <CORRIDENT>4100</CORRIDENT>
   </ITEM>
   <ITEM num="31">
      <IDENT>4110</IDENT>
      <KATEGORIE>Verwandtschaft</KATEGORIE>
      <BEZIEHUNG>hat Nichte/Neffe</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#hasNieceNephew</URI>
      <CORRIDENT>4050</CORRIDENT>
   </ITEM>
   <ITEM num="32">
      <IDENT>4120</IDENT>
      <KATEGORIE>Verwandtschaft</KATEGORIE>
      <BEZIEHUNG>hat Geschwister</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#hasSibling</URI>
      <CORRIDENT>4120</CORRIDENT>
   </ITEM>
   <ITEM num="33">
      <IDENT>5010</IDENT>
      <KATEGORIE>Vitaler/letaler Kontakt</KATEGORIE>
      <BEZIEHUNG>hat Arzt</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#hasPhysician</URI>
      <CORRIDENT>5020</CORRIDENT>
   </ITEM>
   <ITEM num="34">
      <IDENT>5020</IDENT>
      <KATEGORIE>Vitaler/letaler Kontakt</KATEGORIE>
      <BEZIEHUNG>ist Arzt von</BEZIEHUNG>
      <URI>http://d-nb.info/standards/elementset/agrelon#isPhysicianOf</URI>
      <CORRIDENT>5010</CORRIDENT>
   </ITEM>
   <ITEM num="35">
      <IDENT>4130</IDENT>
      <KATEGORIE>Verwandtschaft</KATEGORIE>
      <BEZIEHUNG>hat Urenkel</BEZIEHUNG>
      <CORRIDENT>4140</CORRIDENT>
   </ITEM>
   <ITEM num="36">
      <IDENT>4140</IDENT>
      <KATEGORIE>Verwandtschaft</KATEGORIE>
      <BEZIEHUNG>hat Urgroßelternteil</BEZIEHUNG>
      <CORRIDENT>4130</CORRIDENT>
   </ITEM>
   <ITEM num="37">
      <IDENT>7010</IDENT>
      <KATEGORIE>Geografikum</KATEGORIE>
      <BEZIEHUNG>ist übergeordnet</BEZIEHUNG>
      <CORRIDENT>7020</CORRIDENT>
   </ITEM>
   <ITEM num="38">
      <IDENT>7020</IDENT>
      <KATEGORIE>Geografikum</KATEGORIE>
      <BEZIEHUNG>ist untergeordnet</BEZIEHUNG>
      <CORRIDENT>7010</CORRIDENT>
   </ITEM>
   <ITEM num="39">
      <IDENT>3100</IDENT>
      <KATEGORIE>Beruflicher Kontakt</KATEGORIE>
      <BEZIEHUNG>hat Vorgänger</BEZIEHUNG>
      <CORRIDENT>3110</CORRIDENT>
   </ITEM>
   <ITEM num="40">
      <IDENT>3110</IDENT>
      <KATEGORIE>Beruflicher Kontakt</KATEGORIE>
      <BEZIEHUNG>hat Nachfolger</BEZIEHUNG>
      <CORRIDENT>3100</CORRIDENT>
   </ITEM>
   <ITEM num="41">
      <IDENT>8010</IDENT>
      <KATEGORIE>Werk</KATEGORIE>
      <BEZIEHUNG>ist Übersetzung von</BEZIEHUNG>
      <CORRIDENT>8020</CORRIDENT>
   </ITEM>
   <ITEM num="42">
      <IDENT>8020</IDENT>
      <KATEGORIE>Werk</KATEGORIE>
      <BEZIEHUNG>hat Übersetzung</BEZIEHUNG>
      <CORRIDENT>8010</CORRIDENT>
   </ITEM>
   <ITEM num="43">
      <IDENT>8030</IDENT>
      <KATEGORIE>Werk</KATEGORIE>
      <BEZIEHUNG>ist Rezension von</BEZIEHUNG>
      <CORRIDENT>8040</CORRIDENT>
   </ITEM>
   <ITEM num="44">
      <IDENT>8040</IDENT>
      <KATEGORIE>Werk</KATEGORIE>
      <BEZIEHUNG>hat Rezension</BEZIEHUNG>
      <CORRIDENT>8030</CORRIDENT>
   </ITEM>
</NSL_AGRELON>
