<?xml version = "1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE PROJEKT_GOEBRIEFE [
<!ELEMENT PROJEKT_GOEBRIEFE (ITEM)*>
<!ELEMENT ITEM (ID, REGISTEREINTRAG?)>
<!ATTLIST ITEM num CDATA #REQUIRED>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT REGISTEREINTRAG (#PCDATA)>
]>
<PROJEKT_GOEBRIEFE>
   <ITEM num="1">
      <ID>875</ID>
      <REGISTEREINTRAG>Boydell, John (1719-1804), britischer Kupferstecher, der seine eigenen und die Werke anderer Künstler auch verlegte und verkaufte</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="2">
      <ID>927</ID>
      <REGISTEREINTRAG>Breitenbauch, Heinrich Ferdinand von (1767-1836), sachsen-weimarischer Offizier, seit 1798 verheiratet mit Dorothée Elisabethe Wilhelmine von Oldershausen, 1802 Hauptmann, 1804 verabschiedet, jüngster Sohn von Georg August von B. (s. auch RA 2)</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="3">
      <ID>1492</ID>
      <REGISTEREINTRAG>Darbes, Joseph Friedrich August (1747-1810), Porträtmaler, zunächst in St. Petersburg, seit 1785 in Berlin, seit 1796 dort Professor an der königlichen Akademie der bildenden Künste</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="4">
      <ID>1906</ID>
      <REGISTEREINTRAG>Faciius, #k#Angelika#/k# Bellonate (1806–1887), Bildhauerin, Stein- und Stempelschneiderin, Tochter von Friedrich Wilhelm F.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="5">
      <ID>2054</ID>
      <REGISTEREINTRAG>Förster, #r#Ernst#/r# Joachim (1800-1885), Maler, Kunstschriftsteller und Publizist, seit 1825 in München, seit 1826 Schwiegersohn von Jean Paul</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="6">
      <ID>2390</ID>
      <REGISTEREINTRAG>Geyser (Geiser), Christian Gottlieb (1742-1803), Kupferstecher, Miniaturmaler und Illustrator in Leipzig, seit 1761 Schüler Adam Friedrich Oesers, von 1766 bis 1770 Lehrer für Kupferstich an der Leipziger Kunstakademie, seit 1771 ordentliches Mitglied der Leipziger Kunstakademie,  in zweiter Ehe verheiratet mit Adam Friedrich Oesers Tochter Wilhelmine</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="7">
      <ID>2475</ID>
      <REGISTEREINTRAG>Goethe, Johann Wolfgang (seit 1782: von) (1749-1832), Pseudonym Wilton (Band 8.2, S. 190)</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="8">
      <ID>2696</ID>
      <REGISTEREINTRAG>Haas, Meno (1752-1833), Kupferstecher in Berlin</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="9">
      <ID>3128</ID>
      <REGISTEREINTRAG>Holloway, Thomas (1748-1828), englischer Kupferstecher</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="10">
      <ID>3190</ID>
      <REGISTEREINTRAG>Hose, Johann Heinrich (1765-1841), Zeichenlehrer an der Zeichenschule in Eisenach, ab 1809 Hofbildhauer in Weimar</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="11">
      <ID>3198</ID>
      <REGISTEREINTRAG>Houdon, Jean-Antoine (1741-1828), französischer Bildhauer</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="12">
      <ID>3267</ID>
      <REGISTEREINTRAG>Imhoff, Christoph Adam Carl  von (1734-1788), Portrait- und Miniaturmaler, Offizier in Hessen-Kassel, später in Württemberg, in erster Ehe Mann von Anna Maria Apollonia Chapusset verh. Hastings, von 1767 bis 1769 in London, danach bis 1773 in Indien, 1775 Heirat mit Louise von Schardt, einer Schwester von Charlotte von Steins, bis 1785 auf dem Familiengut in Mörlach bei Nürnberg, seit 1786 Unterstützung durch Herzog Carl August von Sachsen-Weimar und Eisenach </REGISTEREINTRAG>
   </ITEM>
   <ITEM num="13">
      <ID>3562</ID>
      <REGISTEREINTRAG>Kniller (Kneller), Gottfried (1646-1723), Maler, seit 1676 in London</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="14">
      <ID>3924</ID>
      <REGISTEREINTRAG>Leochares (390/385-320/315. v. Chr.), griechischer Bildhauer</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="15">
      <ID>4105</ID>
      <REGISTEREINTRAG>Lowe (Loewe), Johann Michael Siegfried (vorher: Samuel Moses) (1756-1831), Miniaturist, Maler, Kupferstecher</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="16">
      <ID>4330</ID>
      <REGISTEREINTRAG>May, Georg Oswald (1738–1816), Porträtmaler</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="17">
      <ID>4526</ID>
      <REGISTEREINTRAG>Moeglich, Andreas Leonhard (1742-1810), Zeichner und Kupferstecher</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="18">
      <ID>5233</ID>
      <REGISTEREINTRAG>Preller, Ernst Christian Johann #r#Friedrich#/r# d. Ä. (1804–1878), Maler und Zeichner in Weimar, seit 1832 Leiter der Zeichenschule in Weimar</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="19">
      <ID>5327</ID>
      <REGISTEREINTRAG>Ramberg, Johann Heinrich (1763–1840), Maler, Zeichner und Radierer, seit 1792/93 Hofmaler in Hannover</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="20">
      <ID>5848</ID>
      <REGISTEREINTRAG>Scheffauer, Philipp Jakob (1756-1808), Bildhauer</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="21">
      <ID>6002</ID>
      <REGISTEREINTRAG>Schmoll, Georg Friedrich (gest. 1785), Zeichner und Kupferstecher in Zürich</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="22">
      <ID>6005</ID>
      <REGISTEREINTRAG>Schmutzer, Jacob Matthias (1733–1811), Maler und Kupferstecher in Wien</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="23">
      <ID>6080</ID>
      <REGISTEREINTRAG>Schröder, Johann Heinrich (1757-1812), Maler</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="24">
      <ID>6371</ID>
      <REGISTEREINTRAG>Sonnenschein, Johann Valentin (1749-1828), Bildhauer, Stukkateur und Maler, Modelleur bei der Porzellanmanufaktur in Ludwigsburg, 1771 Hofstukkateur in Stuttgart, seit 1775 in Zürich, 1779 Lehrer an der Kunstschule Bern</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="25">
      <ID>6670</ID>
      <REGISTEREINTRAG>Taubert, Gustav Friedrich Amalius (1755–1839), deutscher Maler, seit 1785 in Warschau, seit 1797 in Berlin</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="26">
      <ID>6784</ID>
      <REGISTEREINTRAG>Tischbein, Johann Heinrich d. Ä. (1722-1789), Maler und Radierer, Reisen nach Paris, Venedig und Rom, Hofmaler in Kassel, 1762 Professor am Collegium Carolinum in Kassel, Onkel von Johann Heinrich Wilhelm Tischbein</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="27">
      <ID>7502</ID>
      <REGISTEREINTRAG>Ziesenis, Johann Georg (1716-1776), Porträtmaler aus Hannover, Vetter von Johann Freidrichs Blasius Z.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="28">
      <ID>7663</ID>
      <REGISTEREINTRAG>David, François Anne (1741–1824), französischer Kupferstecher, Radierer und Verleger</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="29">
      <ID>11032</ID>
      <REGISTEREINTRAG>Gout, Jean François (Johann Franz) (1748-1812), Maler und Radierer, 1780 Hofmaler in Bayreuth, 1782 von Johann Heinrich Merck an den Hof in Darmstadt empfohlen und dort Theatermaler, später in Wiesbaden, Frankfurt a. M. und Dessau</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="30">
      <ID>11085</ID>
      <REGISTEREINTRAG>Sachsen-Weimar und Eisenach, Ernst August I. Herzog von (1688-1748), seit 1707 Mitregent, seit 1728 Alleinregent von Sachsen-Weimar und Eisenach, Großvater des Herzogs Carl August von Sachsen-Weimar und Eisenach</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="31">
      <ID>11087</ID>
      <REGISTEREINTRAG>Braunschweig und Lüneburg-Wolfenbüttel, Carl I. von (1713-1780), seit 1735 regierender Herzog, Vater der Herzogin Anna Amalia von Sachsen-Weimar und Eisenach</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="32">
      <ID>11089</ID>
      <REGISTEREINTRAG>Hessen-Darmstadt, Henriette #r#Karoline#/r# Christine Philippine Luise Landgräfin von, geb. Prinzessin von Pfalz-Zweibrücken (1721-1774), seit 1741 Frau von Ludwig IX. von Hessen-Darmstadt, residierte in Darmstadt, Mutter der Herzogin#r# Louise#/r# von Sachsen-Weimar und Eisenach</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="33">
      <ID>11093</ID>
      <REGISTEREINTRAG>Russland,  Natalia Alexejewna, geb. Prinzessin #r#Wilhelmine#/r# Luise von Hessen-Darmstadt (1755-1776), Tochter von Ludwig IX. und Karoline von Hessen-Darmstadt, Schwester von Louise von Sachsen-Weimar und Eisenach, seit 1773 erste Frau von  Paul  I. Petrowitsch von Russland
</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="34">
      <ID>11094</ID>
      <REGISTEREINTRAG>England, Karl II. von (1630-1685), seit 1660 König von England, Schottland und Irland</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="35">
      <ID>11096</ID>
      <REGISTEREINTRAG>Braunschweig-Wolfenbüttel, Auguste Dorothea von (1749-1810), Dekanin, seit 1778 Äbtissin des Stifts Gandersheim, Schwester der Herzogin Anna Amalia von Sachsen-Weimar und Eisenach</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="36">
      <ID>11103</ID>
      <REGISTEREINTRAG>Sachsen-Weimar, Sophie Auguste Herzogin von, geb. Prinzessin von Anhalt-Zerbst (1663-1694), seit 1685 Frau von Johann Ernst III. </REGISTEREINTRAG>
   </ITEM>
   <ITEM num="37">
      <ID>11104</ID>
      <REGISTEREINTRAG>Sachsen-Weimar, Johann Ernst III. Herzog von (1664-1707)</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="38">
      <ID>11125</ID>
      <REGISTEREINTRAG>Épinay, #k#Louise#/k# Florence Pétronelle de La Live d’, geb. Tardieu d’Esclavelles (1726–1783), französische Literatin</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="39">
      <ID>11127</ID>
      <REGISTEREINTRAG>Rohr, Julius Bernhard von (1688-1742), Kameralist, Jurist, Naturwissenschaftler und Schriftsteller in Merseburg</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="40">
      <ID>11142</ID>
      <REGISTEREINTRAG>Sachsen, Sibylle von, geb. Prinzessin von Jülich-Cleve-Berg (1512-1554), seit 1527 Frau von Johann Friedrich I. von Sachsen </REGISTEREINTRAG>
   </ITEM>
   <ITEM num="41">
      <ID>11143</ID>
      <REGISTEREINTRAG>Sachsen, Johann Friedrich II. (der Mittlere), Herzog von (1529-1595), Sohn von Johann Friedrich I. und Sibylle von Sachsen</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="42">
      <ID>11144</ID>
      <REGISTEREINTRAG>Sachsen-Weimar, Johann Wilhelm I. Maria, Herzog von (1530-1573), Sohn von Johann Friedrich I. und Sibylle von Sachsen</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="43">
      <ID>11146</ID>
      <REGISTEREINTRAG>Sachsen-Weimar, Dorothea Susanna Herzogin von, geb. Prinzessin von der Pfalz (1544-1592), Großmutter von Bernhard Herzog von Sachsen-Weimar</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="44">
      <ID>11156</ID>
      <REGISTEREINTRAG>Sachsen-Weimar, Johann Ernst I. Herzog von (1594-1626), Sohn von Johann und Dorothea Maria von Sachsen, seit 1615 regierender Herzog</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="45">
      <ID>11160</ID>
      <REGISTEREINTRAG>Kotzebue, Levin Carl Christian (1727-1761), sachsen-weimarischer Legationsrat, Geheimer Referendar der Herzogin Anna Amalia, Vater von August Kotzebue</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="46">
      <ID>11175</ID>
      <REGISTEREINTRAG>Sachsen-Weimar, Wilhelm Ernst von (1662-1728), seit 1683 Herzog</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="47">
      <ID>19814</ID>
   </ITEM>
   <ITEM num="48">
      <ID>20370</ID>
      <REGISTEREINTRAG>Heideloff, Victor Peter (1757-1817),  Hof- und Theatermaler, Professor an der Hohen Karlsschule in Stuttgart, Bruder von Johann Friedrich Carl Heideloff
</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="49">
      <ID>21911</ID>
      <REGISTEREINTRAG>Schmidt, Klamer (Clamor) Eberhard Karl (1746-1824), Domkommissar und Sekretär der Kriegs- und Domänenkammer in Halberstadt, Schriftsteller</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="50">
      <ID>22898</ID>
      <REGISTEREINTRAG>Bernard, Esther, geb. Gad, seit 1802 Sophie Luzie (#r#Lucy#/r#) Domeier (zwischen 1767 und 1770-1836?), Schriftstellerin</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="51">
      <ID>35180</ID>
      <REGISTEREINTRAG>Labacco, Antonio (1495–1570), italienischer Architekt und Kupferstecher</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="52">
      <ID>35181</ID>
      <REGISTEREINTRAG>Abegg, Johann Friedrich (1765-1840), Theologe, 1789 Gymnasiallehrer in Heidelberg tätig, seit 1791 auch Professor der klassischen Philologie an der Universität, 1794 Pfarrer in Boxberg, 1799 in Leimen und 1808 in Heidelberg, 1807 auch Mitglied des Oberkirchenrates, 1819 Professor der Theologie</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="53">
      <ID>35184</ID>
      <REGISTEREINTRAG>Abel, Johann Gotthelf Leberecht (1749-1822), Arzt, seit 1784 in Düsseldorf, Hausarzt der Familie Friedrich Heinrich Jacobis</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="54">
      <ID>35187</ID>
      <REGISTEREINTRAG>Abildgaard, #r#Nicolai#/r# Abraham (1743– 1809), dänischer Maler, Bildhauer und Architekt</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="55">
      <ID>35189</ID>
      <REGISTEREINTRAG>Abramson, Abraham (1754-1811), Medailleur und Stempelschneider in Berlin</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="56">
      <ID>35192</ID>
      <REGISTEREINTRAG>Abt (Abbt), Karl Friedrich (#k#eigentl.#/k# Johann Daniel Dettenrieder, gen. Dingerling) (1733-1783), Schauspieler in Gotha, Lübeck, Hamburg, Bremen u.a., Prinzipal einer Wandertruppe, Theaterleiter
</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="57">
      <ID>35199</ID>
      <REGISTEREINTRAG>Ackermann, Heinrich Anton (1730/31-1792), Hofsekretär und Hofadvokat in Weimar, 1779 Justizamtmann in Ilmenau</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="58">
      <ID>35204</ID>
      <REGISTEREINTRAG>Ackermann, Maria Anna, geb. Schumann (um 1757-1830), aus Winkel im Rheingau, seit 1780 verheirtet mit dem Bankier, Handelsmann und kurmainzischen Salzfaktor Andreas Ackermann in Mainz, 1802 verwitwet, zuletzt in Frankfurt am Main</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="59">
      <ID>35206</ID>
      <REGISTEREINTRAG>Ackermann, Sophie, geb. Tschorn (um 1760-1815), Sängerin und Schauspielerin in der Bellomoschen Theatertruppe in Weimar, seit 1780 Frau von Gottfried Ackermann</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="60">
      <ID>35208</ID>
      <REGISTEREINTRAG>Acton, John Francis Edward Sir (1736-1811), neapolitanischer Staatsmann und Offizier, von 1784 bis 1806 Premierminister von Neapel</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="61">
      <ID>35211</ID>
      <REGISTEREINTRAG>Addison, Joseph (1672-1719), englischer Politiker, Journalist und Schriftsteller, Mitbegründer der Zeitschriften &quot;The Tatler&quot;, &quot;The Spectator&quot; und &quot;The Guardian&quot;</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="62">
      <ID>35212</ID>
      <REGISTEREINTRAG>Adelung, Johann Christoph (1732-1806), seit 1765 Redakteur, Sprachforscher und Übersetzer in Leipzig, seit 1787 kurfürstlicher Bibliothekar in Dresden</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="63">
      <ID>35214</ID>
      <REGISTEREINTRAG>Aehnelt, Christian Gottfried (gest. nach 1800), Mechaniker und Optiker in Dresden</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="64">
      <ID>35218</ID>
      <REGISTEREINTRAG>Aischylos (Aeschylus) (525/24-456 v. Chr.), griechischer Tragödiendichter</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="65">
      <ID>35219</ID>
      <REGISTEREINTRAG>Äsop (Aisopos) (6. Jh. v. Chr.), griechischer Fabeldichter</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="66">
      <ID>35227</ID>
      <REGISTEREINTRAG>Albani, Francesco (1578-1660), italienischer Maler</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="67">
      <ID>35236</ID>
   </ITEM>
   <ITEM num="68">
      <ID>35238</ID>
      <REGISTEREINTRAG>Alberti, Leon Battista (1404–1472), italienischer Architekt, Schriftsteller und Kunsttheoretiker</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="69">
      <ID>35239</ID>
      <REGISTEREINTRAG>Hensler, Wilhelmine Johanna (1777–1851), Schwester von August Wilhelm H.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="70">
      <ID>35241</ID>
      <REGISTEREINTRAG>Albinus, Bernhard Siegfried (1697-1770), deutscher Mediziner, bedeutender Vertreter der beschreibenden Anatomie, Professor für Anatomie und Chirurgie, später für Anatomie und Therapie an der Universität Leiden, zeitweise Rektor</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="71">
      <ID>35244</ID>
      <REGISTEREINTRAG>Albrecht, Adolf Ludwig (1736-1799), Kaufmann in Zeitz, Geschäftspartner von Heinrich Rapp</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="72">
      <ID>35246</ID>
      <REGISTEREINTRAG>Albrecht, Heinrich Christoph (1762/63–1800), Historiker, Sprachlehrer und Publizist, in den 1780er Jahren Gründer eines Erziehungsinstituts in Eppendorf (heute Stadtteil von Hamburg), seit Juli 1794 politischer Schriftsteller auf Gut Kielseng bei Flensburg</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="73">
      <ID>35247</ID>
      <REGISTEREINTRAG>Albrecht, Johann Georg (1694-1770), Rektor des Barfüßergymnasiums in Frankfurt a. M., von 1762 bis 1765 Goethes Hebräischlehrer</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="74">
      <ID>35248</ID>
      <REGISTEREINTRAG>Albrecht, Johann Carl Gottlob (1734-1800), Jurist, Naturforscher, Pädagoge, seit 1760 in Weimar, Geheimer Archivar, Prinzenlehrer, Legations- und Hofrat, Reisebegleiter des Prinzen Constantin von Sachsen-Weimar und Eisenach </REGISTEREINTRAG>
   </ITEM>
   <ITEM num="75">
      <ID>35251</ID>
      <REGISTEREINTRAG>Alembert, Jean Baptiste le Rond d' (1717-1783), französischer Mathematiker und Philosoph, Enzyklopädist</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="76">
      <ID>35252</ID>
      <REGISTEREINTRAG>Alexander VII. (#k#eigentl.#/k# Fabio Chigi) (1599-1667), seit 1655 Papst</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="77">
      <ID>35256</ID>
      <REGISTEREINTRAG>Alfieri, Vittorio (1749-1803), italienischer Schriftsteller und Dramatiker</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="78">
      <ID>35257</ID>
      <REGISTEREINTRAG>Algarotti, Francesco Conte (1712–1764), italienischer Schriftsteller, Kunstkritiker, Kunsthändler und Verfasser populärwissenschaftlicher Werke</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="79">
      <ID>35263</ID>
      <REGISTEREINTRAG>Altdorfer (Altdorffer), Albrecht (um 1480–1538), Maler, Kupferstecher und Baumeister</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="80">
      <ID>35266</ID>
      <REGISTEREINTRAG>Althof, Ludwig Christoph (1758–1832), Arzt in Göttingen</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="81">
      <ID>35277</ID>
      <REGISTEREINTRAG>Ambrosius, Johann Nicolaus (1744-1839), Hautboist in Weimar, um 1781 Hof- und um 1810 Kammermusiker, auch Notenschreiber für Goethe</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="82">
      <ID>35280</ID>
      <REGISTEREINTRAG>Amerongen (Amrung), Johann Friedrich Taets von (1785–1853), 1800 Page am Weimarer Hof</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="83">
      <ID>35284</ID>
      <REGISTEREINTRAG>Ammanati, Bartolomeo di Antonio (1511-1592), italienischer Baumeister und Bildhauer</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="84">
      <ID>35289</ID>
      <REGISTEREINTRAG>Amor, Caroline, geb. Frederici, (geb. 1745), verw. Naumann, Schauspielerin in Weimar</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="85">
      <ID>35295</ID>
      <REGISTEREINTRAG>André, #r#Johann#/r# Christian (1741-1799), Seidenfabrikant in Offenbach, Musikalienverleger und Komponist, von 1777 bis 1784 Musikdirektor in Berlin, Musikverleger in Offenbach</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="86">
      <ID>35303</ID>
      <REGISTEREINTRAG>Anfossi, Bonifacio Domenico #r#Pasquale#/r# (1727-1797), italienischer Komponist</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="87">
      <ID>35310</ID>
      <REGISTEREINTRAG>Anhalt-Bernburg, Friedrich Albrecht Fürst von (1735-1796), seit 1765 Fürst</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="88">
      <ID>35312</ID>
      <REGISTEREINTRAG>Anhalt-Dessau, Friedrich Erbprinz von (1769-1814), preußischer Offizier, 1794 als Generalmajor entlassen, Sohn von Fürst Leopold III. Friedrich Franz von Anhalt-Dessau</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="89">
      <ID>35324</ID>
      <REGISTEREINTRAG>Appelius, #r#Wilhelm#/r# #r#Carl#/r# Lorenz (1728-1796), Lanschaftssyndikus sowie Hofadvokat und Kammerrat in Eisenach</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="90">
      <ID>35332</ID>
      <REGISTEREINTRAG>Araujo de Azevédo (Aranjo), Antonio de, (seit 1815/16:) Conde da Barca (1754-1817), portugiesischer Diplomat, Politiker, Schriftsteller und Übersetzer, 1790-1802 Gesandter in den Niederlanden und 1802-1804 in Rußland
</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="91">
      <ID>35333</ID>
      <REGISTEREINTRAG>Archenholz (Archenholtz), Johann #r#Wilhelm#/r# von (1741/43-1812), preußischer Offizier, Historiker und Publizist, bis 1763 im preußischen Militärdienst, bis 1780 ausgedehnte Reisen durch Deutschland und Europa, danach in Dresden, ab 1786 in Hamburg</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="92">
      <ID>35336</ID>
      <REGISTEREINTRAG>Arens (Ahrens), Johann August (1757-1806), Maler und Architekt des Klassizismus in Hamburg, Reisen durch Frankreich, England und Italien, Berater beim Wiederaufbau des Weimarer Schlosses, 1791 Ernennung zum herzoglichen Baurat in Weimar</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="93">
      <ID>35338</ID>
      <REGISTEREINTRAG>Aretino, Pietro (1492-1556), italienischer Schriftsteller</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="94">
      <ID>35339</ID>
      <REGISTEREINTRAG>Arien, Bernhard Christoph d¿ (1754-1793), Advokat in Hamburg, Dichter</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="95">
      <ID>35341</ID>
      <REGISTEREINTRAG>Ariosto (Ariost), Lodovico (1474-1533), italienischer Dichter und Diplomat aus der Familie d'Este, Hofbeamter des Herzogs Alfonso I. d'Este in Ferrara
</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="96">
      <ID>35375</ID>
      <REGISTEREINTRAG>Auch, Jacob (1765-1842), Mechaniker, 1787 Uhrmacher in Vaihingen an der Enz, seit 1798 Hofuhrmacher in Weimar</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="97">
      <ID>35381</ID>
      <REGISTEREINTRAG>Augereau, Pierre François Charles (1757-1816), seit 1808 Duc de Castiglione, französischer General, seit 1804 Marschall</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="98">
      <ID>35384</ID>
      <REGISTEREINTRAG>Augustinus (Aurelius Augustinus) (354–430), Kirchenlehrer, Bischof von Hippo im heutigen östlichen Algerien</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="99">
      <ID>35385</ID>
      <REGISTEREINTRAG>Augustus (#k#eigentl.#/k# Gaius Octavius), Gaius Iulius Caesar Octavianus (63 v. Chr.-14 n. Chr.), seit 31 v. Chr. erster römischer Kaiser</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="100">
      <ID>35387</ID>
      <REGISTEREINTRAG>Aulhorn, Johann Adam (1728-1808), Hoftanzmeister, Schauspieler und Sänger in Weimar </REGISTEREINTRAG>
   </ITEM>
   <ITEM num="101">
      <ID>35388</ID>
      <REGISTEREINTRAG>Ausfeld, Georg Gottlob (1740-1782), Theologe, von 1768 bis 1775 Pfarrer in Großwelsbach, 1775 Diakon in Langensalza, 1782 Professor in Jena</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="102">
      <ID>35393</ID>
      <REGISTEREINTRAG>Autenrieth, Johann Heinrich Ferdinand (seit 1818:) von (1772-1835), Mediziner, 1797 Professor in Tübingen, 1822 Kanzler der Universität</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="103">
      <ID>35399</ID>
      <REGISTEREINTRAG>Ayrer, Johann Heinrich (1732-1817), Universitätstallmeister in Göttingen</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="104">
      <ID>35400</ID>
      <REGISTEREINTRAG>Azara y Perera, José Nicolás de (1730-1804), spanischer Diplomat, Kunstsammler und Schriftsteller, 1765-1798 in Rom, seit 1801 Marquese de Nibbiano und Botschafter in Paris</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="105">
      <ID>35401</ID>
      <REGISTEREINTRAG>Baader, Joseph (seit 1813: von) (1763–1835), Ingenieur, von 1787 bis 1795 in England, 1796 Mitglied der Akademie der Wissenschaften in München</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="106">
      <ID>35402</ID>
      <REGISTEREINTRAG>Babo, Joseph Marius Franz (seit 1791:) von (1756-1822), Theaterschriftsteller, seit 1774 Sekretär des Mannheimer Theaters, von 1789 bis 1799 Studiendirektor der Münchner Militärakademie, von 1792 bis 1810 Leiter des Hoftheaters in München</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="107">
      <ID>35406</ID>
      <REGISTEREINTRAG>Bach, Johann Sebastian (1685-1750)</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="108">
      <ID>35407</ID>
      <REGISTEREINTRAG>Bach, Johann Sebastian (1748-1778), Maler, Schüler Adam Friedrich Oesers in Leipzig, Enkel des Komponisten Johann Sebastian Bach</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="109">
      <ID>35408</ID>
      <REGISTEREINTRAG>Bach, Carl #r#Philipp Emanuel#/r# (1714-1788), Komponist, seit 1767 Musikdirektor in Hamburg, Sohn von Johann Sebastian Bach</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="110">
      <ID>35414</ID>
      <REGISTEREINTRAG>Baden, Friedrich I. Markgraf von (um 1249-1268), regierender Markgraf von Verona und Baden sowie Herzog von Österreich und Steiermark </REGISTEREINTRAG>
   </ITEM>
   <ITEM num="111">
      <ID>35415</ID>
      <REGISTEREINTRAG>Baden, Carl Friedrich von (1728-1811), seit 1746 regierender Markgraf, seit 1803 Kurfürst, seit 1806 Großherzog</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="112">
      <ID>35417</ID>
      <REGISTEREINTRAG>Baden, #r#Ludwig#/r#  Wilhelm August Prinz von (1763-1830), seit 1818 als Ludwig I. Großherzog, Sohn von Carl Friedrich Markgraf und Caroline Louise Markgräfin von Baden</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="113">
      <ID>35425</ID>
      <REGISTEREINTRAG>Bager, Johann Daniel (1734-1815), Maler und Radierer in Frankfurt a. M.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="114">
      <ID>35427</ID>
      <REGISTEREINTRAG>Baggesen, Jens Immanuel (1764–1826), deutsch-dänischer Schriftsteller, Reisender, von 1811 bis 1814 Professor für dänische Sprache und Literatur in Kiel, dänischer Dichter</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="115">
      <ID>35431</ID>
      <REGISTEREINTRAG>Bahrdt (Bardt), Carl Friedrich (1741-1792), Theologe und Schriftsteller, seit 1771 Professor in Gießen, 1773/1774 Herausgeber der FGA, seit 1779 in Halle</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="116">
      <ID>35437</ID>
      <REGISTEREINTRAG>Baldauf, Carl Gottfried (1751–1811), Bergingenieur, seit 1787 Berggeschworener in Schneeberg, Sachverständiger in Ilmenau</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="117">
      <ID>35438</ID>
      <REGISTEREINTRAG>Balde, Jacob (1604–1668), Dichter, Jesuit, 1635 Professor der Rhetorik  in Ingolstadt, von 1638 bis 1640 bayerischer Hofprediger in München</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="118">
      <ID>35439</ID>
      <REGISTEREINTRAG>Baldinger, Ernst Gottfried (1738-1804), Mediziner, Botaniker, 1768 Professor in Jena und 1773 in Göttingen, 1783 Dirigent der Medizinalangelegenheiten des Landes und Leibarzt in Kassel, 1786 Professor in Marburg</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="119">
      <ID>35448</ID>
      <REGISTEREINTRAG>Bandinelli, Baccio (Bartolommeo Brandini) (1488/93-1560), italienischer Bildhauer und Maler</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="120">
      <ID>35451</ID>
      <REGISTEREINTRAG>Banks, John (um 1650-1696), englischer Dramatiker</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="121">
      <ID>35452</ID>
      <REGISTEREINTRAG>Banks, Joseph (1781: Sir) (1743-1820), englischer Botaniker und Forschungsreisender, Begleiter von James Cook</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="122">
      <ID>35454</ID>
      <REGISTEREINTRAG>Bansa, Johann Matthias (1758-1802), Bankier (Bansa &amp; Reuß) und Weinhändler in Frankfurt am Main</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="123">
      <ID>35471</ID>
      <REGISTEREINTRAG>Barocci, Federico (#k#eigentl.#/k# Federico Fiori) (1526–1612), italienischer Maler und Kupferstecher</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="124">
      <ID>35481</ID>
      <REGISTEREINTRAG>Barth, Joseph (1745–1818), kaiserlicher Leibarzt am Wiener Hof</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="125">
      <ID>35489</ID>
      <REGISTEREINTRAG>Bartholomäi, Johann Christian (1708-1778), Bibliothekar in Weimar</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="126">
      <ID>35494</ID>
      <REGISTEREINTRAG>Barton, Charles (1760-1813), englischer Schriftsteller</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="127">
      <ID>35497</ID>
      <REGISTEREINTRAG>Basch, Siegmund (1700-1771), Theologe, Oberkirchenrat, Oberhofprediger, Superintendent in Weimar, Aufseher des Gymnasiums, Herders Vorgänger</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="128">
      <ID>35498</ID>
      <REGISTEREINTRAG>Basedow, Johann Bernhard (1724-1790), Theologe, Pädagoge, Schulreformer, 1774 Begründer des Philanthropinums in Dessau, pädagogischer Schriftsteller</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="129">
      <ID>35508</ID>
      <REGISTEREINTRAG>Batty (Bätty, Baty, Bäty), George (1732/33-1821), englischer Ökonom, seit 1779 sachsen-weimarischer Landkommissar und Inspektor der herzoglichen Kammergüter in Weimar, 1805 Privatier</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="130">
      <ID>35509</ID>
      <REGISTEREINTRAG>Bauder, Johann Friedrich (1713-1791), Fabrikant, Händler und Fossiliensammler in Altdorf, 1770-1784 Bürgermeister</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="131">
      <ID>35526</ID>
      <REGISTEREINTRAG>Baumbach, Johann Georg (1751–1817), Tischler in Meiningen, um 1794 Hoftischler</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="132">
      <ID>35530</ID>
      <REGISTEREINTRAG>Baumgärtner, Albrecht (Albert) Heinrich (1743–1809), Historiker, Schriftsteller, Beamter, seit 1783
Kastenamtmann in Baiersdorf bei Erlangen, seit 1786 preußischer Kriegsrat und Resident im Fränkischen Kreis in Baiersdorf bei Erlangen, von 1797 bis 1803 Kammeramtmann in Frauenaurach, zuletzt in Erlangen lebend</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="133">
      <ID>35533</ID>
      <REGISTEREINTRAG>Baumgarten, Sigmund Jacob (1706-1757), Professor der Theologie in Halle</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="134">
      <ID>35537</ID>
      <REGISTEREINTRAG>Bause, Henriette Charlotte, geb. Brünner (1742-1818), seit 1766 Frau des Kupferstechers Johann Friedrich Bause in Leipzig</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="135">
      <ID>35538</ID>