<?xml version = "1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE PROJEKT_TAGEBUCH [
<!ELEMENT PROJEKT_TAGEBUCH (ITEM)*>
<!ELEMENT ITEM (ID, REGISTEREINTRAG?)>
<!ATTLIST ITEM num CDATA #REQUIRED>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT REGISTEREINTRAG (#PCDATA)>
]>
<PROJEKT_TAGEBUCH>
   <ITEM num="1">
      <ID>2475</ID>
      <REGISTEREINTRAG>Goethe, (G., G**, Göthe), Johann Wolfgang (Wolf), seit 1782 von (1749–1832); Moeller (Möller), Johann Phillipp (Jean Philippe, Giovanni Filippo), Goethes Pseudonym während der Italienreise</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="2">
      <ID>3924</ID>
      <REGISTEREINTRAG>Leochares (390/385–320/315 vChr), griechischer Bildhauer</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="3">
      <ID>4330</ID>
      <REGISTEREINTRAG>May, Georg Oswald (1738–1816), Porträtmaler</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="4">
      <ID>11085</ID>
      <REGISTEREINTRAG>Sachsen-Weimar-Eisenach, Ernst August I. (A., Aug.) Herzog von (1688–1748), seit 1707 Mitregent Ernst Wilhelms, seit 1728 Alleinregent</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="5">
      <ID>11093</ID>
      <REGISTEREINTRAG>Rußland, Natalia Alexejewna Großfürstin von, geb. Wilhelmine Prinzessin von Hessen-Darmstadt (1755–1776), Frau des Großfürsten Paul Petrowitsch von Rußland (1754–1801), Schwester der Herzogin Louise von Sachsen-Weimar-Eisenach</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="6">
      <ID>22363</ID>
      <REGISTEREINTRAG>Velde, Carl Franz van der (1779--1824), Jurist, Schriftsteller, 1814 Stadtgerichtsassessor in Breslau, 1818 Stadtrichter in Zobten, 1823 Rückkehr nach Breslau und dort kurz vor seinem Tod Justizkommissar </REGISTEREINTRAG>
   </ITEM>
   <ITEM num="7">
      <ID>35189</ID>
      <REGISTEREINTRAG>Abramson, Abraham (1754–1811), Medailleur in Berlin</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="8">
      <ID>35205</ID>
      <REGISTEREINTRAG>Ackermann, Rudolph (1764-1834), deutscher Verleger und Kunsthändler in London</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="9">
      <ID>35218</ID>
      <REGISTEREINTRAG>Aischylos (Eschyl), athenischer Tragödiendichter (um 525 – um 455 v. Chr.)</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="10">
      <ID>35248</ID>
      <REGISTEREINTRAG>Albrecht, Johann Carl (1734–1800), Mathematiker und Naturforscher, 1765 Legationsrat, Lehrer und 1781 Reisebegleiter des Prinzen Constantin von Sachsen-Weimar-Eisenach, 1782 als Hofrat pensioniert</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="11">
      <ID>35260</ID>
      <REGISTEREINTRAG>Alopaeus, David Maximowitsch (seit 1808) Graf von (1769--1831), russischer Diplomat, u._a. 1803--1808 Gesandter in Stockholm, 1811 in Stuttgart, seit 1813 in Berlin</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="12">
      <ID>35295</ID>
      <REGISTEREINTRAG>(Andre), Johann (1741–1799), Seidenfabrikant und Musikalienverleger, Musiker und Komponist, seit 1776 Kapellmeister am Komödienhaus in Berlin</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="13">
      <ID>35310</ID>
      <REGISTEREINTRAG>Anhalt-Bernburg, Friedrich Albrecht Fürst von (1735–1796), Regent seit 1765</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="14">
      <ID>35324</ID>
      <REGISTEREINTRAG>Appelius (Appel), Wilhelm Carl Lorenz (1728–1796), burggräflich-kirchbergischer Rat, Landschaftssyndikus und Hofadvokat, 1780 Landkammerrat in Eisenach</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="15">
      <ID>35333</ID>
      <REGISTEREINTRAG>Archenholtz (Archenholz), Johann Wilhelm von (1743–1812), preußischer Offizier, dann Publizist und Reiseschriftsteller</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="16">
      <ID>35341</ID>
      <REGISTEREINTRAG>Ariosto (Ariost), Ludovico (1474–1533), italienischer Dichter</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="17">
      <ID>35384</ID>
      <REGISTEREINTRAG>Augustinus, Aurelius (353–430), Kirchenvater, Heiliger</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="18">
      <ID>35385</ID>
      <REGISTEREINTRAG>Augustus, Caius Iulius Caesar Octavianus (63 v. Chr. – 14 n. Chr.), seit 27 v. Chr. römischer Kaiser</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="19">
      <ID>35387</ID>
      <REGISTEREINTRAG>Aulhorn, Johann Adam (1729/1730–1808), Schauspieler und Sänger, seit 1766 Hoftanzmeister in Weimar</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="20">
      <ID>35498</ID>
      <REGISTEREINTRAG>Basedow (Basedov), Johann #s+Bernhard#s- (1724–1790), Pädagoge, Schriftsteller, begründete 1774 das Dessauer Philanthropinum</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="21">
      <ID>35508</ID>
      <REGISTEREINTRAG>Batty, George (1732/1733–1821), in Weimar, seit 1779 Landkommissar und Inspektor der Kammergüter,
zuständig für Pflanzenanbau und Wiesenbewässerung</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="22">
      <ID>35533</ID>
      <REGISTEREINTRAG>Baumgarten, Siegmund Jacob (1706–1757), Theologieprofessor, Schriftsteller, Übersetzer</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="23">
      <ID>35545</ID>
      <REGISTEREINTRAG>Beaumarchais, Pierre Augustin Caron de (1732–1799), französischer Schriftsteller und Politiker</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="24">
      <ID>35553</ID>
      <REGISTEREINTRAG>Bechtolsheim, Johann #s+Ludwig#s- Freiherr von Mauchenheim, genannt von (1739–1806), gothaischer Oberamtshauptmann, seit 1776 Vizekanzler, 1781 Kanzler und Oberkonsistorialpräsident in Eisenach</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="25">
      <ID>35576</ID>
      <REGISTEREINTRAG>Beethoven (Bethofen), Ludwig van (1770--1827), Komponist, seit 1792 in Wien</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="26">
      <ID>35621</ID>
      <REGISTEREINTRAG>Bentheim, Johann Georg von (1739–1801), Offizier, 1779 als Hauptmann in Weimar, 1783 Stadtkommandant von Jena, 1784 Major</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="27">
      <ID>35671</ID>
      <REGISTEREINTRAG>Berlichingen, Gottfried, Ritter von (1480–1562)</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="28">
      <ID>35705</ID>
      <REGISTEREINTRAG>Bernstorff, Charitas Emilie Gräfin von, geb. von Buchwald (1733–1820), seit 1772 Witwe des Ministers Johann Hartwig Ernst Graf von B., seit 1779 in Weimar</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="29">
      <ID>35744</ID>
      <REGISTEREINTRAG>Beyer, Albert, etwa seit 1775 Steinschneider in Jena</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="30">
      <ID>35841</ID>
      <REGISTEREINTRAG>Bode, #s+Johann Joachim#s- Christoph (1730–1793), Buchhändler und Verleger, Schriftsteller, hessen-darmstädtischer Geheimer Rat, Freimaurer, seit 1778 Sekretär der Gräfin von Bernstorff in Weimar, beteiligt an Aufführungen des Weimarer Liebhabertheaters</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="31">
      <ID>35903</ID>
      <REGISTEREINTRAG>Boie, Heinrich Christian (1744–1806), Jurist, Schriftsteller</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="32">
      <ID>35940</ID>
      <REGISTEREINTRAG>Borromeo (Boromäus, Borromäi), Carlo Graf (1538–1584), 1560 Erzbischof von Mailand, 1610 heiliggesprochen</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="33">
      <ID>35970</ID>
      <REGISTEREINTRAG>Bouilly, Jean Nicolas (1763--1842), französischer Dramatiker</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="34">
      <ID>35991</ID>
      <REGISTEREINTRAG>Branconi, Maria Antonia Marquise von, geb. von Elsener, seit 1776 Witwe von Francesco di Pessina B., auf Gut Langenstein bei Halberstadt, Mätresse von Carl Wilhelm Ferdinand von Braunschweig-Lüneburg-Wolfenbüttel (1735–1806; Regent seit 1780)</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="35">
      <ID>36018</ID>
      <REGISTEREINTRAG>Braunschweig-Lüneburg-Wolfenbüttel, Ferdinand Herzog von (1721–1792), bis 1766 preußischer Generalfeldmarschall, Freimaurer, Großmeister, Onkel von Anna Amalia von Sachsen-Weimar-Eisenach</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="36">
      <ID>36059</ID>
      <REGISTEREINTRAG>Bretzner, Christoph Friedrich (1746–1807), Kaufmann und Dramatiker in Leipzig</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="37">
      <ID>36125</ID>
      <REGISTEREINTRAG>Brutus, Marcus Junius (85–42 v. Chr.), 53 Quaestor, 44 Praetor, an der Ermordung Caesars beteiligt</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="38">
      <ID>36136</ID>
      <REGISTEREINTRAG>Buchholz, Wilhelm Heinrich #s+Sebastian#s- (1734–1798), Mediziner, Pharmazeut, Chemiker und Botaniker, seit 1772 Hofapotheker in Weimar, seit 1777 Hofmedikus und Amtsphysikus, 1782 Bergrat</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="39">
      <ID>36169</ID>
      <REGISTEREINTRAG>Büttner, Christian Wilhelm (1716–1801), Natur- und Sprachforscher, 1758–1782 Professor in Göttingen, 1783 Privatgelehrter und Hofrat in Jena</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="40">
      <ID>36176</ID>
      <REGISTEREINTRAG>Buffon, Georges Louis Leclerc Comte de (1707–1788), französischer Naturforscher</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="41">
      <ID>36218</ID>
      <REGISTEREINTRAG>Byron (Beyron), George Gordon (seit 1798) Lord (1788--1824), englischer Schriftsteller, 1809--1811 und seit 1816 Reisen auf dem europäischen Kontinent</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="42">
      <ID>36222</ID>
      <REGISTEREINTRAG>Caesar, Gajus Julius (100–44 v. Chr.)</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="43">
      <ID>36230</ID>
      <REGISTEREINTRAG>Calderón de la Barca (Barka), Pedro (1600--1681), spanischer Dramatiker</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="44">
      <ID>36285</ID>
      <REGISTEREINTRAG>Carus, Carl Gustav (1789--1869), Mediziner, Philosoph, Maler, 1811 Arzt in Leipzig, 1812 auch Privatdozent, 1814 Professor an der Chirurgisch-Medizinischen Akademie und Direktor der Entbindungsanstalt in Dresden, 1827 Leibarzt der königl. Familie, Hof- und Medizinalrat</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="45">
      <ID>36300</ID>
      <REGISTEREINTRAG>Castrop, Jean Antoine Joseph de (um 1731–1785), Offizer, seit 1756 in Weimar für den Stadtpflaster- und Wegebau tätig, Artilleriehauptmann, 1764 Ingenieurhauptmann, 1776–1778 kommissarischer Leiter der Wegebaudirektion</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="46">
      <ID>36305</ID>
   </ITEM>
   <ITEM num="47">
      <ID>36363</ID>
      <REGISTEREINTRAG>Marlborough, John Churchill, Duke of (1650–1722), englischer Oberbefehlshaber im Spanischen Erbfolgekrieg 1701–1711</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="48">
      <ID>36374</ID>
      <REGISTEREINTRAG>Cimarosa, Domenico (1749--1801), italienischer Opernkomponist</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="49">
      <ID>36399</ID>
      <REGISTEREINTRAG>Clodius, Christian August (1737–1784), Schriftsteller, 1764 Professor der Philosophie und (seit 1782) der Dichtkunst in Leipzig</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="50">
      <ID>36421</ID>
      <REGISTEREINTRAG>Colman, George d. Ä. (1732--1794), englischer Dramatiker</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="51">
      <ID>36431</ID>
      <REGISTEREINTRAG>Compter, Johann David Gottlob (1795--1838), Kanzlist in Jena, 1820 Bibliotheksschreiber, 1835 Bibliothekssekretär</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="52">
      <ID>36485</ID>
      <REGISTEREINTRAG>Cramer, Carl Friedrich (1752–1807), Philologe, Schriftsteller, Mitglied des Göttinger Hainbundes</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="53">
      <ID>36499</ID>
      <REGISTEREINTRAG>Crébillon (Crebillon), Prosper Jolyot, Sieur de Crais-Billon, genannt (1674-1762), französischer klassizistischer Dramatiker</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="54">
      <ID>36514</ID>
      <REGISTEREINTRAG>Cumberland, Richard (1732–1811), englischer Schriftsteller</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="55">
      <ID>36640</ID>
      <REGISTEREINTRAG>Diderot, Denis (1713–1784)</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="56">
      <ID>36645</ID>
      <REGISTEREINTRAG>Diede zum Fürstenstein, Wilhelm Christoph von (1732–1807), Diplomat in dänischen Diensten</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="57">
      <ID>36711</ID>
      <REGISTEREINTRAG>Dörr, Johann Wilhelm Heinrich (1755–1819), Amtsadvokat, Landschaftskassierer in Eisenach, 1780 Obersteuerverwalter</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="58">
      <ID>36750</ID>
      <REGISTEREINTRAG>Dryden, John (1631–1700), englischer Dichter</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="59">
      <ID>36758</ID>
      <REGISTEREINTRAG>Dürer, Albrecht (1471–1528), Maler, Kupferstecher und Zeichner</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="60">
      <ID>36759</ID>
      <REGISTEREINTRAG>Düring, Johann Christian von (1751–1823), hannoverscher Oberjägermeister in Dannenberg an der Jeetzel</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="61">
      <ID>36808</ID>
      <REGISTEREINTRAG>Dy(c)k, Johann Gottfried (1750–1813), Buchhändler, Übersetzer</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="62">
      <ID>36823</ID>
      <REGISTEREINTRAG>Eckardt (Eckard), Johann Christian Ludwig (1732–1800), Jurist, 1772 sachsen-weimarischer Hof- und Regierungsrat, 1777 Mitglied der Bergwerkskommission und Geheimer Archivar, 1783 Geheimer Hofrat und
Professor der Rechte in Jena</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="63">
      <ID>36836</ID>
      <REGISTEREINTRAG>Edelsheim, Wilhelm von (1737–1799), seit 1774 badischer
Geheimer Rat in Karlsruhe, Minister</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="64">
      <ID>36866</ID>
      <REGISTEREINTRAG>Eichhorn, Johann Gottfried (1752–1827), protestantischer Theologe, Orientalist, Literarhistoriker, seit 1775 Professor der orientalischen Sprachen in Jena, seit 1788 in Göttingen </REGISTEREINTRAG>
   </ITEM>
   <ITEM num="65">
      <ID>36925</ID>
      <REGISTEREINTRAG>Erdmannsdorff (Erdmannsdorf), Friedrich Wilhelm Freiherr von (1736–1800), Bau- und Gartenarchitekt, anhalt-dessauischer Hofbaumeister</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="66">
      <ID>36976</ID>
      <REGISTEREINTRAG>Everdingen, Allaert van (1621–1675), holländischer Landschaftsmaler und Radierer</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="67">
      <ID>37000</ID>
      <REGISTEREINTRAG>Facius, Friedrich Wilhelm (1764--1843), Medailleur, Graveur, Stein- und Stempelschneider, seit 1788 in Weimar, 1823 (?) Lehrer an der Zeichenschule, 1829 Hofmedailleur, 1840 Professor, Vater von Angelica Bellonata Facius</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="68">
      <ID>37157</ID>
      <REGISTEREINTRAG>Francia, Francesco (Francesko di Francia), eigentlich Francesco Raibolini, genannt Il Francia (um 1450–1518), italienischer Maler</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="69">
      <ID>37165</ID>
      <REGISTEREINTRAG>Franckenberg (Frankenberg), Sylvius Friedrich Ludwig Freiherr von (1728/1729–1815), 1765 Geheimer Rat und Mitglied des Geheimen Ratskollegiums in Gotha</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="70">
      <ID>37224</ID>
      <REGISTEREINTRAG>Frisch, Johann Christoph (1738–1815), Historienmaler, Radierer, Kunstsammler</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="71">
      <ID>37228</ID>
      <REGISTEREINTRAG>Fritsch (Fr.), Jacob Friedrich Freiherr von (1731–1814), Jurist, sachsen-weimarischer Staatsbeamter, 1756 Referendar, 1762 Legationsrat, 1766 Geheimer Rat, 1772 Wirklicher Geheimer Rat, seit 1762 Mitglied,
seit 1772 Präsident des Geheimen Consilium, Meister vom Stuhl der Loge »Amalia «:</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="72">
      <ID>37313</ID>
      <REGISTEREINTRAG>Garrick, David (1716–1779), englischer Schauspieler und Bühnenautor</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="73">
      <ID>37353</ID>
      <REGISTEREINTRAG>Gellert, Christian Fürchtegott (1715–1769), Schriftsteller, Universitätslehrer in Leipzig</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="74">
      <ID>37375</ID>
      <REGISTEREINTRAG>Gentzsch (R., Rentsch), Johann Ernst (geb. um 1717 – um 1780), Hofgärtner in Belvedere, 1777 pensioniert</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="75">
      <ID>37390</ID>
      <REGISTEREINTRAG>Gerhardt (Gerhard), Carl Abraham (1738–1821), Mineraloge</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="76">
      <ID>37456</ID>
      <REGISTEREINTRAG>Glaser, Johann Elias (gest. 1781), Kaufmann in Stützerbach</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="77">
      <ID>37470</ID>
      <REGISTEREINTRAG>Gluck, Christoph Willibald Ritter von (1714–1787), Komponist</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="78">
      <ID>37538</ID>
      <REGISTEREINTRAG>Goldoni, Carlo (1707–1793), italienischer Dramatiker</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="79">
      <ID>37561</ID>
      <REGISTEREINTRAG>Gotter, Friedrich Wilhelm (1746–1797), Schriftsteller und Beamter, 1766 Archivar in Gotha, 1767 sachsen-gothaischer Legationssekretär in Wetzlar, seit 1771 Geheimer Sekretär in Gotha, in Wetzlar Bekanntschaft mit Goethe</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="80">
      <ID>37565</ID>
      <REGISTEREINTRAG>Gottsched, Johann Christoph (1700–1766), Schriftsteller, Universitätslehrer in Leipzig</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="81">
      <ID>37578</ID>
      <REGISTEREINTRAG>Gozzi, Carlo Conte (1720–1806), italienischer Dramatiker</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="82">
      <ID>37588</ID>
      <REGISTEREINTRAG>Graff (Graf), Anton (1736–1813), Porträtmaler</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="83">
      <ID>37628</ID>
      <REGISTEREINTRAG>Griesbach, Johann Jacob (1745–1812), protestantischer Theologe, Schriftsteller, 1775 Professor in Jena, seit 1781 sachsen-weimarischer Kirchenrat, 1784 Geheimer Kirchenrat</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="84">
      <ID>37631</ID>
      <REGISTEREINTRAG>Grimm (Gr.), #s+Freidrich#s- Melchior, seit 1776 Baron von (1723–1807), Schriftsteller, Diplomat, seit 1748 in Paris, seit 1776 sachsen-gothaischer Gesandter in Versailles</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="85">
      <ID>37651</ID>
      <REGISTEREINTRAG>Großmann, Gustav #s+Friedrich#s- Wilhelm (1746–1796), Jurist, Schauspieler und Bühnenautor</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="86">
      <ID>37760</ID>
      <REGISTEREINTRAG>Häfeli, Johann Caspar (1754–1811), Schweizer Theologe und Schriftsteller, seit 1773 Pfarrer in Elisau bei Zürich, Freund Lavaters</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="87">
      <ID>37768</ID>
      <REGISTEREINTRAG>Händel, Georg Friedrich (1685–1759)</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="88">
      <ID>37817</ID>
      <REGISTEREINTRAG>Hamann (Haman), Johann Georg (1730–1788), Schriftsteller</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="89">
      <ID>37964</ID>
      <REGISTEREINTRAG>Hellfeld, Johann August von (1717–1782), 1748 Professor der Rechte in Jena, 1763 Geheimer Regierungsrat</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="90">
      <ID>38022</ID>
      <REGISTEREINTRAG>Herda zu Brandenburg, #s+Carl#s- Christian von (um 1726–1802), 1776 Kammerpräsident, 1781 Geheimer Rat und Steuer- und Kassendirektor in Eisenach</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="91">
      <ID>38024</ID>
      <REGISTEREINTRAG>Herder, Johann #s+Gottfried#s- (1744–1803), Theologe, Schriftsteller, 1776 Generalsuperintendent und Oberkonsistorialrat in Weimar</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="92">
      <ID>38075</ID>
      <REGISTEREINTRAG>Hessen-Darmstadt (D., Darmst, Darmst.), Ludwig Erbprinz von (1753–1830), seit 1790 Landgraf Ludwig X. von</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="93">
      <ID>38080</ID>
      <REGISTEREINTRAG>Hessen-Kassel, Friedrich II. Landgraf von (1720–1785), Regent seit 1760</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="94">
      <ID>38186</ID>
      <REGISTEREINTRAG>Hogarth, William (1697–1764), englischer Maler, Kupferstecher und Radierer</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="95">
      <ID>38198</ID>
      <REGISTEREINTRAG>Holbein, Hans d. J. (1497–1543), Maler und Zeichner, Sohn von Hans H. d. Ä.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="96">
      <ID>38211</ID>
      <REGISTEREINTRAG>Holzschuher (Holzschuer), Johann Carl Siegmund von (1749–1824), Jurist, Assessor in Nürnberg, Freund Karl Ludwig von Knebels </REGISTEREINTRAG>
   </ITEM>
   <ITEM num="97">
      <ID>38213</ID>
      <REGISTEREINTRAG>Homer (wohl 8. Jh. v.Chr)</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="98">
      <ID>38283</ID>
      <REGISTEREINTRAG>Hufeland (Hufl.), Johann Friedrich (1730–1787), seit 1765 Hofrat und Leibmedikus, 1782 Geheimer Hofrat in Weimar</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="99">
      <ID>38333</ID>
      <REGISTEREINTRAG>im Baumgarten, Peter (Pet.) (1765/1766–1799), Findelkind aus Meiringen in der Schweiz, 1775–1777 Famulant des Philanthropins in Marschlin, 1777 Pflegesohn Goethes, 1779 Försterlehrling in Ilmenau, nach 1780 als Kupferstecher tätig</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="100">
      <ID>38374</ID>
      <REGISTEREINTRAG>Jagemann, Christian Joseph (1735–1804), lebte als katholischer Theologe und Mönch zwischen 1755 und 1772 in Italien, seit 1775 Protestant, Schriftsteller und Übersetzer, 1775 Bibliothekar in der Privatbibliothek Anna Amalias</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="101">
      <ID>38466</ID>
      <REGISTEREINTRAG>Kaestner (Kästner, Kestn., Kestner), Johann Friedrich (1747–1812), Hofmeister der Kinder von Charlotte und Gottlob Ernst Josias von Stein, seit 1780 Pageninformator, seit 1788 Professor am Gymnasium in Weimar</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="102">
      <ID>38470</ID>
      <REGISTEREINTRAG>Kalb, Johann August Alexander von (1747–1814), 1775 Kammerherr, 1776–1782 Präsident des Kammerkollegiums in Weimar, Mitglied der Bergwerkskommission, Sohn von Carl Alexander von K</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="103">
      <ID>38507</ID>
      <REGISTEREINTRAG>Karsch (Karschin), Anna Louisa, geb. Dürbach, gesch. Hirsekorn (1722–1791), Schriftstellerin, seit 1762 in Berlin:</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="104">
      <ID>38515</ID>
      <REGISTEREINTRAG>Kaufmann (Kaufm., Kaufman, Kfm.), Johann Christoph (1753–1795), Schweizer Apotheker, Arzt und Wundertäter, versuchte 1776 mit Unterstützung des Fürsten von Anhalt- Dessau Einfluß auf das Dessauer Philanthropin zu gewinnen</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="105">
      <ID>38523</ID>
      <REGISTEREINTRAG>Kayser, Philipp Christoph (1755–1823), Pianist und Komponist, Freund Goethes in Frankfurt am Main, seit 1775 Musiklehrer in Zürich, Freimaurer</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="106">
      <ID>38633</ID>
      <REGISTEREINTRAG>Clemens XIV., eigentlich Lorenzo Ganganelli (1705–1774), ab 1769 Papst</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="107">
      <ID>38643</ID>
      <REGISTEREINTRAG>Kleopatra (Cleopatra) (66–30 v.Chr.), 51 und ab 48 v.Chr. Königin von Ägypten</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="108">
      <ID>38649</ID>
      <REGISTEREINTRAG>Klinckowström (Klingovstr.), Leonhard Freiherr von (1741/1742–1821), 1765 sachsenweimarischer Kammerjunker, seit 1775 Reisemarschall, 1781 Hofmarschall, 1788 von Weimar weggegangen, 1789  entlassen</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="109">
      <ID>38656</ID>
      <REGISTEREINTRAG>Klinger, Friedrich Maximilian (1752–1831), seit 1780 nobilitiert, Schriftsteller, 1776 als Theaterdichter und Sekretär der Seilerschen Truppe tätig, 1778–1779 Offizier in österreichischen, seit 1780 in russischen Diensten</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="110">
      <ID>38693</ID>
      <REGISTEREINTRAG>Koch, Franziska Romana, geb. Gieranek (1748–1796), Schauspielerin und Sängerin, verh. mit Friedrich Carl K.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="111">
      <ID>38702</ID>
      <REGISTEREINTRAG>Koch, Johann Christoph (1732–1808), Jurist, 1758 Professor der Rechte in Gießen, 1771 Vizekanzler, 1773  Geheimer Rat</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="112">
      <ID>38773</ID>
      <REGISTEREINTRAG>Johann Friedrich (1738–1811), Herr auf Rohrbach, sachsen-weimarischer Beamter, 1772 Hofrat, 1776 Geheimer Regierungsrat, 1783 Landschaftskassendirektor in Jena, 1789 Kanzler, Vater von Johanne Louise Bernhardine K. v. K.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="113">
      <ID>38802</ID>
      <REGISTEREINTRAG>Krafft (Kr.), Johann Friedrich, eigentlich Weiße? (gest. 1785), um 1762 Mitarbeiter Friedrich Nicolais in Berlin, später in Gera, 1779–1785 für Goethe in Ilmenau tätig</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="114">
      <ID>38807</ID>
      <REGISTEREINTRAG>Kranz, Johann #s+Friedrich#s- (1752–1810), Violinist und Komponist, Mitglied der Weimarer Hofkapelle, 1778 Kammermusiker, 1787 Zweiter Konzertmeister</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="115">
      <ID>38812</ID>
      <REGISTEREINTRAG>Kraus (C., Kr., Krause), Georg Melchior (1737–1806), Zeichner, Maler und Kupferstecher, 1761–1766 in Paris, seit 1775 Zeichenmeister, seit 1776 Direktor der Fürstlichen freien Zeichenschule in Weimar, 1780 Rat</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="116">
      <ID>38860</ID>
      <REGISTEREINTRAG>Kühn, August Christian (um 1743–1807), Stadtphysikus in Eisenach</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="117">
      <ID>38983</ID>
      <REGISTEREINTRAG>Lanthieri, Aloysia (1750–1821), Gräfin aus Graz</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="118">
      <ID>38990</ID>
      <REGISTEREINTRAG>La Roche, Georg Michael Anton von, eigentlich Frank von Lichtenfels (1720–1788), Schriftsteller, seit 1771 kurtrierischer Geheimer Staatsrat und Kanzler, 1780 entlassen</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="119">
      <ID>39033</ID>
      <REGISTEREINTRAG>Lavater (Lav.), Johann Caspar (1741–1801), Schweizer Theologe und Prediger, Schriftsteller</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="120">
      <ID>39056</ID>
      <REGISTEREINTRAG>Leffler (Loffler), Johann Wilhelm (gest. 1797), Amtsakzessist, 1770 Amtsaktuar, 1776 Gerichtsschreiber, 1784 Steuereinnehmerin Ilmenau</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="121">
      <ID>39070</ID>
      <REGISTEREINTRAG>Leisewitz (Leisewiz), Johann Anton (1752–1806), Jurist, Historiker, Schriftsteller und Übersetzer, seit 1775 Advokat in Braunschweig, 1778 Landschaftssekretär</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="122">
      <ID>39085</ID>
      <REGISTEREINTRAG>Lener, Johann Nepomuk (18. Jh.), Wirt des Post- und Gasthauses auf dem Brenner</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="123">
      <ID>39093</ID>
      <REGISTEREINTRAG>Lenz (L.), #s+Jakob#s- Michael Reinhold (1751–1792), Schriftsteller</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="124">
      <ID>39108</ID>
      <REGISTEREINTRAG>Leopold II. (Erzherzog Leopold) (1747–1792), ab 1765 Großherzog von Toskana, seit 1790 römisch-deutscher Kaiser, Bruder und Nachfolger Josephs II.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="125">
      <ID>39121</ID>
      <REGISTEREINTRAG>Lessing, Gotthold Ephraim (1729–1781)</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="126">
      <ID>39215</ID>
      <REGISTEREINTRAG>Loder, Justus Christian (1753–1832), Anatom, 1778 Professor in Jena, 1781 sachsen-weimarischer Leibarzt, 1782 Hofrat</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="127">
      <ID>39275</ID>
      <REGISTEREINTRAG>Loyola, Ignaz, eigentlich Inigo Lopez de Recalde (1491–1556), spanischer Soldat, dann Einsiedler; gründete 1534 den Jesuitenorden, dessen General er 1541 wurde; 1623 kanonisiert</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="128">
      <ID>39336</ID>
      <REGISTEREINTRAG>Macpherson, James (1736–1796), schottischer Schriftsteller</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="129">
      <ID>39384</ID>
      <REGISTEREINTRAG>Mantegna, Andrea (1431–1506), italienischer Maler</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="130">
      <ID>39387</ID>
      <REGISTEREINTRAG>Mara, Gertrud Elisabeth, geb. Schmeling (1749–1833), Sängerin, 1766 in Leipzig, 1771–1780 in Berlin engagiert </REGISTEREINTRAG>
   </ITEM>
   <ITEM num="131">
      <ID>39412</ID>
      <REGISTEREINTRAG>Marius, Gaius (156–86 vChr), römischer Konsul und Heerführer</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="132">
      <ID>39413</ID>
      <REGISTEREINTRAG>Antoninus, Marcus Annius Verus Arrius, genannt Marcus Aurelius (121–180), seit 161 römischer Kaiser</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="133">
      <ID>39418</ID>
      <REGISTEREINTRAG>Marmontel, Jean-François (1723–1799), französischer Schriftsteller</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="134">
      <ID>39426</ID>
      <REGISTEREINTRAG>Marschall-Burgholzhausen, August Dietrich, Reichsgraf von (1750–1824), Herr auf Oßmannstedt und Burgholzhausen, Erbmarschall in Thüringen, Hofgerichtsassessor inBraunschweig</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="135">
      <ID>39552</ID>
      <REGISTEREINTRAG>Mendelssohn, Moses (1729–1786), Berliner Kaufmann, Philosoph</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="136">
      <ID>39559</ID>
      <REGISTEREINTRAG>Mengs, Anton #s+Raphael#s- (1728–1779), Maler und Kunstschriftsteller</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="137">
      <ID>39571</ID>
      <REGISTEREINTRAG>Merck (M.), Johann Heinrich (1741–1791), Schriftsteller, Unternehmer und Beamter, 1768 Kriegszahlmeister, 1774 Kriegsrat in Darmstadt</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="138">
      <ID>39597</ID>
      <REGISTEREINTRAG>Metastasio, #s+Pietro#s- Antonio Dominico #s+Bonaventura#s-, eigentlich  #s+Pietro#s- Antonio Dominico #s+Bonaventura#s- Trapassi (1698–1782), italienischer Dramatiker</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="139">
      <ID>39682</ID>
      <REGISTEREINTRAG>Milkau, Christian Wilhelm Gottlob von (1739–1802), Offizier, Kammerherr in Weimar und Jena </REGISTEREINTRAG>
   </ITEM>
   <ITEM num="140">
      <ID>39741</ID>
      <REGISTEREINTRAG>Monsigny, Pierre Alexandre (1729–1817), französischer Komponist:</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="141">
      <ID>39798</ID>
      <REGISTEREINTRAG>Mozart, Johannes Chrysostomus Wolfgang Gottlieb, genannt Wolfgang Amadeus (1756–1791)</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="142">
      <ID>39810</ID>
      <REGISTEREINTRAG>Müller, Christian Friedrich (1730/1731–1792), Amtmann in Berka und Kapellendorf</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="143">
      <ID>39907</ID>
      <REGISTEREINTRAG>Nagel, Charlotte (geb. um 1755), in Offenbach</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="144">