<?xml version = "1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE NDB_INDIV [
<!ELEMENT NDB_INDIV (ITEM)*>
<!ELEMENT ITEM (ID, SEXUS?, LITERATUR?, GND?)>
<!ATTLIST ITEM num CDATA #REQUIRED>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT SEXUS (#PCDATA)>
<!ELEMENT LITERATUR (#PCDATA)>
<!ELEMENT GND (#PCDATA)>
]>
<NDB_INDIV>
   <ITEM num="1">
      <ID>71</ID>
      <SEXUS>m</SEXUS>
      <GND>132216736</GND>
   </ITEM>
   <ITEM num="2">
      <ID>249</ID>
      <SEXUS>m</SEXUS>
      <GND>121065847</GND>
   </ITEM>
   <ITEM num="3">
      <ID>391</ID>
      <SEXUS>m</SEXUS>
      <LITERATUR>Wikipedia</LITERATUR>
      <GND>116267968</GND>
   </ITEM>
   <ITEM num="4">
      <ID>492</ID>
      <SEXUS>m</SEXUS>
      <GND>119181304</GND>
   </ITEM>
   <ITEM num="5">
      <ID>762</ID>
      <SEXUS>m</SEXUS>
   </ITEM>
   <ITEM num="6">
      <ID>875</ID>
      <SEXUS>m</SEXUS>
      <GND>120898306</GND>
   </ITEM>
   <ITEM num="7">
      <ID>927</ID>
      <SEXUS>m</SEXUS>
   </ITEM>
   <ITEM num="8">
      <ID>1492</ID>
      <SEXUS>m</SEXUS>
      <GND>123097924</GND>
   </ITEM>
   <ITEM num="9">
      <ID>1502</ID>
      <SEXUS>m</SEXUS>
      <GND>118878794</GND>
   </ITEM>
   <ITEM num="10">
      <ID>1537</ID>
      <SEXUS>m</SEXUS>
      <GND>104142146</GND>
   </ITEM>
   <ITEM num="11">
      <ID>1861</ID>
   </ITEM>
   <ITEM num="12">
      <ID>1874</ID>
      <SEXUS>m</SEXUS>
      <GND>116584459</GND>
   </ITEM>
   <ITEM num="13">
      <ID>1906</ID>
      <SEXUS>w</SEXUS>
      <GND>116372443</GND>
   </ITEM>
   <ITEM num="14">
      <ID>2004</ID>
      <SEXUS>m</SEXUS>
      <GND>116586761</GND>
   </ITEM>
   <ITEM num="15">
      <ID>2008</ID>
      <SEXUS>m</SEXUS>
      <GND>1070261696</GND>
   </ITEM>
   <ITEM num="16">
      <ID>2019</ID>
      <SEXUS>m</SEXUS>
      <GND>116602821</GND>
   </ITEM>
   <ITEM num="17">
      <ID>2054</ID>
      <SEXUS>m</SEXUS>
      <GND>116642718</GND>
   </ITEM>
   <ITEM num="18">
      <ID>2162</ID>
      <SEXUS>m</SEXUS>
      <GND>118703277</GND>
   </ITEM>
   <ITEM num="19">
      <ID>2189</ID>
      <SEXUS>m</SEXUS>
      <GND>118861700</GND>
   </ITEM>
   <ITEM num="20">
      <ID>2318</ID>
      <SEXUS>m</SEXUS>
      <GND>119059800</GND>
   </ITEM>
   <ITEM num="21">
      <ID>2390</ID>
      <SEXUS>m</SEXUS>
      <GND>11661451X</GND>
   </ITEM>
   <ITEM num="22">
      <ID>2475</ID>
      <SEXUS>m</SEXUS>
      <GND>118540238</GND>
   </ITEM>
   <ITEM num="23">
      <ID>2645</ID>
      <SEXUS>m</SEXUS>
      <GND>117572101</GND>
   </ITEM>
   <ITEM num="24">
      <ID>2682</ID>
      <SEXUS>m</SEXUS>
      <GND>102556504</GND>
   </ITEM>
   <ITEM num="25">
      <ID>2696</ID>
      <SEXUS>m</SEXUS>
      <GND>122996399</GND>
   </ITEM>
   <ITEM num="26">
      <ID>2832</ID>
      <SEXUS>m</SEXUS>
      <GND>118547216</GND>
   </ITEM>
   <ITEM num="27">
      <ID>2931</ID>
      <SEXUS>m</SEXUS>
      <GND>115876898</GND>
   </ITEM>
   <ITEM num="28">
      <ID>2932</ID>
      <SEXUS>m</SEXUS>
      <GND>115876871</GND>
   </ITEM>
   <ITEM num="29">
      <ID>3082</ID>
      <SEXUS>m</SEXUS>
      <GND>116935383</GND>
   </ITEM>
   <ITEM num="30">
      <ID>3128</ID>
      <SEXUS>m</SEXUS>
      <GND>120161559</GND>
   </ITEM>
   <ITEM num="31">
      <ID>3190</ID>
      <SEXUS>m</SEXUS>
      <GND>133391329</GND>
   </ITEM>
   <ITEM num="32">
      <ID>3198</ID>
      <SEXUS>m</SEXUS>
      <GND>118707264</GND>
   </ITEM>
   <ITEM num="33">
      <ID>3251</ID>
      <SEXUS>w</SEXUS>
      <GND>117051543</GND>
   </ITEM>
   <ITEM num="34">
      <ID>3267</ID>
      <SEXUS>m</SEXUS>
      <GND>123210836</GND>
   </ITEM>
   <ITEM num="35">
      <ID>3291</ID>
      <SEXUS>m</SEXUS>
      <GND>136250734</GND>
   </ITEM>
   <ITEM num="36">
      <ID>3362</ID>
      <SEXUS>m</SEXUS>
      <GND>124164285</GND>
   </ITEM>
   <ITEM num="37">
      <ID>3420</ID>
      <SEXUS>m</SEXUS>
      <GND>118560751</GND>
   </ITEM>
   <ITEM num="38">
      <ID>3562</ID>
      <SEXUS>m</SEXUS>
      <GND>119080958</GND>
   </ITEM>
   <ITEM num="39">
      <ID>3595</ID>
      <SEXUS>m</SEXUS>
      <GND>124779107</GND>
   </ITEM>
   <ITEM num="40">
      <ID>3703</ID>
      <SEXUS>m</SEXUS>
      <GND>11872469X</GND>
   </ITEM>
   <ITEM num="41">
      <ID>3704</ID>
      <SEXUS>m</SEXUS>
      <GND>120158388</GND>
   </ITEM>
   <ITEM num="42">
      <ID>3917</ID>
      <SEXUS>m</SEXUS>
      <GND>115830642</GND>
   </ITEM>
   <ITEM num="43">
      <ID>3924</ID>
      <SEXUS>m</SEXUS>
      <GND>118779532</GND>
   </ITEM>
   <ITEM num="44">
      <ID>3933</ID>
      <SEXUS>m</SEXUS>
      <GND>116943963</GND>
   </ITEM>
   <ITEM num="45">
      <ID>3966</ID>
      <SEXUS>m</SEXUS>
      <GND>124014372</GND>
   </ITEM>
   <ITEM num="46">
      <ID>4042</ID>
      <SEXUS>m</SEXUS>
      <GND>136755321</GND>
   </ITEM>
   <ITEM num="47">
      <ID>4105</ID>
      <SEXUS>m</SEXUS>
      <GND>101984759X</GND>
   </ITEM>
   <ITEM num="48">
      <ID>4275</ID>
      <SEXUS>m</SEXUS>
      <GND>116801301</GND>
   </ITEM>
   <ITEM num="49">
      <ID>4330</ID>
      <SEXUS>m</SEXUS>
      <GND>124351239</GND>
   </ITEM>
   <ITEM num="50">
      <ID>4333</ID>
      <SEXUS>m</SEXUS>
      <GND>115389385</GND>
   </ITEM>
   <ITEM num="51">
      <ID>4526</ID>
      <SEXUS>m</SEXUS>
      <GND>117080586</GND>
   </ITEM>
   <ITEM num="52">
      <ID>4648</ID>
      <SEXUS>m</SEXUS>
      <GND>118974408</GND>
   </ITEM>
   <ITEM num="53">
      <ID>4859</ID>
      <SEXUS>m</SEXUS>
      <GND>117107263</GND>
   </ITEM>
   <ITEM num="54">
      <ID>5233</ID>
      <SEXUS>m</SEXUS>
      <GND>118741837</GND>
   </ITEM>
   <ITEM num="55">
      <ID>5279</ID>
      <SEXUS>m</SEXUS>
      <GND>129060674</GND>
   </ITEM>
   <ITEM num="56">
      <ID>5327</ID>
      <SEXUS>m</SEXUS>
      <GND>118598031</GND>
   </ITEM>
   <ITEM num="57">
      <ID>5503</ID>
      <SEXUS>m</SEXUS>
      <GND>11874528X</GND>
   </ITEM>
   <ITEM num="58">
      <ID>5596</ID>
      <SEXUS>m</SEXUS>
      <GND>10424366X</GND>
   </ITEM>
   <ITEM num="59">
      <ID>5848</ID>
      <SEXUS>m</SEXUS>
      <GND>117185191</GND>
   </ITEM>
   <ITEM num="60">
      <ID>6002</ID>
      <SEXUS>m</SEXUS>
      <GND>143606689</GND>
   </ITEM>
   <ITEM num="61">
      <ID>6005</ID>
      <SEXUS>m</SEXUS>
      <GND>133855376</GND>
   </ITEM>
   <ITEM num="62">
      <ID>6080</ID>
      <SEXUS>m</SEXUS>
      <GND>119289474</GND>
   </ITEM>
   <ITEM num="63">
      <ID>6107</ID>
      <SEXUS>m</SEXUS>
      <GND>131382659</GND>
   </ITEM>
   <ITEM num="64">
      <ID>6219</ID>
      <SEXUS>w</SEXUS>
      <GND>11904238X</GND>
   </ITEM>
   <ITEM num="65">
      <ID>6223</ID>
      <SEXUS>m</SEXUS>
      <GND>117458945</GND>
   </ITEM>
   <ITEM num="66">
      <ID>6371</ID>
      <SEXUS>m</SEXUS>
      <GND>119124718</GND>
   </ITEM>
   <ITEM num="67">
      <ID>6528</ID>
      <SEXUS>m</SEXUS>
      <GND>118755285</GND>
   </ITEM>
   <ITEM num="68">
      <ID>6573</ID>
      <SEXUS>m</SEXUS>
      <GND>11954797X</GND>
   </ITEM>
   <ITEM num="69">
      <ID>6670</ID>
      <SEXUS>m</SEXUS>
      <GND>133430367</GND>
   </ITEM>
   <ITEM num="70">
      <ID>6782</ID>
      <SEXUS>w</SEXUS>
      <GND>103405063X</GND>
   </ITEM>
   <ITEM num="71">
      <ID>6784</ID>
      <SEXUS>m</SEXUS>
      <GND>118758349</GND>
   </ITEM>
   <ITEM num="72">
      <ID>6881</ID>
      <SEXUS>m</SEXUS>
      <GND>132656159</GND>
   </ITEM>
   <ITEM num="73">
      <ID>7038</ID>
      <SEXUS>m</SEXUS>
      <GND>119019264</GND>
   </ITEM>
   <ITEM num="74">
      <ID>7090</ID>
      <SEXUS>m</SEXUS>
      <GND>117076317</GND>
   </ITEM>
   <ITEM num="75">
      <ID>7178</ID>
      <SEXUS>m</SEXUS>
      <GND>1089398131</GND>
   </ITEM>
   <ITEM num="76">
      <ID>7370</ID>
      <SEXUS>m</SEXUS>
      <GND>118920588</GND>
   </ITEM>
   <ITEM num="77">
      <ID>7409</ID>
      <SEXUS>m</SEXUS>
      <GND>118807803</GND>
   </ITEM>
   <ITEM num="78">
      <ID>7502</ID>
      <SEXUS>m</SEXUS>
      <GND>119273950</GND>
   </ITEM>
   <ITEM num="79">
      <ID>7663</ID>
      <SEXUS>m</SEXUS>
      <GND>104303875</GND>
   </ITEM>
   <ITEM num="80">
      <ID>10858</ID>
      <SEXUS>m</SEXUS>
   </ITEM>
   <ITEM num="81">
      <ID>11032</ID>
      <SEXUS>m</SEXUS>
      <GND>104134368X</GND>
   </ITEM>
   <ITEM num="82">
      <ID>11036</ID>
      <SEXUS>m</SEXUS>
   </ITEM>
   <ITEM num="83">
      <ID>11043</ID>
      <SEXUS>w</SEXUS>
   </ITEM>
   <ITEM num="84">
      <ID>11085</ID>
      <SEXUS>m</SEXUS>
      <GND>104175931</GND>
   </ITEM>
   <ITEM num="85">
      <ID>11087</ID>
      <SEXUS>m</SEXUS>
      <GND>10044220X</GND>
   </ITEM>
   <ITEM num="86">
      <ID>11089</ID>
      <SEXUS>w</SEXUS>
      <GND>118560271</GND>
   </ITEM>
   <ITEM num="87">
      <ID>11093</ID>
      <SEXUS>w</SEXUS>
      <GND>119147793</GND>
   </ITEM>
   <ITEM num="88">
      <ID>11094</ID>
      <SEXUS>m</SEXUS>
      <GND>118560042</GND>
   </ITEM>
   <ITEM num="89">
      <ID>11096</ID>
      <SEXUS>w</SEXUS>
      <GND>1012618994</GND>
   </ITEM>
   <ITEM num="90">
      <ID>11103</ID>
      <SEXUS>w</SEXUS>
      <GND>124716288</GND>
   </ITEM>
   <ITEM num="91">
      <ID>11104</ID>
      <SEXUS>m</SEXUS>
      <GND>10210901X</GND>
   </ITEM>
   <ITEM num="92">
      <ID>11125</ID>
      <SEXUS>w</SEXUS>
      <GND>118685015</GND>
   </ITEM>
   <ITEM num="93">
      <ID>11127</ID>
      <SEXUS>m</SEXUS>
      <GND>117593338</GND>
   </ITEM>
   <ITEM num="94">
      <ID>11136</ID>
      <SEXUS>m</SEXUS>
      <GND>118793063</GND>
   </ITEM>
   <ITEM num="95">
      <ID>11142</ID>
      <SEXUS>w</SEXUS>
      <GND>119093049</GND>
   </ITEM>
   <ITEM num="96">
      <ID>11143</ID>
      <SEXUS>m</SEXUS>
      <GND>100031900</GND>
   </ITEM>
   <ITEM num="97">
      <ID>11144</ID>
      <SEXUS>m</SEXUS>
      <GND>100863892</GND>
   </ITEM>
   <ITEM num="98">
      <ID>11146</ID>
      <SEXUS>w</SEXUS>
      <GND>102360847</GND>
   </ITEM>
   <ITEM num="99">
      <ID>11156</ID>
      <SEXUS>m</SEXUS>
      <GND>102239452</GND>
   </ITEM>
   <ITEM num="100">
      <ID>11159</ID>
      <SEXUS>w</SEXUS>
      <GND>119131641</GND>
   </ITEM>
   <ITEM num="101">
      <ID>11160</ID>
      <SEXUS>m</SEXUS>
      <GND>136425755</GND>
   </ITEM>
   <ITEM num="102">
      <ID>11166</ID>
      <SEXUS>w</SEXUS>
   </ITEM>
   <ITEM num="103">
      <ID>11175</ID>
      <SEXUS>m</SEXUS>
      <GND>102282099</GND>
   </ITEM>
   <ITEM num="104">
      <ID>19242</ID>
      <SEXUS>w</SEXUS>
   </ITEM>
   <ITEM num="105">
      <ID>19271</ID>
      <SEXUS>m</SEXUS>
      <LITERATUR>Deutscher Biographischer Index, K. G. Saur, 1986, Band 1</LITERATUR>
      <GND>116361190</GND>
   </ITEM>
   <ITEM num="106">
      <ID>19426</ID>
      <SEXUS>m</SEXUS>
      <GND>116165391</GND>
   </ITEM>
   <ITEM num="107">
      <ID>19443</ID>
      <SEXUS>w</SEXUS>
      <GND>116195819</GND>
   </ITEM>
   <ITEM num="108">
      <ID>19477</ID>
      <SEXUS>m</SEXUS>
      <LITERATUR>GND, Wikipedia</LITERATUR>
      <GND>117608866</GND>
   </ITEM>
   <ITEM num="109">
      <ID>19579</ID>
      <SEXUS>m</SEXUS>
      <GND>116817275</GND>
   </ITEM>
   <ITEM num="110">
      <ID>19723</ID>
      <SEXUS>m</SEXUS>
      <GND>116055448</GND>
   </ITEM>
   <ITEM num="111">
      <ID>19764</ID>
      <SEXUS>m</SEXUS>
      <LITERATUR>ADB</LITERATUR>
      <GND>10114606X</GND>
   </ITEM>
   <ITEM num="112">
      <ID>19782</ID>
      <SEXUS>m</SEXUS>
      <GND>116178728</GND>
   </ITEM>
   <ITEM num="113">
      <ID>19814</ID>
      <SEXUS>w</SEXUS>
      <GND>116251883</GND>
   </ITEM>
   <ITEM num="114">
      <ID>19833</ID>
      <SEXUS>m</SEXUS>
      <GND>100116450</GND>
   </ITEM>
   <ITEM num="115">
      <ID>20338</ID>
      <SEXUS>m</SEXUS>
      <GND>116514957</GND>
   </ITEM>
   <ITEM num="116">
      <ID>20370</ID>
      <SEXUS>m</SEXUS>
      <GND>116604816</GND>
   </ITEM>
   <ITEM num="117">
      <ID>20510</ID>
      <SEXUS>m</SEXUS>
      <GND>118706640</GND>
   </ITEM>
   <ITEM num="118">
      <ID>20869</ID>
      <SEXUS>m</SEXUS>
      <GND>118778277</GND>
   </ITEM>
   <ITEM num="119">
      <ID>21044</ID>
      <SEXUS>m</SEXUS>
      <GND>118573527</GND>
   </ITEM>
   <ITEM num="120">
      <ID>21114</ID>
      <SEXUS>m</SEXUS>
      <GND>116723149</GND>
   </ITEM>
   <ITEM num="121">
      <ID>21140</ID>
      <SEXUS>m</SEXUS>
      <GND>104140720</GND>
   </ITEM>
   <ITEM num="122">
      <ID>21199</ID>
      <SEXUS>m</SEXUS>
      <GND>118783688</GND>
   </ITEM>
   <ITEM num="123">
      <ID>21283</ID>
      <SEXUS>w</SEXUS>
      <GND>118585754</GND>
   </ITEM>
   <ITEM num="124">
      <ID>21378</ID>
      <SEXUS>m</SEXUS>
      <GND>117067598</GND>
   </ITEM>
   <ITEM num="125">
      <ID>21394</ID>
      <SEXUS>m</SEXUS>
      <GND>117105821</GND>
   </ITEM>
   <ITEM num="126">
      <ID>21412</ID>
      <SEXUS>m</SEXUS>
      <GND>117148970</GND>
   </ITEM>
   <ITEM num="127">
      <ID>21554</ID>
      <SEXUS>m</SEXUS>
      <GND>118597442</GND>
   </ITEM>
   <ITEM num="128">
      <ID>21791</ID>
      <SEXUS>m</SEXUS>
      <GND>118794558</GND>
   </ITEM>
   <ITEM num="129">
      <ID>21911</ID>
      <SEXUS>m</SEXUS>
      <GND>10026705X</GND>
   </ITEM>
   <ITEM num="130">
      <ID>21952</ID>
      <SEXUS>m</SEXUS>
      <GND>116849436</GND>
   </ITEM>
   <ITEM num="131">
      <ID>21994</ID>
      <SEXUS>w</SEXUS>
      <GND>118761889</GND>
   </ITEM>
   <ITEM num="132">
      <ID>22069</ID>
      <SEXUS>m</SEXUS>
      <GND>116857374</GND>
   </ITEM>
   <ITEM num="133">
      <ID>22147</ID>
      <SEXUS>m</SEXUS>
      <GND>117479047</GND>
   </ITEM>
   <ITEM num="134">
      <ID>22164</ID>
      <SEXUS>m</SEXUS>
      <GND>117480118</GND>
   </ITEM>
   <ITEM num="135">
      <ID>22235</ID>
      <SEXUS>m</SEXUS>
      <LITERATUR>WBIS</LITERATUR>
      <GND>117289337</GND>
   </ITEM>
   <ITEM num="136">
      <ID>22322</ID>
      <SEXUS>m</SEXUS>
      <GND>117381608</GND>
   </ITEM>
   <ITEM num="137">
      <ID>22329</ID>
      <SEXUS>m</SEXUS>
      <GND>104309040</GND>
   </ITEM>
   <ITEM num="138">
      <ID>22363</ID>
      <SEXUS>m</SEXUS>
      <GND>117368857</GND>
   </ITEM>
   <ITEM num="139">
      <ID>22390</ID>
      <SEXUS>m</SEXUS>
      <GND>117488240</GND>
   </ITEM>
   <ITEM num="140">
      <ID>22403</ID>
      <SEXUS>m</SEXUS>
      <GND>104057440</GND>
   </ITEM>
   <ITEM num="141">
      <ID>22472</ID>
      <SEXUS>m</SEXUS>
   </ITEM>
   <ITEM num="142">
      <ID>22473</ID>
      <SEXUS>m</SEXUS>
   </ITEM>
   <ITEM num="143">
      <ID>22544</ID>
      <SEXUS>m</SEXUS>
      <GND>117371092</GND>
   </ITEM>
   <ITEM num="144">
      <ID>22592</ID>
      <SEXUS>m</SEXUS>
      <GND>117442003</GND>
   </ITEM>
   <ITEM num="145">
      <ID>22607</ID>
      <SEXUS>m</SEXUS>
      <GND>11889028X</GND>
   </ITEM>
   <ITEM num="146">
      <ID>22681</ID>
      <SEXUS>m</SEXUS>
      <GND>11877297X</GND>
   </ITEM>
   <ITEM num="147">
      <ID>22781</ID>
      <SEXUS>w</SEXUS>
      <GND>11853419X</GND>
   </ITEM>
   <ITEM num="148">
      <ID>22800</ID>
      <SEXUS>m</SEXUS>
      <GND>118509675</GND>
   </ITEM>
   <ITEM num="149">
      <ID>22898</ID>
      <SEXUS>w</SEXUS>
      <GND>116176024</GND>
   </ITEM>
   <ITEM num="150">
      <ID>35180</ID>
      <SEXUS>m</SEXUS>
      <GND>124330568</GND>
   </ITEM>
   <ITEM num="151">
      <ID>35181</ID>
      <SEXUS>m</SEXUS>
      <GND>118500104</GND>
   </ITEM>
   <ITEM num="152">
      <ID>35182</ID>
      <SEXUS>w</SEXUS>
   </ITEM>
   <ITEM num="153">
      <ID>35183</ID>
      <SEXUS>m</SEXUS>
      <GND>1031974342</GND>
   </ITEM>
   <ITEM num="154">
      <ID>35184</ID>
      <SEXUS>m</SEXUS>
      <GND>116001666</GND>
   </ITEM>
   <ITEM num="155">
      <ID>35185</ID>
      <SEXUS>m</SEXUS>
      <GND>11914543X</GND>
   </ITEM>
   <ITEM num="156">
      <ID>35186</ID>
      <SEXUS>m</SEXUS>
      <GND>116001755</GND>
   </ITEM>
   <ITEM num="157">
      <ID>35187</ID>
      <SEXUS>m</SEXUS>
      <GND>116003472</GND>
   </ITEM>
   <ITEM num="158">
      <ID>35188</ID>
      <SEXUS>m</SEXUS>
   </ITEM>
   <ITEM num="159">
      <ID>35189</ID>
      <SEXUS>m</SEXUS>
      <GND>116004037</GND>
   </ITEM>
   <ITEM num="160">
      <ID>35190</ID>
      <SEXUS>m</SEXUS>
      <GND>118500279</GND>
   </ITEM>
   <ITEM num="161">
      <ID>35191</ID>
      <SEXUS>m</SEXUS>
      <GND>127029443</GND>
   </ITEM>
   <ITEM num="162">
      <ID>35192</ID>
      <SEXUS>m</SEXUS>
      <GND>116004827</GND>
   </ITEM>
   <ITEM num="163">
      <ID>35193</ID>
   </ITEM>
   <ITEM num="164">
      <ID>35194</ID>
      <SEXUS>m</SEXUS>
      <GND>116004894</GND>
   </ITEM>
   <ITEM num="165">
      <ID>35195</ID>
      <SEXUS>m</SEXUS>
      <GND>1052412556</GND>
   </ITEM>
   <ITEM num="166">
      <ID>35196</ID>
      <SEXUS>m</SEXUS>
      <GND>128995211</GND>
   </ITEM>
   <ITEM num="167">
      <ID>35197</ID>
      <SEXUS>m</SEXUS>
      <GND>118643525</GND>
   </ITEM>
   <ITEM num="168">
      <ID>35198</ID>
      <SEXUS>m</SEXUS>
      <GND>1183418922</GND>
   </ITEM>
   <ITEM num="169">
      <ID>35199</ID>
      <SEXUS>m</SEXUS>
   </ITEM>
   <ITEM num="170">
      <ID>35200</ID>
      <SEXUS>m</SEXUS>
      <GND>116005904</GND>
   </ITEM>
   <ITEM num="171">
      <ID>35201</ID>
      <SEXUS>m</SEXUS>
   </ITEM>
   <ITEM num="172">
      <ID>35202</ID>
      <SEXUS>w</SEXUS>
      <GND>11600570X</GND>
   </ITEM>
   <ITEM num="173">
      <ID>35203</ID>
   </ITEM>
   <ITEM num="174">
      <ID>35204</ID>
      <SEXUS>w</SEXUS>
   </ITEM>
   <ITEM num="175">
      <ID>35205</ID>
      <SEXUS>m</SEXUS>
      <GND>116006048</GND>
   </ITEM>
   <ITEM num="176">
      <ID>35206</ID>
      <SEXUS>w</SEXUS>
      <GND>1029366314</GND>
   </ITEM>
   <ITEM num="177">
      <ID>35207</ID>
      <SEXUS>m</SEXUS>
      <GND>1166179265</GND>
   </ITEM>
   <ITEM num="178">
      <ID>35208</ID>
      <SEXUS>m</SEXUS>
      <GND>119082624</GND>
   </ITEM>
   <ITEM num="179">
      <ID>35209</ID>
      <SEXUS>m</SEXUS>
      <GND>172522889</GND>
   </ITEM>
   <ITEM num="180">
      <ID>35210</ID>
      <SEXUS>m</SEXUS>
      <GND>118500597</GND>
   </ITEM>
   <ITEM num="181">
      <ID>35211</ID>
      <SEXUS>m</SEXUS>
      <GND>118500619</GND>
   </ITEM>
   <ITEM num="182">
      <ID>35212</ID>
      <SEXUS>m</SEXUS>
      <GND>118500651</GND>
   </ITEM>
   <ITEM num="183">
      <ID>35213</ID>
      <SEXUS>m</SEXUS>
      <GND>119089645</GND>
   </ITEM>
   <ITEM num="184">
      <ID>35214</ID>
      <SEXUS>m</SEXUS>
   </ITEM>
   <ITEM num="185">
      <ID>35215</ID>
      <SEXUS>m</SEXUS>
      <GND>118643959</GND>
   </ITEM>
   <ITEM num="186">
      <ID>35216</ID>
      <SEXUS>m</SEXUS>
      <GND>118501062</GND>
   </ITEM>
   <ITEM num="187">
      <ID>35217</ID>
      <SEXUS>w</SEXUS>
   </ITEM>
   <ITEM num="188">
      <ID>35218</ID>
      <SEXUS>m</SEXUS>
      <GND>118500856</GND>
   </ITEM>
   <ITEM num="189">
      <ID>35219</ID>
      <SEXUS>m</SEXUS>
      <GND>118647180</GND>
   </ITEM>
   <ITEM num="190">
      <ID>35220</ID>
      <SEXUS>m</SEXUS>
      <GND>100005063</GND>
   </ITEM>
   <ITEM num="191">
      <ID>35221</ID>
      <SEXUS>m</SEXUS>
      <GND>103121188</GND>
   </ITEM>
   <ITEM num="192">
      <ID>35222</ID>
      <SEXUS>m</SEXUS>
   </ITEM>
   <ITEM num="193">
      <ID>35223</ID>
   </ITEM>
   <ITEM num="194">
      <ID>35224</ID>
      <SEXUS>m</SEXUS>
   </ITEM>
   <ITEM num="195">
      <ID>35225</ID>
      <SEXUS>m</SEXUS>
      <GND>1082312134</GND>
   </ITEM>
   <ITEM num="196">
      <ID>35226</ID>
      <SEXUS>m</SEXUS>
      <GND>116275235</GND>
   </ITEM>
   <ITEM num="197">
      <ID>35227</ID>
      <SEXUS>m</SEXUS>
      <GND>119344483</GND>
   </ITEM>
   <ITEM num="198">
      <ID>35228</ID>
   </ITEM>
   <ITEM num="199">
      <ID>35229</ID>
      <SEXUS>m</SEXUS>
      <GND>1069005509</GND>
   </ITEM>
   <ITEM num="200">
      <ID>35230</ID>
      <SEXUS>m</SEXUS>
      <GND>1033720844</GND>
   </ITEM>
   <ITEM num="201">
      <ID>35231</ID>
   </ITEM>
   <ITEM num="202">
      <ID>35232</ID>
      <SEXUS>w</SEXUS>
   </ITEM>
   <ITEM num="203">
      <ID>35233</ID>
      <SEXUS>m</SEXUS>
      <GND>11864761X</GND>
   </ITEM>
   <ITEM num="204">
      <ID>35234</ID>
      <SEXUS>m</SEXUS>
      <GND>117726419</GND>
   </ITEM>
   <ITEM num="205">
      <ID>35235</ID>
      <SEXUS>w</SEXUS>
   </ITEM>
   <ITEM num="206">
      <ID>35236</ID>
      <SEXUS>m</SEXUS>
      <GND>116009942</GND>
   </ITEM>
   <ITEM num="207">
      <ID>35237</ID>
      <SEXUS>m</SEXUS>
      <GND>138961433</GND>
   </ITEM>
   <ITEM num="208">
      <ID>35238</ID>
      <SEXUS>m</SEXUS>
      <GND>11850147X</GND>
   </ITEM>
   <ITEM num="209">
      <ID>35239</ID>
      <SEXUS>w</SEXUS>
      <GND>1156816025</GND>
   </ITEM>
   <ITEM num="210">
      <ID>35240</ID>
      <SEXUS>m</SEXUS>
      <GND>117760692</GND>
   </ITEM>
   <ITEM num="211">
      <ID>35241</ID>
      <SEXUS>m</SEXUS>
      <GND>119396432</GND>
   </ITEM>
   <ITEM num="212">
      <ID>35242</ID>
      <SEXUS>m</SEXUS>
   </ITEM>
   <ITEM num="213">
      <ID>35243</ID>
      <SEXUS>m</SEXUS>
      <GND>118501607</GND>
   </ITEM>
   <ITEM num="214">
      <ID>35244</ID>
      <SEXUS>m</SEXUS>
   </ITEM>
   <ITEM num="215">
      <ID>35245</ID>
      <SEXUS>m</SEXUS>
      <GND>103749864X</GND>
   </ITEM>
   <ITEM num="216">
      <ID>35246</ID>
      <SEXUS>m</SEXUS>
      <GND>118647822</GND>
   </ITEM>
   <ITEM num="217">
      <ID>35247</ID>
      <SEXUS>m</SEXUS>
      <GND>116283823</GND>
   </ITEM>
   <ITEM num="218">
      <ID>35248</ID>
      <SEXUS>m</SEXUS>
      <GND>1018068899</GND>
   </ITEM>
   <ITEM num="219">
      <ID>35249</ID>
      <SEXUS>m</SEXUS>
   </ITEM>
   <ITEM num="220">
      <ID>35250</ID>
      <SEXUS>m</SEXUS>
      <GND>118898825</GND>
   </ITEM>
   <ITEM num="221">
      <ID>35251</ID>
      <SEXUS>m</SEXUS>
      <GND>11850178X</GND>
   </ITEM>
   <ITEM num="222">
      <ID>35252</ID>
      <SEXUS>m</SEXUS>
      <GND>118647989</GND>
   </ITEM>
   <ITEM num="223">
      <ID>35253</ID>
      <SEXUS>m</SEXUS>
      <GND>118501925</GND>
   </ITEM>
   <ITEM num="224">
      <ID>35254</ID>
      <SEXUS>m</SEXUS>
      <GND>118501933</GND>
   </ITEM>
   <ITEM num="225">
      <ID>35255</ID>
      <SEXUS>m</SEXUS>
   </ITEM>
   <ITEM num="226">
      <ID>35256</ID>
      <SEXUS>m</SEXUS>
      <GND>11864808X</GND>
   </ITEM>
   <ITEM num="227">
      <ID>35257</ID>
      <SEXUS>m</SEXUS>
      <GND>119086395</GND>
   </ITEM>
   <ITEM num="228">
      <ID>35258</ID>
      <SEXUS>m</SEXUS>
      <GND>135862132</GND>
   </ITEM>
   <ITEM num="229">
      <ID>35259</ID>
      <SEXUS>m</SEXUS>
      <GND>100009360</GND>
   </ITEM>
   <ITEM num="230">
      <ID>35260</ID>
      <SEXUS>m</SEXUS>
      <GND>116288329</GND>
   </ITEM>
   <ITEM num="231">
      <ID>35261</ID>
      <SEXUS>m</SEXUS>
      <GND>10185725X</GND>
   </ITEM>
   <ITEM num="232">
      <ID>35262</ID>
      <SEXUS>m</SEXUS>
      <GND>116292938</GND>
   </ITEM>
   <ITEM num="233">
      <ID>35263</ID>
      <SEXUS>m</SEXUS>
      <GND>118502220</GND>
   </ITEM>
   <ITEM num="234">
      <ID>35264</ID>
      <SEXUS>m</SEXUS>
      <GND>116293748</GND>
   </ITEM>
   <ITEM num="235">
      <ID>35265</ID>
      <SEXUS>m</SEXUS>
      <GND>100010385</GND>
   </ITEM>
   <ITEM num="236">
      <ID>35266</ID>
      <SEXUS>m</SEXUS>
      <GND>116294477</GND>
   </ITEM>
   <ITEM num="237">
      <ID>35267</ID>
      <SEXUS>w</SEXUS>
      <GND>129459658</GND>
   </ITEM>
   <ITEM num="238">
      <ID>35268</ID>
      <SEXUS>w</SEXUS>
   </ITEM>
   <ITEM num="239">
      <ID>35269</ID>
      <SEXUS>m</SEXUS>
   </ITEM>
   <ITEM num="240">
      <ID>35270</ID>
      <SEXUS>m</SEXUS>
      <GND>137747470</GND>
   </ITEM>
   <ITEM num="241">
      <ID>35271</ID>
      <SEXUS>m</SEXUS>
      <GND>135708869</GND>
   </ITEM>
   <ITEM num="242">
      <ID>35272</ID>
      <SEXUS>m</SEXUS>
   </ITEM>
   <ITEM num="243">
      <ID>35273</ID>
      <SEXUS>m</SEXUS>
      <GND>131545949</GND>
   </ITEM>
   <ITEM num="244">
      <ID>35274</ID>
      <SEXUS>m</SEXUS>
      <GND>118844903</GND>
   </ITEM>
   <ITEM num="245">
      <ID>35275</ID>
      <SEXUS>m</SEXUS>
      <GND>130567043</GND>
   </ITEM>
   <ITEM num="246">
      <ID>35276</ID>
      <SEXUS>m</SEXUS>
   </ITEM>
   <ITEM num="247">
      <ID>35277</ID>
      <SEXUS>m</SEXUS>
      <GND>11629762X</GND>
   </ITEM>
   <ITEM num="248">
      <ID>35278</ID>
   </ITEM>
   <ITEM num="249">
      <ID>35279</ID>
      <SEXUS>m</SEXUS>
   </ITEM>
   <ITEM num="250">
      <ID>35280</ID>
      <SEXUS>m</SEXUS>
   </ITEM>
   <ITEM num="251">
      <ID>35281</ID>
      <SEXUS>w</SEXUS>
   </ITEM>
   <ITEM num="252">
      <ID>35282</ID>
      <SEXUS>m</SEXUS>
      <GND>10007894X</GND>
   </ITEM>
   <ITEM num="253">
      <ID>35283</ID>
      <SEXUS>m</SEXUS>
      <GND>118812343</GND>
   </ITEM>
   <ITEM num="254">
      <ID>35284</ID>
      <SEXUS>m</SEXUS>
      <GND>118645021</GND>
   </ITEM>
   <ITEM num="255">
      <ID>35285</ID>
      <SEXUS>m</SEXUS>
      <GND>116299290</GND>
   </ITEM>
   <ITEM num="256">
      <ID>35286</ID>
      <SEXUS>m</SEXUS>
      <GND>116299355</GND>
   </ITEM>
   <ITEM num="257">
      <ID>35287</ID>
      <SEXUS>m</SEXUS>
      <GND>1037416694</GND>
   </ITEM>
   <ITEM num="258">
      <ID>35288</ID>
      <SEXUS>w</SEXUS>
   </ITEM>
   <ITEM num="259">
      <ID>35289</ID>
      <SEXUS>w</SEXUS>
   </ITEM>
   <ITEM num="260">
      <ID>35290</ID>
      <SEXUS>m</SEXUS>
      <GND>100009670</GND>
   </ITEM>
   <ITEM num="261">
      <ID>35291</ID>
   </ITEM>
   <ITEM num="262">
      <ID>35292</ID>
      <SEXUS>m</SEXUS>
      <GND>131538918</GND>
   </ITEM>
   <ITEM num="263">
      <ID>35293</ID>
      <SEXUS>m</SEXUS>
   </ITEM>
   <ITEM num="264">
      <ID>35294</ID>
      <SEXUS>m</SEXUS>
      <GND>100011152</GND>
   </ITEM>
   <ITEM num="265">
      <ID>35295</ID>
      <SEXUS>m</SEXUS>
      <GND>11601198X</GND>
   </ITEM>
   <ITEM num="266">
      <ID>35296</ID>
      <SEXUS>m</SEXUS>
      <GND>1096359936</GND>
   </ITEM>
   <ITEM num="267">
      <ID>35297</ID>
      <SEXUS>m</SEXUS>
   </ITEM>
   <ITEM num="268">
      <ID>35298</ID>
      <SEXUS>m</SEXUS>
      <GND>116309393</GND>
   </ITEM>
   <ITEM num="269">
      <ID>35299</ID>
      <SEXUS>m</SEXUS>
   </ITEM>
   <ITEM num="270">
      <ID>35300</ID>
      <SEXUS>m</SEXUS>
      <GND>116309784</GND>
   </ITEM>
   <ITEM num="271">
      <ID>35301</ID>
      <SEXUS>m</SEXUS>
      <GND>124878113</GND>
   </ITEM>
   <ITEM num="272">
      <ID>35302</ID>
      <SEXUS>m</SEXUS>
      <GND>100414907</GND>
   </ITEM>
   <ITEM num="273">
      <ID>35303</ID>
      <SEXUS>m</SEXUS>
      <LITERATUR>Inventar GSA 25/XLIX,1b (Reproduktion)</LITERATUR>
      <GND>118846922</GND>
   </ITEM>
   <ITEM num="274">
      <ID>35304</ID>
      <SEXUS>m</SEXUS>
      <GND>118503081</GND>
   </ITEM>
   <ITEM num="275">
      <ID>35305</ID>
      <SEXUS>m</SEXUS>
      <GND>123386462</GND>
   </ITEM>
   <ITEM num="276">
      <ID>35306</ID>
      <SEXUS>m</SEXUS>
   </ITEM>
   <ITEM num="277">
      <ID>35307</ID>
      <SEXUS>m</SEXUS>
      <GND>117661724</GND>
   </ITEM>
   <ITEM num="278">
      <ID>35308</ID>
      <SEXUS>m</SEXUS>
      <GND>129854697</GND>
   </ITEM>
   <ITEM num="279">
      <ID>35309</ID>
      <SEXUS>w</SEXUS>
      <GND>119064332</GND>
   </ITEM>
   <ITEM num="280">
      <ID>35310</ID>
      <SEXUS>m</SEXUS>
      <GND>104173254</GND>
   </ITEM>
   <ITEM num="281">
      <ID>35311</ID>
   </ITEM>
   <ITEM num="282">
      <ID>35312</ID>
      <SEXUS>m</SEXUS>
      <GND>140011293</GND>
   </ITEM>
   <ITEM num="283">
      <ID>35313</ID>
      <SEXUS>m</SEXUS>
      <GND>104173262</GND>
   </ITEM>
   <ITEM num="284">
      <ID>35314</ID>
      <SEXUS>m</SEXUS>
      <GND>118640100</GND>
   </ITEM>
   <ITEM num="285">
      <ID>35315</ID>
      <SEXUS>m</SEXUS>
      <GND>123920361</GND>
   </ITEM>
   <ITEM num="286">
      <ID>35316</ID>
      <SEXUS>m</SEXUS>
   </ITEM>
   <ITEM num="287">
      <ID>35317</ID>
      <SEXUS>m</SEXUS>
      <GND>119043610</GND>
   </ITEM>
   <ITEM num="288">
      <ID>35318</ID>
      <SEXUS>m</SEXUS>
      <GND>118649671</GND>
   </ITEM>
   <ITEM num="289">
      <ID>35319</ID>
      <SEXUS>w</SEXUS>
   </ITEM>
   <ITEM num="290">
      <ID>35320</ID>
      <SEXUS>m</SEXUS>
      <GND>118847805</GND>
   </ITEM>
   <ITEM num="291">
      <ID>35321</ID>
      <SEXUS>m</SEXUS>
      <GND>118952331</GND>
   </ITEM>
   <ITEM num="292">
      <ID>35322</ID>
      <SEXUS>m</SEXUS>
      <GND>132564130</GND>
   </ITEM>
   <ITEM num="293">
      <ID>35323</ID>
      <SEXUS>m</SEXUS>
      <GND>1160056242</GND>
   </ITEM>
   <ITEM num="294">
      <ID>35324</ID>
      <SEXUS>m</SEXUS>
      <GND>1031835318</GND>
   </ITEM>
   <ITEM num="295">
      <ID>35325</ID>
      <SEXUS>m</SEXUS>
      <GND>1053413750</GND>
   </ITEM>
   <ITEM num="296">
      <ID>35326</ID>
      <SEXUS>m</SEXUS>
      <GND>119060558</GND>
   </ITEM>
   <ITEM num="297">
      <ID>35327</ID>
   </ITEM>
   <ITEM num="298">
      <ID>35328</ID>
      <SEXUS>m</SEXUS>
      <GND>118649892</GND>
   </ITEM>
   <ITEM num="299">
      <ID>35329</ID>
      <SEXUS>w</SEXUS>
   </ITEM>
   <ITEM num="300">
      <ID>35330</ID>
   </ITEM>
   <ITEM num="301">
      <ID>35331</ID>
   </ITEM>
   <ITEM num="302">
      <ID>35332</ID>
      <SEXUS>m</SEXUS>
      <GND>105283650X</GND>
   </ITEM>
   <ITEM num="303">
      <ID>35333</ID>
      <SEXUS>m</SEXUS>
      <GND>118503839</GND>
   </ITEM>
   <ITEM num="304">
      <ID>35334</ID>
      <SEXUS>m</SEXUS>
      <GND>118859269</GND>
   </ITEM>
   <ITEM num="305">
      <ID>35335</ID>
      <SEXUS>m</SEXUS>
      <LITERATUR>WBIS</LITERATUR>
      <GND>116320214</GND>
   </ITEM>
   <ITEM num="306">
      <ID>35336</ID>
      <SEXUS>m</SEXUS>