<?xml version = "1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE NDB_BEZIEHUNGEN [
<!ELEMENT NDB_BEZIEHUNGEN (ITEM)*>
<!ELEMENT ITEM (ID1, ID2, AGRELON_ID1, AGRELON_ID2)>
<!ATTLIST ITEM num CDATA #REQUIRED>
<!ELEMENT ID1 (#PCDATA)>
<!ELEMENT ID2 (#PCDATA)>
<!ELEMENT AGRELON_ID1 (#PCDATA)>
<!ELEMENT AGRELON_ID2 (#PCDATA)>
]>
<NDB_BEZIEHUNGEN>
   <ITEM num="1">
      <ID1>239</ID1>
      <ID2>43000</ID2>
      <AGRELON_ID1>4020</AGRELON_ID1>
      <AGRELON_ID2>4040</AGRELON_ID2>
   </ITEM>
   <ITEM num="2">
      <ID1>927</ID1>
      <ID2>36039</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="3">
      <ID1>1906</ID1>
      <ID2>37000</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="4">
      <ID1>1906</ID1>
      <ID2>49834</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="5">
      <ID1>2187</ID1>
      <ID2>37242</ID2>
      <AGRELON_ID1>4020</AGRELON_ID1>
      <AGRELON_ID2>4040</AGRELON_ID2>
   </ITEM>
   <ITEM num="6">
      <ID1>2187</ID1>
      <ID2>49539</ID2>
      <AGRELON_ID1>4020</AGRELON_ID1>
      <AGRELON_ID2>4040</AGRELON_ID2>
   </ITEM>
   <ITEM num="7">
      <ID1>2189</ID1>
      <ID2>2187</ID2>
      <AGRELON_ID1>4030</AGRELON_ID1>
      <AGRELON_ID2>4010</AGRELON_ID2>
   </ITEM>
   <ITEM num="8">
      <ID1>2189</ID1>
      <ID2>43118</ID2>
      <AGRELON_ID1>4020</AGRELON_ID1>
      <AGRELON_ID2>4040</AGRELON_ID2>
   </ITEM>
   <ITEM num="9">
      <ID1>2189</ID1>
      <ID2>66166</ID2>
      <AGRELON_ID1>4030</AGRELON_ID1>
      <AGRELON_ID2>4010</AGRELON_ID2>
   </ITEM>
   <ITEM num="10">
      <ID1>2189</ID1>
      <ID2>66369</ID2>
      <AGRELON_ID1>4030</AGRELON_ID1>
      <AGRELON_ID2>4010</AGRELON_ID2>
   </ITEM>
   <ITEM num="11">
      <ID1>2189</ID1>
      <ID2>68305</ID2>
      <AGRELON_ID1>4120</AGRELON_ID1>
      <AGRELON_ID2>4120</AGRELON_ID2>
   </ITEM>
   <ITEM num="12">
      <ID1>2189</ID1>
      <ID2>81943</ID2>
      <AGRELON_ID1>4030</AGRELON_ID1>
      <AGRELON_ID2>4010</AGRELON_ID2>
   </ITEM>
   <ITEM num="13">
      <ID1>2189</ID1>
      <ID2>85846</ID2>
      <AGRELON_ID1>4030</AGRELON_ID1>
      <AGRELON_ID2>4010</AGRELON_ID2>
   </ITEM>
   <ITEM num="14">
      <ID1>2189</ID1>
      <ID2>85847</ID2>
      <AGRELON_ID1>4030</AGRELON_ID1>
      <AGRELON_ID2>4010</AGRELON_ID2>
   </ITEM>
   <ITEM num="15">
      <ID1>2212</ID1>
      <ID2>37258</ID2>
      <AGRELON_ID1>4050</AGRELON_ID1>
      <AGRELON_ID2>4110</AGRELON_ID2>
   </ITEM>
   <ITEM num="16">
      <ID1>2212</ID1>
      <ID2>43697</ID2>
      <AGRELON_ID1>4060</AGRELON_ID1>
      <AGRELON_ID2>4060</AGRELON_ID2>
   </ITEM>
   <ITEM num="17">
      <ID1>2212</ID1>
      <ID2>43699</ID2>
      <AGRELON_ID1>4060</AGRELON_ID1>
      <AGRELON_ID2>4060</AGRELON_ID2>
   </ITEM>
   <ITEM num="18">
      <ID1>2212</ID1>
      <ID2>69507</ID2>
      <AGRELON_ID1>4060</AGRELON_ID1>
      <AGRELON_ID2>4060</AGRELON_ID2>
   </ITEM>
   <ITEM num="19">
      <ID1>2390</ID1>
      <ID2>53393</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="20">
      <ID1>2735</ID1>
      <ID2>37800</ID2>
      <AGRELON_ID1>4030</AGRELON_ID1>
      <AGRELON_ID2>4010</AGRELON_ID2>
   </ITEM>
   <ITEM num="21">
      <ID1>3267</ID1>
      <ID2>54638</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="22">
      <ID1>3703</ID1>
      <ID2>43588</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="23">
      <ID1>3966</ID1>
      <ID2>39140</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="24">
      <ID1>5848</ID1>
      <ID2>36555</ID2>
      <AGRELON_ID1>1010</AGRELON_ID1>
      <AGRELON_ID2>1010</AGRELON_ID2>
   </ITEM>
   <ITEM num="25">
      <ID1>6782</ID1>
      <ID2>45521</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="26">
      <ID1>6782</ID1>
      <ID2>45742</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="27">
      <ID1>7038</ID1>
      <ID2>42330</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="28">
      <ID1>11065</ID1>
      <ID2>45122</ID2>
      <AGRELON_ID1>4120</AGRELON_ID1>
      <AGRELON_ID2>4120</AGRELON_ID2>
   </ITEM>
   <ITEM num="29">
      <ID1>11085</ID1>
      <ID2>40960</ID2>
      <AGRELON_ID1>4030</AGRELON_ID1>
      <AGRELON_ID2>4010</AGRELON_ID2>
   </ITEM>
   <ITEM num="30">
      <ID1>11085</ID1>
      <ID2>40962</ID2>
      <AGRELON_ID1>4040</AGRELON_ID1>
      <AGRELON_ID2>4020</AGRELON_ID2>
   </ITEM>
   <ITEM num="31">
      <ID1>11087</ID1>
      <ID2>36021</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="32">
      <ID1>11087</ID1>
      <ID2>40438</ID2>
      <AGRELON_ID1>4090</AGRELON_ID1>
      <AGRELON_ID2>4090</AGRELON_ID2>
   </ITEM>
   <ITEM num="33">
      <ID1>11087</ID1>
      <ID2>40959</ID2>
      <AGRELON_ID1>4030</AGRELON_ID1>
      <AGRELON_ID2>4010</AGRELON_ID2>
   </ITEM>
   <ITEM num="34">
      <ID1>11093</ID1>
      <ID2>38077</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="35">
      <ID1>11093</ID1>
      <ID2>38079</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="36">
      <ID1>11093</ID1>
      <ID2>40926</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="37">
      <ID1>11093</ID1>
      <ID2>45046</ID2>
      <AGRELON_ID1>4120</AGRELON_ID1>
      <AGRELON_ID2>4120</AGRELON_ID2>
   </ITEM>
   <ITEM num="38">
      <ID1>11096</ID1>
      <ID2>40959</ID2>
      <AGRELON_ID1>4120</AGRELON_ID1>
      <AGRELON_ID2>4120</AGRELON_ID2>
   </ITEM>
   <ITEM num="39">
      <ID1>11103</ID1>
      <ID2>11104</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="40">
      <ID1>11142</ID1>
      <ID2>40946</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="41">
      <ID1>11143</ID1>
      <ID2>11142</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="42">
      <ID1>11143</ID1>
      <ID2>11144</ID2>
      <AGRELON_ID1>4120</AGRELON_ID1>
      <AGRELON_ID2>4120</AGRELON_ID2>
   </ITEM>
   <ITEM num="43">
      <ID1>11143</ID1>
      <ID2>40946</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="44">
      <ID1>11144</ID1>
      <ID2>11142</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="45">
      <ID1>11144</ID1>
      <ID2>40946</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="46">
      <ID1>11146</ID1>
      <ID2>40957</ID2>
      <AGRELON_ID1>4040</AGRELON_ID1>
      <AGRELON_ID2>4020</AGRELON_ID2>
   </ITEM>
   <ITEM num="47">
      <ID1>11146</ID1>
      <ID2>80791</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="48">
      <ID1>11156</ID1>
      <ID2>68061</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="49">
      <ID1>11159</ID1>
      <ID2>39982</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="50">
      <ID1>11159</ID1>
      <ID2>44696</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="51">
      <ID1>11159</ID1>
      <ID2>45044</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="52">
      <ID1>19242</ID1>
      <ID2>42972</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="53">
      <ID1>19264</ID1>
      <ID2>35346</ID2>
      <AGRELON_ID1>4050</AGRELON_ID1>
      <AGRELON_ID2>4110</AGRELON_ID2>
   </ITEM>
   <ITEM num="54">
      <ID1>19266</ID1>
      <ID2>35346</ID2>
      <AGRELON_ID1>4020</AGRELON_ID1>
      <AGRELON_ID2>4040</AGRELON_ID2>
   </ITEM>
   <ITEM num="55">
      <ID1>19346</ID1>
      <ID2>35552</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="56">
      <ID1>19347</ID1>
      <ID2>35552</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="57">
      <ID1>19427</ID1>
      <ID2>19426</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="58">
      <ID1>19478</ID1>
      <ID2>19477</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="59">
      <ID1>19633</ID1>
      <ID2>36161</ID2>
      <AGRELON_ID1>4020</AGRELON_ID1>
      <AGRELON_ID2>4040</AGRELON_ID2>
   </ITEM>
   <ITEM num="60">
      <ID1>19634</ID1>
      <ID2>36161</ID2>
      <AGRELON_ID1>4020</AGRELON_ID1>
      <AGRELON_ID2>4040</AGRELON_ID2>
   </ITEM>
   <ITEM num="61">
      <ID1>19647</ID1>
      <ID2>43351</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="62">
      <ID1>19725</ID1>
      <ID2>19723</ID2>
      <AGRELON_ID1>4020</AGRELON_ID1>
      <AGRELON_ID2>4040</AGRELON_ID2>
   </ITEM>
   <ITEM num="63">
      <ID1>19726</ID1>
      <ID2>19723</ID2>
      <AGRELON_ID1>4020</AGRELON_ID1>
      <AGRELON_ID2>4040</AGRELON_ID2>
   </ITEM>
   <ITEM num="64">
      <ID1>19727</ID1>
      <ID2>19723</ID2>
      <AGRELON_ID1>4020</AGRELON_ID1>
      <AGRELON_ID2>4040</AGRELON_ID2>
   </ITEM>
   <ITEM num="65">
      <ID1>19742</ID1>
      <ID2>49229</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="66">
      <ID1>19743</ID1>
      <ID2>49229</ID2>
      <AGRELON_ID1>4020</AGRELON_ID1>
      <AGRELON_ID2>4040</AGRELON_ID2>
   </ITEM>
   <ITEM num="67">
      <ID1>19765</ID1>
      <ID2>19764</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="68">
      <ID1>19819</ID1>
      <ID2>43491</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="69">
      <ID1>19820</ID1>
      <ID2>43491</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="70">
      <ID1>19834</ID1>
      <ID2>19833</ID2>
      <AGRELON_ID1>4120</AGRELON_ID1>
      <AGRELON_ID2>4120</AGRELON_ID2>
   </ITEM>
   <ITEM num="71">
      <ID1>19859</ID1>
      <ID2>49778</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="72">
      <ID1>19860</ID1>
      <ID2>49778</ID2>
      <AGRELON_ID1>4020</AGRELON_ID1>
      <AGRELON_ID2>4040</AGRELON_ID2>
   </ITEM>
   <ITEM num="73">
      <ID1>19861</ID1>
      <ID2>49778</ID2>
      <AGRELON_ID1>4020</AGRELON_ID1>
      <AGRELON_ID2>4040</AGRELON_ID2>
   </ITEM>
   <ITEM num="74">
      <ID1>19862</ID1>
      <ID2>49778</ID2>
      <AGRELON_ID1>4020</AGRELON_ID1>
      <AGRELON_ID2>4040</AGRELON_ID2>
   </ITEM>
   <ITEM num="75">
      <ID1>19864</ID1>
      <ID2>49778</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="76">
      <ID1>19919</ID1>
      <ID2>37012</ID2>
      <AGRELON_ID1>4120</AGRELON_ID1>
      <AGRELON_ID2>4120</AGRELON_ID2>
   </ITEM>
   <ITEM num="77">
      <ID1>19987</ID1>
      <ID2>43659</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="78">
      <ID1>19988</ID1>
      <ID2>43659</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="79">
      <ID1>20220</ID1>
      <ID2>37683</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="80">
      <ID1>20339</ID1>
      <ID2>20338</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="81">
      <ID1>20340</ID1>
      <ID2>20338</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="82">
      <ID1>20364</ID1>
      <ID2>43940</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="83">
      <ID1>20371</ID1>
      <ID2>20370</ID2>
      <AGRELON_ID1>4020</AGRELON_ID1>
      <AGRELON_ID2>4040</AGRELON_ID2>
   </ITEM>
   <ITEM num="84">
      <ID1>20577</ID1>
      <ID2>44128</ID2>
      <AGRELON_ID1>4020</AGRELON_ID1>
      <AGRELON_ID2>4040</AGRELON_ID2>
   </ITEM>
   <ITEM num="85">
      <ID1>20626</ID1>
      <ID2>45126</ID2>
      <AGRELON_ID1>4080</AGRELON_ID1>
      <AGRELON_ID2>4070</AGRELON_ID2>
   </ITEM>
   <ITEM num="86">
      <ID1>20870</ID1>
      <ID2>20869</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="87">
      <ID1>21045</ID1>
      <ID2>21044</ID2>
      <AGRELON_ID1>4050</AGRELON_ID1>
      <AGRELON_ID2>4110</AGRELON_ID2>
   </ITEM>
   <ITEM num="88">
      <ID1>21115</ID1>
      <ID2>21114</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="89">
      <ID1>21195</ID1>
      <ID2>39641</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="90">
      <ID1>21257</ID1>
      <ID2>44650</ID2>
      <AGRELON_ID1>4020</AGRELON_ID1>
      <AGRELON_ID2>4040</AGRELON_ID2>
   </ITEM>
   <ITEM num="91">
      <ID1>21258</ID1>
      <ID2>44650</ID2>
      <AGRELON_ID1>4020</AGRELON_ID1>
      <AGRELON_ID2>4040</AGRELON_ID2>
   </ITEM>
   <ITEM num="92">
      <ID1>21259</ID1>
      <ID2>44650</ID2>
      <AGRELON_ID1>4020</AGRELON_ID1>
      <AGRELON_ID2>4040</AGRELON_ID2>
   </ITEM>
   <ITEM num="93">
      <ID1>21283</ID1>
      <ID2>51696</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="94">
      <ID1>21284</ID1>
      <ID2>21283</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="95">
      <ID1>21285</ID1>
      <ID2>21283</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="96">
      <ID1>21306</ID1>
      <ID2>44628</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="97">
      <ID1>21395</ID1>
      <ID2>21394</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="98">
      <ID1>21555</ID1>
      <ID2>21554</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="99">
      <ID1>21556</ID1>
      <ID2>21554</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="100">
      <ID1>21755</ID1>
      <ID2>44993</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="101">
      <ID1>21756</ID1>
      <ID2>44993</ID2>
      <AGRELON_ID1>4020</AGRELON_ID1>
      <AGRELON_ID2>4040</AGRELON_ID2>
   </ITEM>
   <ITEM num="102">
      <ID1>21792</ID1>
      <ID2>21791</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="103">
      <ID1>21864</ID1>
      <ID2>45122</ID2>
      <AGRELON_ID1>4020</AGRELON_ID1>
      <AGRELON_ID2>4040</AGRELON_ID2>
   </ITEM>
   <ITEM num="104">
      <ID1>21912</ID1>
      <ID2>21911</ID2>
      <AGRELON_ID1>4020</AGRELON_ID1>
      <AGRELON_ID2>4040</AGRELON_ID2>
   </ITEM>
   <ITEM num="105">
      <ID1>21973</ID1>
      <ID2>45221</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="106">
      <ID1>21976</ID1>
      <ID2>45221</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="107">
      <ID1>21994</ID1>
      <ID2>49230</ID2>
      <AGRELON_ID1>4030</AGRELON_ID1>
      <AGRELON_ID2>4010</AGRELON_ID2>
   </ITEM>
   <ITEM num="108">
      <ID1>21995</ID1>
      <ID2>21994</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="109">
      <ID1>22002</ID1>
      <ID2>41353</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="110">
      <ID1>22037</ID1>
      <ID2>41429</ID2>
      <AGRELON_ID1>4020</AGRELON_ID1>
      <AGRELON_ID2>4040</AGRELON_ID2>
   </ITEM>
   <ITEM num="111">
      <ID1>22059</ID1>
      <ID2>41469</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="112">
      <ID1>22083</ID1>
      <ID2>41359</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="113">
      <ID1>22109</ID1>
      <ID2>41537</ID2>
      <AGRELON_ID1>4050</AGRELON_ID1>
      <AGRELON_ID2>4110</AGRELON_ID2>
   </ITEM>
   <ITEM num="114">
      <ID1>22165</ID1>
      <ID2>22164</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="115">
      <ID1>22236</ID1>
      <ID2>22235</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="116">
      <ID1>22330</ID1>
      <ID2>22329</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="117">
      <ID1>22364</ID1>
      <ID2>22363</ID2>
      <AGRELON_ID1>4020</AGRELON_ID1>
      <AGRELON_ID2>4040</AGRELON_ID2>
   </ITEM>
   <ITEM num="118">
      <ID1>22391</ID1>
      <ID2>22390</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="119">
      <ID1>22395</ID1>
      <ID2>45626</ID2>
      <AGRELON_ID1>4020</AGRELON_ID1>
      <AGRELON_ID2>4040</AGRELON_ID2>
   </ITEM>
   <ITEM num="120">
      <ID1>22404</ID1>
      <ID2>22403</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="121">
      <ID1>22472</ID1>
      <ID2>42555</ID2>
      <AGRELON_ID1>4020</AGRELON_ID1>
      <AGRELON_ID2>4040</AGRELON_ID2>
   </ITEM>
   <ITEM num="122">
      <ID1>22472</ID1>
      <ID2>47229</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="123">
      <ID1>22473</ID1>
      <ID2>42555</ID2>
      <AGRELON_ID1>4020</AGRELON_ID1>
      <AGRELON_ID2>4040</AGRELON_ID2>
   </ITEM>
   <ITEM num="124">
      <ID1>22473</ID1>
      <ID2>47229</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="125">
      <ID1>22515</ID1>
      <ID2>45724</ID2>
      <AGRELON_ID1>4020</AGRELON_ID1>
      <AGRELON_ID2>4040</AGRELON_ID2>
   </ITEM>
   <ITEM num="126">
      <ID1>22593</ID1>
      <ID2>22592</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="127">
      <ID1>22594</ID1>
      <ID2>22592</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="128">
      <ID1>22608</ID1>
      <ID2>22607</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="129">
      <ID1>22609</ID1>
      <ID2>22607</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="130">
      <ID1>22632</ID1>
      <ID2>42845</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="131">
      <ID1>22682</ID1>
      <ID2>22681</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="132">
      <ID1>22683</ID1>
      <ID2>22681</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="133">
      <ID1>22684</ID1>
      <ID2>22681</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="134">
      <ID1>22781</ID1>
      <ID2>4780</ID2>
      <AGRELON_ID1>4120</AGRELON_ID1>
      <AGRELON_ID2>4120</AGRELON_ID2>
   </ITEM>
   <ITEM num="135">
      <ID1>22781</ID1>
      <ID2>49610</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="136">
      <ID1>35180</ID1>
      <ID2>59194</ID2>
      <AGRELON_ID1>3090</AGRELON_ID1>
      <AGRELON_ID2>3080</AGRELON_ID2>
   </ITEM>
   <ITEM num="137">
      <ID1>35239</ID1>
      <ID2>35237</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="138">
      <ID1>35239</ID1>
      <ID2>38010</ID2>
      <AGRELON_ID1>4120</AGRELON_ID1>
      <AGRELON_ID2>4120</AGRELON_ID2>
   </ITEM>
   <ITEM num="139">
      <ID1>35239</ID1>
      <ID2>80030</ID2>
      <AGRELON_ID1>4120</AGRELON_ID1>
      <AGRELON_ID2>4120</AGRELON_ID2>
   </ITEM>
   <ITEM num="140">
      <ID1>35248</ID1>
      <ID2>45043</ID2>
      <AGRELON_ID1>3080</AGRELON_ID1>
      <AGRELON_ID2>3090</AGRELON_ID2>
   </ITEM>
   <ITEM num="141">
      <ID1>35281</ID1>
      <ID2>35280</ID2>
      <AGRELON_ID1>4030</AGRELON_ID1>
      <AGRELON_ID2>4010</AGRELON_ID2>
   </ITEM>
   <ITEM num="142">
      <ID1>35285</ID1>
      <ID2>98748</ID2>
      <AGRELON_ID1>4120</AGRELON_ID1>
      <AGRELON_ID2>4120</AGRELON_ID2>
   </ITEM>
   <ITEM num="143">
      <ID1>35288</ID1>
      <ID2>35287</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="144">
      <ID1>35295</ID1>
      <ID2>42978</ID2>
      <AGRELON_ID1>4030</AGRELON_ID1>
      <AGRELON_ID2>4010</AGRELON_ID2>
   </ITEM>
   <ITEM num="145">
      <ID1>35295</ID1>
      <ID2>53626</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="146">
      <ID1>35429</ID1>
      <ID2>35430</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="147">
      <ID1>35447</ID1>
      <ID2>35446</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="148">
      <ID1>35464</ID1>
      <ID2>43043</ID2>
      <AGRELON_ID1>4030</AGRELON_ID1>
      <AGRELON_ID2>4010</AGRELON_ID2>
   </ITEM>
   <ITEM num="149">
      <ID1>35510</ID1>
      <ID2>35509</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="150">
      <ID1>35514</ID1>
      <ID2>35513</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="151">
      <ID1>35528</ID1>
      <ID2>36952</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="152">
      <ID1>35536</ID1>
      <ID2>35509</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="153">
      <ID1>35536</ID1>
      <ID2>35510</ID2>
      <AGRELON_ID1>4120</AGRELON_ID1>
      <AGRELON_ID2>4120</AGRELON_ID2>
   </ITEM>
   <ITEM num="154">
      <ID1>35540</ID1>
      <ID2>40270</ID2>
      <AGRELON_ID1>4120</AGRELON_ID1>
      <AGRELON_ID2>4120</AGRELON_ID2>
   </ITEM>
   <ITEM num="155">
      <ID1>35557</ID1>
      <ID2>43078</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="156">
      <ID1>35584</ID1>
      <ID2>35582</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="157">
      <ID1>35586</ID1>
      <ID2>35580</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="158">
      <ID1>35633</ID1>
      <ID2>35632</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="159">
      <ID1>35652</ID1>
      <ID2>35655</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="160">
      <ID1>35653</ID1>
      <ID2>35652</ID2>
      <AGRELON_ID1>4120</AGRELON_ID1>
      <AGRELON_ID2>4120</AGRELON_ID2>
   </ITEM>
   <ITEM num="161">
      <ID1>35654</ID1>
      <ID2>43103</ID2>
      <AGRELON_ID1>4120</AGRELON_ID1>
      <AGRELON_ID2>4120</AGRELON_ID2>
   </ITEM>
   <ITEM num="162">
      <ID1>35656</ID1>
      <ID2>43103</ID2>
      <AGRELON_ID1>4120</AGRELON_ID1>
      <AGRELON_ID2>4120</AGRELON_ID2>
   </ITEM>
   <ITEM num="163">
      <ID1>35705</ID1>
      <ID2>53653</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="164">
      <ID1>35716</ID1>
      <ID2>43116</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="165">
      <ID1>35716</ID1>
      <ID2>62976</ID2>
      <AGRELON_ID1>4030</AGRELON_ID1>
      <AGRELON_ID2>4010</AGRELON_ID2>
   </ITEM>
   <ITEM num="166">
      <ID1>35717</ID1>
      <ID2>47236</ID2>
      <AGRELON_ID1>4012</AGRELON_ID1>
      <AGRELON_ID2>4032</AGRELON_ID2>
   </ITEM>
   <ITEM num="167">
      <ID1>35724</ID1>
      <ID2>58953</ID2>
      <AGRELON_ID1>2010</AGRELON_ID1>
      <AGRELON_ID2>2020</AGRELON_ID2>
   </ITEM>
   <ITEM num="168">
      <ID1>35724</ID1>
      <ID2>59481</ID2>
      <AGRELON_ID1>2010</AGRELON_ID1>
      <AGRELON_ID2>2020</AGRELON_ID2>
   </ITEM>
   <ITEM num="169">
      <ID1>35725</ID1>
      <ID2>35726</ID2>
      <AGRELON_ID1>4030</AGRELON_ID1>
      <AGRELON_ID2>4010</AGRELON_ID2>
   </ITEM>
   <ITEM num="170">
      <ID1>35725</ID1>
      <ID2>35729</ID2>
      <AGRELON_ID1>4030</AGRELON_ID1>
      <AGRELON_ID2>4010</AGRELON_ID2>
   </ITEM>
   <ITEM num="171">
      <ID1>35725</ID1>
      <ID2>58953</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="172">
      <ID1>35726</ID1>
      <ID2>58953</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="173">
      <ID1>35726</ID1>
      <ID2>59481</ID2>
      <AGRELON_ID1>4050</AGRELON_ID1>
      <AGRELON_ID2>4110</AGRELON_ID2>
   </ITEM>
   <ITEM num="174">
      <ID1>35730</ID1>
      <ID2>35732</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="175">
      <ID1>35730</ID1>
      <ID2>43127</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="176">
      <ID1>35731</ID1>
      <ID2>35732</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="177">
      <ID1>35731</ID1>
      <ID2>43127</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="178">
      <ID1>35732</ID1>
      <ID2>58953</ID2>
      <AGRELON_ID1>4090</AGRELON_ID1>
      <AGRELON_ID2>4090</AGRELON_ID2>
   </ITEM>
   <ITEM num="179">
      <ID1>35741</ID1>
      <ID2>43140</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="180">
      <ID1>35757</ID1>
      <ID2>35758</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="181">
      <ID1>35757</ID1>
      <ID2>70462</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="182">
      <ID1>35758</ID1>
      <ID2>82696</ID2>
      <AGRELON_ID1>4120</AGRELON_ID1>
      <AGRELON_ID2>4120</AGRELON_ID2>
   </ITEM>
   <ITEM num="183">
      <ID1>35762</ID1>
      <ID2>37060</ID2>
      <AGRELON_ID1>1010</AGRELON_ID1>
      <AGRELON_ID2>1010</AGRELON_ID2>
   </ITEM>
   <ITEM num="184">
      <ID1>35762</ID1>
      <ID2>37060</ID2>
      <AGRELON_ID1>3090</AGRELON_ID1>
      <AGRELON_ID2>3080</AGRELON_ID2>
   </ITEM>
   <ITEM num="185">
      <ID1>35764</ID1>
      <ID2>35763</ID2>
      <AGRELON_ID1>4120</AGRELON_ID1>
      <AGRELON_ID2>4120</AGRELON_ID2>
   </ITEM>
   <ITEM num="186">
      <ID1>35770</ID1>
      <ID2>43000</ID2>
      <AGRELON_ID1>1010</AGRELON_ID1>
      <AGRELON_ID2>1010</AGRELON_ID2>
   </ITEM>
   <ITEM num="187">
      <ID1>35777</ID1>
      <ID2>43252</ID2>
      <AGRELON_ID1>4030</AGRELON_ID1>
      <AGRELON_ID2>4010</AGRELON_ID2>
   </ITEM>
   <ITEM num="188">
      <ID1>35779</ID1>
      <ID2>35777</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="189">
      <ID1>35781</ID1>
      <ID2>39527</ID2>
      <AGRELON_ID1>4090</AGRELON_ID1>
      <AGRELON_ID2>4090</AGRELON_ID2>
   </ITEM>
   <ITEM num="190">
      <ID1>35790</ID1>
      <ID2>35789</ID2>
      <AGRELON_ID1>4100</AGRELON_ID1>
      <AGRELON_ID2>4100</AGRELON_ID2>
   </ITEM>
   <ITEM num="191">
      <ID1>35790</ID1>
      <ID2>67962</ID2>
      <AGRELON_ID1>4010</AGRELON_ID1>
      <AGRELON_ID2>4030</AGRELON_ID2>
   </ITEM>
   <ITEM num="192">
      <ID1>35793</ID1>
      <ID2>35792</ID2>
      <AGRELON_ID1>4120</AGRELON_ID1>
      <AGRELON_ID2>4120</AGRELON_ID2>
   </ITEM>
   <ITEM num="193">
      <ID1>35802</ID1>
      <ID2>35801</ID2>
      <AGRELON_ID1>4030</AGRELON_ID1>
      <AGRELON_ID2>4010</AGRELON_ID2>
   </ITEM>
   <ITEM num="194">
      <ID1>35811</ID1>
      <ID2>35812</ID2>
      <AGRELON_ID1>4120</AGRELON_ID1>
      <AGRELON_ID2>4120</AGRELON_ID2>
   </ITEM>
   <ITEM num="195">
      <ID1>35818</ID1>
      <ID2>39103</ID2>
      <AGRELON_ID1>4090</AGRELON_ID1>