<?xml version = "1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE NDB_ORTE [
<!ELEMENT NDB_ORTE (ITEM)*>
<!ELEMENT ITEM (ID, LFDNR, ORT?, ART?, SNDB_ID?)>
<!ATTLIST ITEM num CDATA #REQUIRED>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT LFDNR (#PCDATA)>
<!ELEMENT ORT (#PCDATA)>
<!ELEMENT ART (#PCDATA)>
<!ELEMENT SNDB_ID (#PCDATA)>
]>
<NDB_ORTE>
   <ITEM num="1">
      <ID>71</ID>
      <LFDNR>71</LFDNR>
      <ORT>Leipzig</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78408</SNDB_ID>
   </ITEM>
   <ITEM num="2">
      <ID>71</ID>
      <LFDNR>72</LFDNR>
      <ORT>Kassel</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78244</SNDB_ID>
   </ITEM>
   <ITEM num="3">
      <ID>391</ID>
      <LFDNR>13662</LFDNR>
      <ORT>Eisfeld</ORT>
      <ART>Geburtsort</ART>
      <SNDB_ID>91067</SNDB_ID>
   </ITEM>
   <ITEM num="4">
      <ID>391</ID>
      <LFDNR>17382</LFDNR>
      <ORT>Kassel</ORT>
      <ART>Sterbeort</ART>
      <SNDB_ID>78244</SNDB_ID>
   </ITEM>
   <ITEM num="5">
      <ID>492</ID>
      <LFDNR>9787</LFDNR>
      <ORT>Paris</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78838</SNDB_ID>
   </ITEM>
   <ITEM num="6">
      <ID>492</ID>
      <LFDNR>9788</LFDNR>
      <ORT>Berlin</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77386</SNDB_ID>
   </ITEM>
   <ITEM num="7">
      <ID>762</ID>
      <LFDNR>73</LFDNR>
      <ORT>Weimar</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>79627</SNDB_ID>
   </ITEM>
   <ITEM num="8">
      <ID>762</ID>
      <LFDNR>74</LFDNR>
      <ORT>Göttingen</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77966</SNDB_ID>
   </ITEM>
   <ITEM num="9">
      <ID>1492</ID>
      <LFDNR>6541</LFDNR>
      <ORT>St. Petersburg</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78863</SNDB_ID>
   </ITEM>
   <ITEM num="10">
      <ID>1492</ID>
      <LFDNR>6542</LFDNR>
      <ORT>Berlin</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77386</SNDB_ID>
   </ITEM>
   <ITEM num="11">
      <ID>1502</ID>
      <LFDNR>42118</LFDNR>
      <ORT>Angers</ORT>
      <ART>Geburtsort</ART>
   </ITEM>
   <ITEM num="12">
      <ID>1502</ID>
      <LFDNR>42119</LFDNR>
      <ORT>Paris</ORT>
      <ART>Sterbeort</ART>
      <SNDB_ID>78838</SNDB_ID>
   </ITEM>
   <ITEM num="13">
      <ID>1906</ID>
      <LFDNR>79</LFDNR>
      <ORT>Weimar</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>79627</SNDB_ID>
   </ITEM>
   <ITEM num="14">
      <ID>2054</ID>
      <LFDNR>28591</LFDNR>
      <ORT>München</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78649</SNDB_ID>
   </ITEM>
   <ITEM num="15">
      <ID>2054</ID>
      <LFDNR>42486</LFDNR>
      <ORT>Berlin</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77386</SNDB_ID>
   </ITEM>
   <ITEM num="16">
      <ID>2054</ID>
      <LFDNR>44679</LFDNR>
      <ORT>Münchengosserstädt</ORT>
      <ART>Geburtsort</ART>
   </ITEM>
   <ITEM num="17">
      <ID>2054</ID>
      <LFDNR>44680</LFDNR>
      <ORT>München</ORT>
      <ART>Sterbeort</ART>
      <SNDB_ID>78649</SNDB_ID>
   </ITEM>
   <ITEM num="18">
      <ID>2054</ID>
      <LFDNR>44681</LFDNR>
      <ORT>Jena</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78191</SNDB_ID>
   </ITEM>
   <ITEM num="19">
      <ID>2162</ID>
      <LFDNR>29448</LFDNR>
      <ORT>Heidelberg</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78061</SNDB_ID>
   </ITEM>
   <ITEM num="20">
      <ID>2162</ID>
      <LFDNR>29449</LFDNR>
      <ORT>Darmstadt</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77639</SNDB_ID>
   </ITEM>
   <ITEM num="21">
      <ID>2162</ID>
      <LFDNR>29450</LFDNR>
      <ORT>München</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78649</SNDB_ID>
   </ITEM>
   <ITEM num="22">
      <ID>2162</ID>
      <LFDNR>29451</LFDNR>
      <ORT>Karlsruhe</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78240</SNDB_ID>
   </ITEM>
   <ITEM num="23">
      <ID>2318</ID>
      <LFDNR>13666</LFDNR>
      <ORT>Leipzig</ORT>
      <ART>Geburtsort</ART>
      <SNDB_ID>78408</SNDB_ID>
   </ITEM>
   <ITEM num="24">
      <ID>2318</ID>
      <LFDNR>17386</LFDNR>
      <ORT>Leipzig</ORT>
      <ART>Sterbeort</ART>
      <SNDB_ID>78408</SNDB_ID>
   </ITEM>
   <ITEM num="25">
      <ID>2390</ID>
      <LFDNR>82</LFDNR>
      <ORT>Leipzig</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78408</SNDB_ID>
   </ITEM>
   <ITEM num="26">
      <ID>2475</ID>
      <LFDNR>16448</LFDNR>
      <ORT>Frankfurt (Main)</ORT>
      <ART>Geburtsort</ART>
      <SNDB_ID>77853</SNDB_ID>
   </ITEM>
   <ITEM num="27">
      <ID>2475</ID>
      <LFDNR>19508</LFDNR>
      <ORT>Weimar</ORT>
      <ART>Sterbeort</ART>
      <SNDB_ID>79627</SNDB_ID>
   </ITEM>
   <ITEM num="28">
      <ID>2645</ID>
      <LFDNR>83</LFDNR>
      <ORT>Dresden</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77695</SNDB_ID>
   </ITEM>
   <ITEM num="29">
      <ID>2645</ID>
      <LFDNR>84</LFDNR>
      <ORT>Weimar</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>79627</SNDB_ID>
   </ITEM>
   <ITEM num="30">
      <ID>2645</ID>
      <LFDNR>85</LFDNR>
      <ORT>Neapel</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78674</SNDB_ID>
   </ITEM>
   <ITEM num="31">
      <ID>2645</ID>
      <LFDNR>86</LFDNR>
      <ORT>Rom</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>79060</SNDB_ID>
   </ITEM>
   <ITEM num="32">
      <ID>2645</ID>
      <LFDNR>87</LFDNR>
      <ORT>Berlin</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77386</SNDB_ID>
   </ITEM>
   <ITEM num="33">
      <ID>2645</ID>
      <LFDNR>88</LFDNR>
      <ORT>Zeulenroda</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>90861</SNDB_ID>
   </ITEM>
   <ITEM num="34">
      <ID>2645</ID>
      <LFDNR>89</LFDNR>
      <ORT>Prag</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78941</SNDB_ID>
   </ITEM>
   <ITEM num="35">
      <ID>2682</ID>
      <LFDNR>30591</LFDNR>
      <ORT>Pferdingsleben</ORT>
      <ART>Wirkungsort</ART>
   </ITEM>
   <ITEM num="36">
      <ID>2832</ID>
      <LFDNR>27650</LFDNR>
      <ORT>Leipzig</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78408</SNDB_ID>
   </ITEM>
   <ITEM num="37">
      <ID>3082</ID>
      <LFDNR>46716</LFDNR>
      <ORT>Frankfurt (Main)</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77853</SNDB_ID>
   </ITEM>
   <ITEM num="38">
      <ID>3267</ID>
      <LFDNR>2</LFDNR>
      <ORT>London</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78462</SNDB_ID>
   </ITEM>
   <ITEM num="39">
      <ID>3267</ID>
      <LFDNR>3</LFDNR>
      <ORT>Mörlach bei Nürnberg</ORT>
      <ART>Wirkungsort</ART>
   </ITEM>
   <ITEM num="40">
      <ID>3362</ID>
      <LFDNR>30828</LFDNR>
      <ORT>Berlin</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77386</SNDB_ID>
   </ITEM>
   <ITEM num="41">
      <ID>3420</ID>
      <LFDNR>34862</LFDNR>
      <ORT>Arolsen</ORT>
      <ART>Geburtsort</ART>
      <SNDB_ID>87537</SNDB_ID>
   </ITEM>
   <ITEM num="42">
      <ID>3420</ID>
      <LFDNR>34863</LFDNR>
      <ORT>München</ORT>
      <ART>Sterbeort</ART>
      <SNDB_ID>78649</SNDB_ID>
   </ITEM>
   <ITEM num="43">
      <ID>3562</ID>
      <LFDNR>34374</LFDNR>
      <ORT>London</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78462</SNDB_ID>
   </ITEM>
   <ITEM num="44">
      <ID>3595</ID>
      <LFDNR>34114</LFDNR>
      <ORT>Leipzig</ORT>
      <ART>Geburtsort</ART>
      <SNDB_ID>78408</SNDB_ID>
   </ITEM>
   <ITEM num="45">
      <ID>3703</ID>
      <LFDNR>31383</LFDNR>
      <ORT>Berlin</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77386</SNDB_ID>
   </ITEM>
   <ITEM num="46">
      <ID>3704</ID>
      <LFDNR>31385</LFDNR>
      <ORT>Berlin</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77386</SNDB_ID>
   </ITEM>
   <ITEM num="47">
      <ID>3704</ID>
      <LFDNR>31386</LFDNR>
      <ORT>Warschau</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>79614</SNDB_ID>
   </ITEM>
   <ITEM num="48">
      <ID>3917</ID>
      <LFDNR>31734</LFDNR>
      <ORT>Dresden</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77695</SNDB_ID>
   </ITEM>
   <ITEM num="49">
      <ID>3917</ID>
      <LFDNR>31735</LFDNR>
      <ORT>Ludwigslust</ORT>
      <ART>Wirkungsort</ART>
   </ITEM>
   <ITEM num="50">
      <ID>3924</ID>
      <LFDNR>11693</LFDNR>
      <ORT>Athen</ORT>
      <ART>Wirkungsort</ART>
   </ITEM>
   <ITEM num="51">
      <ID>3966</ID>
      <LFDNR>8</LFDNR>
      <ORT>Stuttgart</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>79399</SNDB_ID>
   </ITEM>
   <ITEM num="52">
      <ID>3966</ID>
      <LFDNR>9</LFDNR>
      <ORT>Wien</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>79663</SNDB_ID>
   </ITEM>
   <ITEM num="53">
      <ID>3966</ID>
      <LFDNR>10</LFDNR>
      <ORT>Rom</ORT>
      <ART>Wirkungsort</ART>
   </ITEM>
   <ITEM num="54">
      <ID>3966</ID>
      <LFDNR>13617</LFDNR>
      <ORT>Stuttgart</ORT>
      <ART>Geburtsort</ART>
      <SNDB_ID>79399</SNDB_ID>
   </ITEM>
   <ITEM num="55">
      <ID>3966</ID>
      <LFDNR>17346</LFDNR>
      <ORT>Stuttgart</ORT>
      <ART>Sterbeort</ART>
      <SNDB_ID>79399</SNDB_ID>
   </ITEM>
   <ITEM num="56">
      <ID>4333</ID>
      <LFDNR>38259</LFDNR>
      <ORT>Nürnberg</ORT>
      <ART>Geburtsort</ART>
      <SNDB_ID>78748</SNDB_ID>
   </ITEM>
   <ITEM num="57">
      <ID>4333</ID>
      <LFDNR>38260</LFDNR>
      <ORT>Nürnberg</ORT>
      <ART>Sterbeort</ART>
      <SNDB_ID>78748</SNDB_ID>
   </ITEM>
   <ITEM num="58">
      <ID>4648</ID>
      <LFDNR>32508</LFDNR>
      <ORT>Rostock</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>79065</SNDB_ID>
   </ITEM>
   <ITEM num="59">
      <ID>4859</ID>
      <LFDNR>53</LFDNR>
      <ORT>Göttingen</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77966</SNDB_ID>
   </ITEM>
   <ITEM num="60">
      <ID>4859</ID>
      <LFDNR>54</LFDNR>
      <ORT>Kassel</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78244</SNDB_ID>
   </ITEM>
   <ITEM num="61">
      <ID>4859</ID>
      <LFDNR>55</LFDNR>
      <ORT>Dresden</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77695</SNDB_ID>
   </ITEM>
   <ITEM num="62">
      <ID>5233</ID>
      <LFDNR>56</LFDNR>
      <ORT>Weimar</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>79627</SNDB_ID>
   </ITEM>
   <ITEM num="63">
      <ID>5233</ID>
      <LFDNR>57</LFDNR>
      <ORT>Dresden</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77695</SNDB_ID>
   </ITEM>
   <ITEM num="64">
      <ID>5233</ID>
      <LFDNR>58</LFDNR>
      <ORT>Antwerpen</ORT>
      <ART>Wirkungsort</ART>
   </ITEM>
   <ITEM num="65">
      <ID>5279</ID>
      <LFDNR>59</LFDNR>
      <ORT>Mailand</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78498</SNDB_ID>
   </ITEM>
   <ITEM num="66">
      <ID>5327</ID>
      <LFDNR>60</LFDNR>
      <ORT>Hannover</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78040</SNDB_ID>
   </ITEM>
   <ITEM num="67">
      <ID>5503</ID>
      <LFDNR>61</LFDNR>
      <ORT>Berlin</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77386</SNDB_ID>
   </ITEM>
   <ITEM num="68">
      <ID>5503</ID>
      <LFDNR>62</LFDNR>
      <ORT>Dresden</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77695</SNDB_ID>
   </ITEM>
   <ITEM num="69">
      <ID>5596</ID>
      <LFDNR>63</LFDNR>
      <ORT>Hamburg</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78034</SNDB_ID>
   </ITEM>
   <ITEM num="70">
      <ID>5596</ID>
      <LFDNR>64</LFDNR>
      <ORT>Heidelberg</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78061</SNDB_ID>
   </ITEM>
   <ITEM num="71">
      <ID>5596</ID>
      <LFDNR>65</LFDNR>
      <ORT>Berlin</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77386</SNDB_ID>
   </ITEM>
   <ITEM num="72">
      <ID>5596</ID>
      <LFDNR>66</LFDNR>
      <ORT>Leipzig</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78408</SNDB_ID>
   </ITEM>
   <ITEM num="73">
      <ID>6002</ID>
      <LFDNR>67</LFDNR>
      <ORT>Zürich</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>79740</SNDB_ID>
   </ITEM>
   <ITEM num="74">
      <ID>6005</ID>
      <LFDNR>8716</LFDNR>
      <ORT>Wien</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>79663</SNDB_ID>
   </ITEM>
   <ITEM num="75">
      <ID>6219</ID>
      <LFDNR>108</LFDNR>
      <ORT>Mantua</ORT>
      <ART>Wirkungsort</ART>
   </ITEM>
   <ITEM num="76">
      <ID>6219</ID>
      <LFDNR>109</LFDNR>
      <ORT>Rom</ORT>
      <ART>Wirkungsort</ART>
   </ITEM>
   <ITEM num="77">
      <ID>6223</ID>
      <LFDNR>110</LFDNR>
      <ORT>München</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78649</SNDB_ID>
   </ITEM>
   <ITEM num="78">
      <ID>6223</ID>
      <LFDNR>111</LFDNR>
      <ORT>Berlin</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77386</SNDB_ID>
   </ITEM>
   <ITEM num="79">
      <ID>6371</ID>
      <LFDNR>13001</LFDNR>
      <ORT>Ludwigsburg</ORT>
      <ART>Wirkungsort</ART>
   </ITEM>
   <ITEM num="80">
      <ID>6371</ID>
      <LFDNR>13002</LFDNR>
      <ORT>Stuttgart</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>79399</SNDB_ID>
   </ITEM>
   <ITEM num="81">
      <ID>6371</ID>
      <LFDNR>13003</LFDNR>
      <ORT>Zürich</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>79740</SNDB_ID>
   </ITEM>
   <ITEM num="82">
      <ID>6371</ID>
      <LFDNR>13004</LFDNR>
      <ORT>Bern</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77387</SNDB_ID>
   </ITEM>
   <ITEM num="83">
      <ID>6528</ID>
      <LFDNR>112</LFDNR>
      <ORT>München</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78649</SNDB_ID>
   </ITEM>
   <ITEM num="84">
      <ID>6670</ID>
      <LFDNR>113</LFDNR>
      <ORT>Warschau</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>79614</SNDB_ID>
   </ITEM>
   <ITEM num="85">
      <ID>6670</ID>
      <LFDNR>114</LFDNR>
      <ORT>Berlin</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77386</SNDB_ID>
   </ITEM>
   <ITEM num="86">
      <ID>6782</ID>
      <LFDNR>39785</LFDNR>
      <ORT>Arolsen</ORT>
      <ART>Geburtsort</ART>
      <SNDB_ID>87537</SNDB_ID>
   </ITEM>
   <ITEM num="87">
      <ID>6782</ID>
      <LFDNR>39786</LFDNR>
      <ORT>Berlin</ORT>
      <ART>Sterbeort</ART>
      <SNDB_ID>77386</SNDB_ID>
   </ITEM>
   <ITEM num="88">
      <ID>6784</ID>
      <LFDNR>118</LFDNR>
      <ORT>Paris</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78838</SNDB_ID>
   </ITEM>
   <ITEM num="89">
      <ID>6784</ID>
      <LFDNR>119</LFDNR>
      <ORT>Venedig</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>79565</SNDB_ID>
   </ITEM>
   <ITEM num="90">
      <ID>6784</ID>
      <LFDNR>120</LFDNR>
      <ORT>Rom</ORT>
      <ART>Wirkungsort</ART>
   </ITEM>
   <ITEM num="91">
      <ID>6784</ID>
      <LFDNR>121</LFDNR>
      <ORT>Kassel</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78244</SNDB_ID>
   </ITEM>
   <ITEM num="92">
      <ID>6881</ID>
      <LFDNR>122</LFDNR>
      <ORT>Dresden</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77695</SNDB_ID>
   </ITEM>
   <ITEM num="93">
      <ID>7038</ID>
      <LFDNR>7573</LFDNR>
      <ORT>Dresden</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77695</SNDB_ID>
   </ITEM>
   <ITEM num="94">
      <ID>7038</ID>
      <LFDNR>7574</LFDNR>
      <ORT>St. Petersburg</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78863</SNDB_ID>
   </ITEM>
   <ITEM num="95">
      <ID>7038</ID>
      <LFDNR>7575</LFDNR>
      <ORT>Rom</ORT>
      <ART>Wirkungsort</ART>
   </ITEM>
   <ITEM num="96">
      <ID>7090</ID>
      <LFDNR>115</LFDNR>
      <ORT>Berlin</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77386</SNDB_ID>
   </ITEM>
   <ITEM num="97">
      <ID>7090</ID>
      <LFDNR>116</LFDNR>
      <ORT>Paris</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78838</SNDB_ID>
   </ITEM>
   <ITEM num="98">
      <ID>7090</ID>
      <LFDNR>117</LFDNR>
      <ORT>Rom</ORT>
      <ART>Wirkungsort</ART>
   </ITEM>
   <ITEM num="99">
      <ID>7178</ID>
      <LFDNR>123</LFDNR>
      <ORT>London</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78462</SNDB_ID>
   </ITEM>
   <ITEM num="100">
      <ID>7178</ID>
      <LFDNR>124</LFDNR>
      <ORT>Paris</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78838</SNDB_ID>
   </ITEM>
   <ITEM num="101">
      <ID>7370</ID>
      <LFDNR>351</LFDNR>
      <ORT>München</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78649</SNDB_ID>
   </ITEM>
   <ITEM num="102">
      <ID>7370</ID>
      <LFDNR>352</LFDNR>
      <ORT>Karlsruhe</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78240</SNDB_ID>
   </ITEM>
   <ITEM num="103">
      <ID>7370</ID>
      <LFDNR>353</LFDNR>
      <ORT>Paris</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78838</SNDB_ID>
   </ITEM>
   <ITEM num="104">
      <ID>7409</ID>
      <LFDNR>128</LFDNR>
      <ORT>Berlin</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77386</SNDB_ID>
   </ITEM>
   <ITEM num="105">
      <ID>7409</ID>
      <LFDNR>129</LFDNR>
      <ORT>Rom</ORT>
      <ART>Wirkungsort</ART>
   </ITEM>
   <ITEM num="106">
      <ID>7502</ID>
      <LFDNR>8411</LFDNR>
      <ORT>Hannover</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78040</SNDB_ID>
   </ITEM>
   <ITEM num="107">
      <ID>10858</ID>
      <LFDNR>6539</LFDNR>
      <ORT>Berlin</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77386</SNDB_ID>
   </ITEM>
   <ITEM num="108">
      <ID>10858</ID>
      <LFDNR>6540</LFDNR>
      <ORT>Dresden</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77695</SNDB_ID>
   </ITEM>
   <ITEM num="109">
      <ID>11032</ID>
      <LFDNR>29717</LFDNR>
      <ORT>Bayreuth</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77365</SNDB_ID>
   </ITEM>
   <ITEM num="110">
      <ID>11032</ID>
      <LFDNR>29718</LFDNR>
      <ORT>Darmstadt</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77639</SNDB_ID>
   </ITEM>
   <ITEM num="111">
      <ID>11032</ID>
      <LFDNR>29719</LFDNR>
      <ORT>Wiesbaden</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>79665</SNDB_ID>
   </ITEM>
   <ITEM num="112">
      <ID>11032</ID>
      <LFDNR>29720</LFDNR>
      <ORT>Frankfurt (Main)</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77853</SNDB_ID>
   </ITEM>
   <ITEM num="113">
      <ID>11032</ID>
      <LFDNR>29721</LFDNR>
      <ORT>Dessau</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77650</SNDB_ID>
   </ITEM>
   <ITEM num="114">
      <ID>11043</ID>
      <LFDNR>162</LFDNR>
      <ORT>Berlin</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77386</SNDB_ID>
   </ITEM>
   <ITEM num="115">
      <ID>11085</ID>
      <LFDNR>13</LFDNR>
      <ORT>Weimar</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>79627</SNDB_ID>
   </ITEM>
   <ITEM num="116">
      <ID>11093</ID>
      <LFDNR>14</LFDNR>
      <ORT>St. Petersburg</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78863</SNDB_ID>
   </ITEM>
   <ITEM num="117">
      <ID>11096</ID>
      <LFDNR>15</LFDNR>
      <ORT>Gandersheim</ORT>
      <ART>Wirkungsort</ART>
   </ITEM>
   <ITEM num="118">
      <ID>11103</ID>
      <LFDNR>16</LFDNR>
      <ORT>Weimar</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>79627</SNDB_ID>
   </ITEM>
   <ITEM num="119">
      <ID>11127</ID>
      <LFDNR>9595</LFDNR>
      <ORT>Merseburg</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78567</SNDB_ID>
   </ITEM>
   <ITEM num="120">
      <ID>11136</ID>
      <LFDNR>163</LFDNR>
      <ORT>Celle</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>87365</SNDB_ID>
   </ITEM>
   <ITEM num="121">
      <ID>11136</ID>
      <LFDNR>164</LFDNR>
      <ORT>Berlin</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77386</SNDB_ID>
   </ITEM>
   <ITEM num="122">
      <ID>11136</ID>
      <LFDNR>165</LFDNR>
      <ORT>Halle (Saale)</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78032</SNDB_ID>
   </ITEM>
   <ITEM num="123">
      <ID>11136</ID>
      <LFDNR>33498</LFDNR>
      <ORT>Nettelrede b. Münder (Weserbergland)</ORT>
      <ART>Geburtsort</ART>
   </ITEM>
   <ITEM num="124">
      <ID>11136</ID>
      <LFDNR>33499</LFDNR>
      <ORT>Halle (Saale)</ORT>
      <ART>Sterbeort</ART>
      <SNDB_ID>78032</SNDB_ID>
   </ITEM>
   <ITEM num="125">
      <ID>11159</ID>
      <LFDNR>31474</LFDNR>
      <ORT>Den Haag</ORT>
      <ART>Geburtsort</ART>
   </ITEM>
   <ITEM num="126">
      <ID>11159</ID>
      <LFDNR>31475</LFDNR>
      <ORT>Weimar</ORT>
      <ART>Sterbeort</ART>
      <SNDB_ID>79627</SNDB_ID>
   </ITEM>
   <ITEM num="127">
      <ID>11175</ID>
      <LFDNR>12</LFDNR>
      <ORT>Weimar</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>79627</SNDB_ID>
   </ITEM>
   <ITEM num="128">
      <ID>19271</ID>
      <LFDNR>14369</LFDNR>
      <ORT>Dresden</ORT>
      <ART>Geburtsort</ART>
      <SNDB_ID>77695</SNDB_ID>
   </ITEM>
   <ITEM num="129">
      <ID>19271</ID>
      <LFDNR>17877</LFDNR>
      <ORT>Leipzig</ORT>
      <ART>Sterbeort</ART>
      <SNDB_ID>78408</SNDB_ID>
   </ITEM>
   <ITEM num="130">
      <ID>19271</ID>
      <LFDNR>20314</LFDNR>
      <ORT>Leipzig</ORT>
      <ART>Wohnort</ART>
      <SNDB_ID>78408</SNDB_ID>
   </ITEM>
   <ITEM num="131">
      <ID>19426</ID>
      <LFDNR>13873</LFDNR>
      <ORT>Namslau</ORT>
      <ART>Geburtsort</ART>
      <SNDB_ID>91188</SNDB_ID>
   </ITEM>
   <ITEM num="132">
      <ID>19426</ID>
      <LFDNR>17534</LFDNR>
      <ORT>Berlin</ORT>
      <ART>Sterbeort</ART>
      <SNDB_ID>77386</SNDB_ID>
   </ITEM>
   <ITEM num="133">
      <ID>19443</ID>
      <LFDNR>13880</LFDNR>
      <ORT>Waren (Müritz)</ORT>
      <ART>Geburtsort</ART>
      <SNDB_ID>87958</SNDB_ID>
   </ITEM>
   <ITEM num="134">
      <ID>19443</ID>
      <LFDNR>17541</LFDNR>
      <ORT>Anklam</ORT>
      <ART>Sterbeort</ART>
      <SNDB_ID>87568</SNDB_ID>
   </ITEM>
   <ITEM num="135">
      <ID>19443</ID>
      <LFDNR>41768</LFDNR>
      <ORT>Rostock</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>79065</SNDB_ID>
   </ITEM>
   <ITEM num="136">
      <ID>19443</ID>
      <LFDNR>41769</LFDNR>
      <ORT>Anklam</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>87568</SNDB_ID>
   </ITEM>
   <ITEM num="137">
      <ID>19477</ID>
      <LFDNR>14381</LFDNR>
      <ORT>Hornhausen b. Oschersleben</ORT>
      <ART>Geburtsort</ART>
   </ITEM>
   <ITEM num="138">
      <ID>19477</ID>
      <LFDNR>17884</LFDNR>
      <ORT>Weimar</ORT>
      <ART>Sterbeort</ART>
      <SNDB_ID>79627</SNDB_ID>
   </ITEM>
   <ITEM num="139">
      <ID>19477</ID>
      <LFDNR>20521</LFDNR>
      <ORT>Weimar</ORT>
      <ART>Wohnort</ART>
      <SNDB_ID>79627</SNDB_ID>
   </ITEM>
   <ITEM num="140">
      <ID>19477</ID>
      <LFDNR>41935</LFDNR>
      <ORT>Weimar</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>79627</SNDB_ID>
   </ITEM>
   <ITEM num="141">
      <ID>19579</ID>
      <LFDNR>14729</LFDNR>
      <ORT>Gotha</ORT>
      <ART>Geburtsort</ART>
      <SNDB_ID>77961</SNDB_ID>
   </ITEM>
   <ITEM num="142">
      <ID>19579</ID>
      <LFDNR>18115</LFDNR>
      <ORT>Gotha</ORT>
      <ART>Sterbeort</ART>
      <SNDB_ID>77961</SNDB_ID>
   </ITEM>
   <ITEM num="143">
      <ID>19579</ID>
      <LFDNR>20706</LFDNR>
      <ORT>Gotha</ORT>
      <ART>Wohnort</ART>
      <SNDB_ID>77961</SNDB_ID>
   </ITEM>
   <ITEM num="144">
      <ID>19579</ID>
      <LFDNR>24648</LFDNR>
      <ORT>Jena</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78191</SNDB_ID>
   </ITEM>
   <ITEM num="145">
      <ID>19579</ID>
      <LFDNR>24649</LFDNR>
      <ORT>Coburg</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77599</SNDB_ID>
   </ITEM>
   <ITEM num="146">
      <ID>19579</ID>
      <LFDNR>24650</LFDNR>
      <ORT>Mainz</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>78500</SNDB_ID>
   </ITEM>
   <ITEM num="147">
      <ID>19723</ID>
      <LFDNR>14788</LFDNR>
      <ORT>Wien</ORT>
      <ART>Geburtsort</ART>
      <SNDB_ID>79663</SNDB_ID>
   </ITEM>
   <ITEM num="148">
      <ID>19723</ID>
      <LFDNR>18162</LFDNR>
      <ORT>Wien</ORT>
      <ART>Sterbeort</ART>
      <SNDB_ID>79663</SNDB_ID>
   </ITEM>
   <ITEM num="149">
      <ID>19723</ID>
      <LFDNR>20865</LFDNR>
      <ORT>Wien</ORT>
      <ART>Wohnort</ART>
      <SNDB_ID>79663</SNDB_ID>
   </ITEM>
   <ITEM num="150">
      <ID>19764</ID>
      <LFDNR>14431</LFDNR>
      <ORT>Gaten b. Pegau</ORT>
      <ART>Geburtsort</ART>
   </ITEM>
   <ITEM num="151">
      <ID>19764</ID>
      <LFDNR>17922</LFDNR>
      <ORT>Chemnitz</ORT>
      <ART>Sterbeort</ART>
   </ITEM>
   <ITEM num="152">
      <ID>19764</ID>
      <LFDNR>20908</LFDNR>
      <ORT>Leipzig</ORT>
      <ART>Wohnort</ART>
      <SNDB_ID>78408</SNDB_ID>
   </ITEM>
   <ITEM num="153">
      <ID>19782</ID>
      <LFDNR>14436</LFDNR>
      <ORT>Krefeld</ORT>
      <ART>Geburtsort</ART>
   </ITEM>
   <ITEM num="154">
      <ID>19782</ID>
      <LFDNR>17925</LFDNR>
      <ORT>Stuttgart</ORT>
      <ART>Sterbeort</ART>
      <SNDB_ID>79399</SNDB_ID>
   </ITEM>
   <ITEM num="155">
      <ID>19782</ID>
      <LFDNR>20935</LFDNR>
      <ORT>Stuttgart</ORT>
      <ART>Wohnort</ART>
      <SNDB_ID>79399</SNDB_ID>
   </ITEM>
   <ITEM num="156">
      <ID>19814</ID>
      <LFDNR>14335</LFDNR>
      <ORT>Augsburg</ORT>
      <ART>Geburtsort</ART>
      <SNDB_ID>77314</SNDB_ID>
   </ITEM>
   <ITEM num="157">
      <ID>19814</ID>
      <LFDNR>17848</LFDNR>
      <ORT>Mannheim</ORT>
      <ART>Sterbeort</ART>
      <SNDB_ID>78508</SNDB_ID>
   </ITEM>
   <ITEM num="158">
      <ID>19814</ID>
      <LFDNR>20991</LFDNR>
      <ORT>Mannheim</ORT>
      <ART>Wohnort</ART>
      <SNDB_ID>78508</SNDB_ID>
   </ITEM>
   <ITEM num="159">
      <ID>19833</ID>
      <LFDNR>14344</LFDNR>
      <ORT>Prag</ORT>
      <ART>Geburtsort</ART>
      <SNDB_ID>78941</SNDB_ID>
   </ITEM>
   <ITEM num="160">
      <ID>19833</ID>
      <LFDNR>17855</LFDNR>
      <ORT>Prag</ORT>
      <ART>Sterbeort</ART>
      <SNDB_ID>78941</SNDB_ID>
   </ITEM>
   <ITEM num="161">
      <ID>20338</ID>
      <LFDNR>17554</LFDNR>
      <ORT>Weimar</ORT>
      <ART>Sterbeort</ART>
      <SNDB_ID>79627</SNDB_ID>
   </ITEM>
   <ITEM num="162">
      <ID>20370</ID>
      <LFDNR>13904</LFDNR>
      <ORT>Stuttgart</ORT>
      <ART>Geburtsort</ART>
      <SNDB_ID>79399</SNDB_ID>
   </ITEM>
   <ITEM num="163">
      <ID>20370</ID>
      <LFDNR>17562</LFDNR>
      <ORT>Stuttgart</ORT>
      <ART>Sterbeort</ART>
      <SNDB_ID>79399</SNDB_ID>
   </ITEM>
   <ITEM num="164">
      <ID>20370</ID>
      <LFDNR>21573</LFDNR>
      <ORT>Stuttgart</ORT>
      <ART>Wohnort</ART>
      <SNDB_ID>79399</SNDB_ID>
   </ITEM>
   <ITEM num="165">
      <ID>20510</ID>
      <LFDNR>13921</LFDNR>
      <ORT>Breslau</ORT>
      <ART>Geburtsort</ART>
      <SNDB_ID>77485</SNDB_ID>
   </ITEM>
   <ITEM num="166">
      <ID>20510</ID>
      <LFDNR>17572</LFDNR>
      <ORT>Breslau</ORT>
      <ART>Sterbeort</ART>
      <SNDB_ID>77485</SNDB_ID>
   </ITEM>
   <ITEM num="167">
      <ID>20510</ID>
      <LFDNR>21761</LFDNR>
      <ORT>Brieg</ORT>
      <ART>Wohnort</ART>
   </ITEM>
   <ITEM num="168">
      <ID>20510</ID>
      <LFDNR>21762</LFDNR>
      <ORT>Breslau</ORT>
      <ART>Wohnort</ART>
      <SNDB_ID>77485</SNDB_ID>
   </ITEM>
   <ITEM num="169">
      <ID>20869</ID>
      <LFDNR>14248</LFDNR>
      <ORT>Reutlingen</ORT>
      <ART>Geburtsort</ART>
   </ITEM>
   <ITEM num="170">
      <ID>20869</ID>
      <LFDNR>17785</LFDNR>
      <ORT>Tübingen</ORT>
      <ART>Sterbeort</ART>
      <SNDB_ID>79519</SNDB_ID>
   </ITEM>
   <ITEM num="171">
      <ID>20869</ID>
      <LFDNR>22219</LFDNR>
      <ORT>Eßlingen (Neckar)</ORT>
      <ART>Wohnort</ART>
   </ITEM>
   <ITEM num="172">
      <ID>20869</ID>
      <LFDNR>22220</LFDNR>
      <ORT>Tübingen</ORT>
      <ART>Wohnort</ART>
      <SNDB_ID>79519</SNDB_ID>
   </ITEM>
   <ITEM num="173">
      <ID>21044</ID>
      <LFDNR>14326</LFDNR>
      <ORT>Raiding</ORT>
      <ART>Geburtsort</ART>
   </ITEM>
   <ITEM num="174">
      <ID>21044</ID>
      <LFDNR>17839</LFDNR>
      <ORT>Bayreuth</ORT>
      <ART>Sterbeort</ART>
      <SNDB_ID>77365</SNDB_ID>
   </ITEM>
   <ITEM num="175">
      <ID>21114</ID>
      <LFDNR>15055</LFDNR>
      <ORT>Berlin</ORT>
      <ART>Geburtsort</ART>
      <SNDB_ID>77386</SNDB_ID>
   </ITEM>
   <ITEM num="176">
      <ID>21114</ID>
      <LFDNR>18338</LFDNR>
      <ORT>Berlin</ORT>
      <ART>Sterbeort</ART>
      <SNDB_ID>77386</SNDB_ID>
   </ITEM>
   <ITEM num="177">
      <ID>21114</ID>
      <LFDNR>41558</LFDNR>
      <ORT>Berlin</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>77386</SNDB_ID>
   </ITEM>
   <ITEM num="178">
      <ID>21114</ID>
      <LFDNR>41559</LFDNR>
      <ORT>Weimar</ORT>
      <ART>Wirkungsort</ART>
      <SNDB_ID>79627</SNDB_ID>
   </ITEM>
   <ITEM num="179">
      <ID>21140</ID>
      <LFDNR>15222</LFDNR>
      <ORT>Bremen</ORT>
      <ART>Geburtsort</ART>
      <SNDB_ID>77479</SNDB_ID>
   </ITEM>
   <ITEM num="180">
      <ID>21140</ID>
      <LFDNR>22408</LFDNR>
      <ORT>Leipzig</ORT>
      <ART>Wohnort</ART>
      <SNDB_ID>78408</SNDB_ID>
   </ITEM>
   <ITEM num="181">
      <ID>21199</ID>
      <LFDNR>15253</LFDNR>
      <ORT>Ehringen b. Nördlingen</ORT>
      <ART>Geburtsort</ART>
   </ITEM>
   <ITEM num="182">
      <ID>21199</ID>
      <LFDNR>18468</LFDNR>
      <ORT>München</ORT>
      <ART>Sterbeort</ART>
      <SNDB_ID>78649</SNDB_ID>
   </ITEM>
   <ITEM num="183">
      <ID>21199</ID>
      <LFDNR>21440</LFDNR>
      <ORT>München</ORT>
      <ART>Wohnort</ART>
      <SNDB_ID>78649</SNDB_ID>
   </ITEM>
   <ITEM num="184">
      <ID>21283</ID>
      <LFDNR>15297</LFDNR>
      <ORT>Neubrandenburg</ORT>
      <ART>Geburtsort</ART>
      <SNDB_ID>87358</SNDB_ID>
   </ITEM>
   <ITEM num="185">
      <ID>21283</ID>
      <LFDNR>18498</LFDNR>
      <ORT>Berlin</ORT>
      <ART>Sterbeort</ART>
      <SNDB_ID>77386</SNDB_ID>
   </ITEM>
   <ITEM num="186">
      <ID>21378</ID>
      <LFDNR>15118</LFDNR>
      <ORT>Ludwigsburg</ORT>
      <ART>Geburtsort</ART>
   </ITEM>
   <ITEM num="187">
      <ID>21378</ID>
      <LFDNR>18385</LFDNR>
      <ORT>Stuttgart</ORT>
      <ART>Sterbeort</ART>
      <SNDB_ID>79399</SNDB_ID>
   </ITEM>
   <ITEM num="188">
      <ID>21378</ID>
      <LFDNR>22696</LFDNR>
      <ORT>Stuttgart</ORT>
      <ART>Wohnort</ART>
      <SNDB_ID>79399</SNDB_ID>
   </ITEM>
   <ITEM num="189">
      <ID>21394</ID>
      <LFDNR>22713</LFDNR>
      <ORT>Ansbach</ORT>
      <ART>Wohnort</ART>