<?xml version = "1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE NDB_BERUFE [
<!ELEMENT NDB_BERUFE (ITEM)*>
<!ELEMENT ITEM (ID, LFDNR, BERUF?, BERUF2?)>
<!ATTLIST ITEM num CDATA #REQUIRED>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT LFDNR (#PCDATA)>
<!ELEMENT BERUF (#PCDATA)>
<!ELEMENT BERUF2 (#PCDATA)>
]>
<NDB_BERUFE>
   <ITEM num="1">
      <ID>71</ID>
      <LFDNR>240</LFDNR>
      <BERUF>Stecher</BERUF>
   </ITEM>
   <ITEM num="2">
      <ID>71</ID>
      <LFDNR>241</LFDNR>
      <BERUF>Zeichner</BERUF>
   </ITEM>
   <ITEM num="3">
      <ID>249</ID>
      <LFDNR>243</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="4">
      <ID>249</ID>
      <LFDNR>244</LFDNR>
      <BERUF>Radierer</BERUF>
   </ITEM>
   <ITEM num="5">
      <ID>391</ID>
      <LFDNR>246</LFDNR>
      <BERUF>Zeichner</BERUF>
   </ITEM>
   <ITEM num="6">
      <ID>391</ID>
      <LFDNR>247</LFDNR>
      <BERUF>Kupferstecher</BERUF>
   </ITEM>
   <ITEM num="7">
      <ID>492</ID>
      <LFDNR>26167</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="8">
      <ID>492</ID>
      <LFDNR>26168</LFDNR>
      <BERUF>Professor an der Akademie der Künste</BERUF>
   </ITEM>
   <ITEM num="9">
      <ID>762</ID>
      <LFDNR>254</LFDNR>
      <BERUF>Mechaniker</BERUF>
   </ITEM>
   <ITEM num="10">
      <ID>927</ID>
      <LFDNR>264</LFDNR>
      <BERUF>Offizier</BERUF>
   </ITEM>
   <ITEM num="11">
      <ID>1492</ID>
      <LFDNR>20534</LFDNR>
      <BERUF>Porträtmaler</BERUF>
   </ITEM>
   <ITEM num="12">
      <ID>1492</ID>
      <LFDNR>20535</LFDNR>
      <BERUF>Professor</BERUF>
   </ITEM>
   <ITEM num="13">
      <ID>1502</ID>
      <LFDNR>57</LFDNR>
      <BERUF>Bildhauer</BERUF>
   </ITEM>
   <ITEM num="14">
      <ID>1537</ID>
      <LFDNR>58</LFDNR>
      <BERUF>Lithograph</BERUF>
   </ITEM>
   <ITEM num="15">
      <ID>1874</ID>
      <LFDNR>285</LFDNR>
      <BERUF>Zeichner</BERUF>
   </ITEM>
   <ITEM num="16">
      <ID>1874</ID>
      <LFDNR>286</LFDNR>
      <BERUF>Kupferstecher</BERUF>
   </ITEM>
   <ITEM num="17">
      <ID>1906</ID>
      <LFDNR>288</LFDNR>
      <BERUF>Stempelschneiderin</BERUF>
   </ITEM>
   <ITEM num="18">
      <ID>1906</ID>
      <LFDNR>289</LFDNR>
      <BERUF>Gemmenschneiderin</BERUF>
   </ITEM>
   <ITEM num="19">
      <ID>1906</ID>
      <LFDNR>290</LFDNR>
      <BERUF>Bildhauerin</BERUF>
   </ITEM>
   <ITEM num="20">
      <ID>2004</ID>
      <LFDNR>296</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="21">
      <ID>2004</ID>
      <LFDNR>297</LFDNR>
      <BERUF>Lithograph</BERUF>
   </ITEM>
   <ITEM num="22">
      <ID>2008</ID>
      <LFDNR>298</LFDNR>
      <BERUF>Bildhauer</BERUF>
   </ITEM>
   <ITEM num="23">
      <ID>2019</ID>
      <LFDNR>300</LFDNR>
      <BERUF>Stecher</BERUF>
   </ITEM>
   <ITEM num="24">
      <ID>2054</ID>
      <LFDNR>193</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="25">
      <ID>2054</ID>
      <LFDNR>194</LFDNR>
      <BERUF>Kunsthistoriker</BERUF>
   </ITEM>
   <ITEM num="26">
      <ID>2054</ID>
      <LFDNR>37435</LFDNR>
      <BERUF>Publizist</BERUF>
   </ITEM>
   <ITEM num="27">
      <ID>2162</ID>
      <LFDNR>306</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="28">
      <ID>2162</ID>
      <LFDNR>307</LFDNR>
      <BERUF>Zeichner</BERUF>
   </ITEM>
   <ITEM num="29">
      <ID>2162</ID>
      <LFDNR>308</LFDNR>
      <BERUF>Lithograph</BERUF>
   </ITEM>
   <ITEM num="30">
      <ID>2189</ID>
      <LFDNR>41627</LFDNR>
      <BERUF>Mediziner</BERUF>
   </ITEM>
   <ITEM num="31">
      <ID>2189</ID>
      <LFDNR>41628</LFDNR>
      <BERUF>Verleger</BERUF>
   </ITEM>
   <ITEM num="32">
      <ID>2318</ID>
      <LFDNR>312</LFDNR>
      <BERUF>Kupferstecher</BERUF>
   </ITEM>
   <ITEM num="33">
      <ID>2318</ID>
      <LFDNR>313</LFDNR>
      <BERUF>Illustrator</BERUF>
   </ITEM>
   <ITEM num="34">
      <ID>2390</ID>
      <LFDNR>314</LFDNR>
      <BERUF>Kupferstecher</BERUF>
   </ITEM>
   <ITEM num="35">
      <ID>2390</ID>
      <LFDNR>315</LFDNR>
      <BERUF>Radierer</BERUF>
   </ITEM>
   <ITEM num="36">
      <ID>2390</ID>
      <LFDNR>316</LFDNR>
      <BERUF>Miniaturmaler</BERUF>
   </ITEM>
   <ITEM num="37">
      <ID>2390</ID>
      <LFDNR>317</LFDNR>
      <BERUF>Illustrator</BERUF>
   </ITEM>
   <ITEM num="38">
      <ID>2475</ID>
      <LFDNR>38744</LFDNR>
      <BERUF>Schriftsteller</BERUF>
   </ITEM>
   <ITEM num="39">
      <ID>2475</ID>
      <LFDNR>38745</LFDNR>
      <BERUF>Jurist</BERUF>
   </ITEM>
   <ITEM num="40">
      <ID>2475</ID>
      <LFDNR>38746</LFDNR>
      <BERUF>Beamter</BERUF>
   </ITEM>
   <ITEM num="41">
      <ID>2475</ID>
      <LFDNR>38747</LFDNR>
      <BERUF>Naturforscher</BERUF>
   </ITEM>
   <ITEM num="42">
      <ID>2645</ID>
      <LFDNR>318</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="43">
      <ID>2682</ID>
      <LFDNR>319</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="44">
      <ID>2682</ID>
      <LFDNR>38158</LFDNR>
      <BERUF>Pfarrer</BERUF>
   </ITEM>
   <ITEM num="45">
      <ID>2832</ID>
      <LFDNR>35904</LFDNR>
      <BERUF>Porträtmaler</BERUF>
   </ITEM>
   <ITEM num="46">
      <ID>2931</ID>
      <LFDNR>321</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="47">
      <ID>2931</ID>
      <LFDNR>322</LFDNR>
      <BERUF>Kupferstecher</BERUF>
   </ITEM>
   <ITEM num="48">
      <ID>2931</ID>
      <LFDNR>323</LFDNR>
      <BERUF>Lithograph</BERUF>
   </ITEM>
   <ITEM num="49">
      <ID>2932</ID>
      <LFDNR>324</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="50">
      <ID>2932</ID>
      <LFDNR>325</LFDNR>
      <BERUF>Kupferstecher</BERUF>
   </ITEM>
   <ITEM num="51">
      <ID>2932</ID>
      <LFDNR>326</LFDNR>
      <BERUF>Lithograph</BERUF>
   </ITEM>
   <ITEM num="52">
      <ID>3082</ID>
      <LFDNR>327</LFDNR>
      <BERUF>Zeichner</BERUF>
   </ITEM>
   <ITEM num="53">
      <ID>3082</ID>
      <LFDNR>328</LFDNR>
      <BERUF>Kupferstecher</BERUF>
   </ITEM>
   <ITEM num="54">
      <ID>3190</ID>
      <LFDNR>330</LFDNR>
      <BERUF>Bildhauer</BERUF>
   </ITEM>
   <ITEM num="55">
      <ID>3190</ID>
      <LFDNR>331</LFDNR>
      <BERUF>Zeichner</BERUF>
   </ITEM>
   <ITEM num="56">
      <ID>3198</ID>
      <LFDNR>1</LFDNR>
      <BERUF>Bildhauer</BERUF>
   </ITEM>
   <ITEM num="57">
      <ID>3251</ID>
      <LFDNR>5</LFDNR>
      <BERUF>Miniaturmalerin</BERUF>
   </ITEM>
   <ITEM num="58">
      <ID>3251</ID>
      <LFDNR>6</LFDNR>
      <BERUF>Radiererin</BERUF>
   </ITEM>
   <ITEM num="59">
      <ID>3251</ID>
      <LFDNR>7</LFDNR>
      <BERUF>Stecherin</BERUF>
   </ITEM>
   <ITEM num="60">
      <ID>3267</ID>
      <LFDNR>8</LFDNR>
      <BERUF>Offizier</BERUF>
   </ITEM>
   <ITEM num="61">
      <ID>3267</ID>
      <LFDNR>9</LFDNR>
      <BERUF>Miniaturenporträtist</BERUF>
   </ITEM>
   <ITEM num="62">
      <ID>3291</ID>
      <LFDNR>10</LFDNR>
      <BERUF>Medailleur</BERUF>
   </ITEM>
   <ITEM num="63">
      <ID>3291</ID>
      <LFDNR>11</LFDNR>
      <BERUF>Bildhauer</BERUF>
   </ITEM>
   <ITEM num="64">
      <ID>3291</ID>
      <LFDNR>12</LFDNR>
      <BERUF>Edelsteinschneider</BERUF>
   </ITEM>
   <ITEM num="65">
      <ID>3362</ID>
      <LFDNR>16</LFDNR>
      <BERUF>Kupferstecher</BERUF>
   </ITEM>
   <ITEM num="66">
      <ID>3420</ID>
      <LFDNR>23</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="67">
      <ID>3420</ID>
      <LFDNR>47952</LFDNR>
      <BERUF>Zeichner</BERUF>
   </ITEM>
   <ITEM num="68">
      <ID>3562</ID>
      <LFDNR>206</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="69">
      <ID>3562</ID>
      <LFDNR>207</LFDNR>
      <BERUF>Musiker</BERUF>
   </ITEM>
   <ITEM num="70">
      <ID>3595</ID>
      <LFDNR>29</LFDNR>
      <BERUF>Kupferstecher</BERUF>
   </ITEM>
   <ITEM num="71">
      <ID>3595</ID>
      <LFDNR>30</LFDNR>
      <BERUF>Kartograf</BERUF>
   </ITEM>
   <ITEM num="72">
      <ID>3703</ID>
      <LFDNR>39159</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="73">
      <ID>3704</ID>
      <LFDNR>35</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="74">
      <ID>3704</ID>
      <LFDNR>39160</LFDNR>
      <BERUF>Kupferstecher</BERUF>
   </ITEM>
   <ITEM num="75">
      <ID>3917</ID>
      <LFDNR>42</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="76">
      <ID>3917</ID>
      <LFDNR>43</LFDNR>
      <BERUF>Kupferstecher</BERUF>
   </ITEM>
   <ITEM num="77">
      <ID>3917</ID>
      <LFDNR>45</LFDNR>
      <BERUF>Lithograph</BERUF>
   </ITEM>
   <ITEM num="78">
      <ID>3924</ID>
      <LFDNR>28863</LFDNR>
      <BERUF>Bildhauer</BERUF>
   </ITEM>
   <ITEM num="79">
      <ID>3933</ID>
      <LFDNR>36782</LFDNR>
      <BERUF>Diplomat</BERUF>
   </ITEM>
   <ITEM num="80">
      <ID>3933</ID>
      <LFDNR>36783</LFDNR>
      <BERUF>Kammerherr</BERUF>
   </ITEM>
   <ITEM num="81">
      <ID>3933</ID>
      <LFDNR>36784</LFDNR>
      <BERUF>Schriftsteller</BERUF>
   </ITEM>
   <ITEM num="82">
      <ID>3966</ID>
      <LFDNR>46</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="83">
      <ID>3966</ID>
      <LFDNR>47</LFDNR>
      <BERUF>Grafiker</BERUF>
   </ITEM>
   <ITEM num="84">
      <ID>3966</ID>
      <LFDNR>48</LFDNR>
      <BERUF>Kupferstecher</BERUF>
   </ITEM>
   <ITEM num="85">
      <ID>3966</ID>
      <LFDNR>49</LFDNR>
      <BERUF>Lithograf</BERUF>
   </ITEM>
   <ITEM num="86">
      <ID>4042</ID>
      <LFDNR>39371</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="87">
      <ID>4042</ID>
      <LFDNR>39372</LFDNR>
      <BERUF>Zeichner</BERUF>
   </ITEM>
   <ITEM num="88">
      <ID>4105</ID>
      <LFDNR>88</LFDNR>
      <BERUF>Miniaturist</BERUF>
   </ITEM>
   <ITEM num="89">
      <ID>4105</ID>
      <LFDNR>89</LFDNR>
      <BERUF>Kupferstecher</BERUF>
   </ITEM>
   <ITEM num="90">
      <ID>4275</ID>
      <LFDNR>90</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="91">
      <ID>4330</ID>
      <LFDNR>91</LFDNR>
      <BERUF>Porträtmaler</BERUF>
   </ITEM>
   <ITEM num="92">
      <ID>4333</ID>
      <LFDNR>92</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="93">
      <ID>4333</ID>
      <LFDNR>93</LFDNR>
      <BERUF>Stecher</BERUF>
   </ITEM>
   <ITEM num="94">
      <ID>4333</ID>
      <LFDNR>94</LFDNR>
      <BERUF>Verleger</BERUF>
   </ITEM>
   <ITEM num="95">
      <ID>4526</ID>
      <LFDNR>22008</LFDNR>
      <BERUF>Zeichner</BERUF>
   </ITEM>
   <ITEM num="96">
      <ID>4526</ID>
      <LFDNR>22009</LFDNR>
      <BERUF>Kupferstecher</BERUF>
   </ITEM>
   <ITEM num="97">
      <ID>4648</ID>
      <LFDNR>101</LFDNR>
      <BERUF>Theologe</BERUF>
   </ITEM>
   <ITEM num="98">
      <ID>4648</ID>
      <LFDNR>102</LFDNR>
      <BERUF>Liederdichter</BERUF>
   </ITEM>
   <ITEM num="99">
      <ID>4648</ID>
      <LFDNR>39684</LFDNR>
      <BERUF>Philologe</BERUF>
   </ITEM>
   <ITEM num="100">
      <ID>4648</ID>
      <LFDNR>39685</LFDNR>
      <BERUF>Komponist</BERUF>
   </ITEM>
   <ITEM num="101">
      <ID>4859</ID>
      <LFDNR>168</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="102">
      <ID>4859</ID>
      <LFDNR>169</LFDNR>
      <BERUF>Kunsthistoriker</BERUF>
   </ITEM>
   <ITEM num="103">
      <ID>5233</ID>
      <LFDNR>181</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="104">
      <ID>5233</ID>
      <LFDNR>182</LFDNR>
      <BERUF>Zeichner</BERUF>
   </ITEM>
   <ITEM num="105">
      <ID>5279</ID>
      <LFDNR>183</LFDNR>
      <BERUF>Medailleur</BERUF>
   </ITEM>
   <ITEM num="106">
      <ID>5279</ID>
      <LFDNR>184</LFDNR>
      <BERUF>Bildhauer</BERUF>
   </ITEM>
   <ITEM num="107">
      <ID>5279</ID>
      <LFDNR>185</LFDNR>
      <BERUF>Stahlstecher</BERUF>
   </ITEM>
   <ITEM num="108">
      <ID>5327</ID>
      <LFDNR>186</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="109">
      <ID>5327</ID>
      <LFDNR>187</LFDNR>
      <BERUF>Zeichner</BERUF>
   </ITEM>
   <ITEM num="110">
      <ID>5327</ID>
      <LFDNR>188</LFDNR>
      <BERUF>Radierer</BERUF>
   </ITEM>
   <ITEM num="111">
      <ID>5503</ID>
      <LFDNR>198</LFDNR>
      <BERUF>Bildhauer</BERUF>
   </ITEM>
   <ITEM num="112">
      <ID>5596</ID>
      <LFDNR>199</LFDNR>
      <BERUF>Kupferstecher</BERUF>
   </ITEM>
   <ITEM num="113">
      <ID>5596</ID>
      <LFDNR>200</LFDNR>
      <BERUF>Stahlstecher</BERUF>
   </ITEM>
   <ITEM num="114">
      <ID>6002</ID>
      <LFDNR>208</LFDNR>
      <BERUF>Zeichner</BERUF>
   </ITEM>
   <ITEM num="115">
      <ID>6002</ID>
      <LFDNR>209</LFDNR>
      <BERUF>Kupferstecher</BERUF>
   </ITEM>
   <ITEM num="116">
      <ID>6005</ID>
      <LFDNR>24308</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="117">
      <ID>6005</ID>
      <LFDNR>24309</LFDNR>
      <BERUF>Kupferstecher</BERUF>
   </ITEM>
   <ITEM num="118">
      <ID>6080</ID>
      <LFDNR>388</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="119">
      <ID>6219</ID>
      <LFDNR>392</LFDNR>
      <BERUF>Stecherin</BERUF>
   </ITEM>
   <ITEM num="120">
      <ID>6219</ID>
      <LFDNR>48505</LFDNR>
      <BERUF>Kupferstecherin</BERUF>
   </ITEM>
   <ITEM num="121">
      <ID>6223</ID>
      <LFDNR>393</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="122">
      <ID>6223</ID>
      <LFDNR>394</LFDNR>
      <BERUF>Porzellanmaler</BERUF>
   </ITEM>
   <ITEM num="123">
      <ID>6371</ID>
      <LFDNR>30637</LFDNR>
      <BERUF>Bildhauer</BERUF>
   </ITEM>
   <ITEM num="124">
      <ID>6371</ID>
      <LFDNR>30638</LFDNR>
      <BERUF>Stukkateur</BERUF>
   </ITEM>
   <ITEM num="125">
      <ID>6371</ID>
      <LFDNR>30639</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="126">
      <ID>6528</ID>
      <LFDNR>395</LFDNR>
      <BERUF>Hofmaler</BERUF>
   </ITEM>
   <ITEM num="127">
      <ID>6670</ID>
      <LFDNR>408</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="128">
      <ID>6782</ID>
      <LFDNR>48876</LFDNR>
      <BERUF>Malerin</BERUF>
   </ITEM>
   <ITEM num="129">
      <ID>6782</ID>
      <LFDNR>48877</LFDNR>
      <BERUF>Zeichnerin</BERUF>
   </ITEM>
   <ITEM num="130">
      <ID>6784</ID>
      <LFDNR>414</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="131">
      <ID>6784</ID>
      <LFDNR>415</LFDNR>
      <BERUF>Radierer</BERUF>
   </ITEM>
   <ITEM num="132">
      <ID>6881</ID>
      <LFDNR>416</LFDNR>
      <BERUF>Kupferstecher</BERUF>
   </ITEM>
   <ITEM num="133">
      <ID>7038</ID>
      <LFDNR>22626</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="134">
      <ID>7090</ID>
      <LFDNR>413</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="135">
      <ID>7178</ID>
      <LFDNR>417</LFDNR>
      <BERUF>Kupferstecher</BERUF>
   </ITEM>
   <ITEM num="136">
      <ID>7178</ID>
      <LFDNR>418</LFDNR>
      <BERUF>Grafiker</BERUF>
   </ITEM>
   <ITEM num="137">
      <ID>7370</ID>
      <LFDNR>1101</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="138">
      <ID>7370</ID>
      <LFDNR>1102</LFDNR>
      <BERUF>Lithograph</BERUF>
   </ITEM>
   <ITEM num="139">
      <ID>7409</ID>
      <LFDNR>428</LFDNR>
      <BERUF>Bildhauer</BERUF>
   </ITEM>
   <ITEM num="140">
      <ID>7502</ID>
      <LFDNR>23912</LFDNR>
      <BERUF>Porträtist</BERUF>
   </ITEM>
   <ITEM num="141">
      <ID>7663</ID>
      <LFDNR>496</LFDNR>
      <BERUF>Radierer</BERUF>
   </ITEM>
   <ITEM num="142">
      <ID>7663</ID>
      <LFDNR>497</LFDNR>
      <BERUF>Kupferstecher</BERUF>
   </ITEM>
   <ITEM num="143">
      <ID>7663</ID>
      <LFDNR>498</LFDNR>
      <BERUF>Verleger</BERUF>
   </ITEM>
   <ITEM num="144">
      <ID>10858</ID>
      <LFDNR>20533</LFDNR>
      <BERUF>Kunsthändler</BERUF>
   </ITEM>
   <ITEM num="145">
      <ID>11032</ID>
      <LFDNR>518</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="146">
      <ID>11032</ID>
      <LFDNR>519</LFDNR>
      <BERUF>Radierer</BERUF>
   </ITEM>
   <ITEM num="147">
      <ID>11085</ID>
      <LFDNR>81</LFDNR>
      <BERUF>Herzog von Sachsen-Weimar</BERUF>
      <BERUF2>und Eisenach</BERUF2>
   </ITEM>
   <ITEM num="148">
      <ID>11096</ID>
      <LFDNR>82</LFDNR>
      <BERUF>Dekanin</BERUF>
   </ITEM>
   <ITEM num="149">
      <ID>11127</ID>
      <LFDNR>25894</LFDNR>
      <BERUF>Kameralist</BERUF>
   </ITEM>
   <ITEM num="150">
      <ID>11127</ID>
      <LFDNR>25895</LFDNR>
      <BERUF>Jurist</BERUF>
   </ITEM>
   <ITEM num="151">
      <ID>11127</ID>
      <LFDNR>25896</LFDNR>
      <BERUF>Naturwissenschaftler</BERUF>
   </ITEM>
   <ITEM num="152">
      <ID>11127</ID>
      <LFDNR>25897</LFDNR>
      <BERUF>Schriftsteller</BERUF>
   </ITEM>
   <ITEM num="153">
      <ID>11136</ID>
      <LFDNR>522</LFDNR>
      <BERUF>Sprachwissenschaftler</BERUF>
   </ITEM>
   <ITEM num="154">
      <ID>11143</ID>
      <LFDNR>59</LFDNR>
      <BERUF>Herzog von Sachsen</BERUF>
   </ITEM>
   <ITEM num="155">
      <ID>11144</ID>
      <LFDNR>60</LFDNR>
      <BERUF>Herzog von Sachsen-Weimar</BERUF>
   </ITEM>
   <ITEM num="156">
      <ID>11156</ID>
      <LFDNR>61</LFDNR>
      <BERUF>Herzog</BERUF>
   </ITEM>
   <ITEM num="157">
      <ID>11159</ID>
      <LFDNR>39194</LFDNR>
      <BERUF>Großherzogin</BERUF>
   </ITEM>
   <ITEM num="158">
      <ID>11160</ID>
      <LFDNR>62</LFDNR>
      <BERUF>Legationsrat</BERUF>
   </ITEM>
   <ITEM num="159">
      <ID>11160</ID>
      <LFDNR>63</LFDNR>
      <BERUF>Geheimer Referendar</BERUF>
   </ITEM>
   <ITEM num="160">
      <ID>11175</ID>
      <LFDNR>66</LFDNR>
      <BERUF>Herzog von Sachsen-Weimar</BERUF>
   </ITEM>
   <ITEM num="161">
      <ID>19271</ID>
      <LFDNR>670</LFDNR>
      <BERUF>Philosoph</BERUF>
   </ITEM>
   <ITEM num="162">
      <ID>19271</ID>
      <LFDNR>671</LFDNR>
      <BERUF>Schriftsteller</BERUF>
   </ITEM>
   <ITEM num="163">
      <ID>19443</ID>
      <LFDNR>50415</LFDNR>
      <BERUF>Schriftstellerin</BERUF>
   </ITEM>
   <ITEM num="164">
      <ID>19477</ID>
      <LFDNR>36468</LFDNR>
      <BERUF>Schriftsteller</BERUF>
   </ITEM>
   <ITEM num="165">
      <ID>19477</ID>
      <LFDNR>36469</LFDNR>
      <BERUF>Lehrer</BERUF>
   </ITEM>
   <ITEM num="166">
      <ID>19579</ID>
      <LFDNR>32159</LFDNR>
      <BERUF>Schriftsteller</BERUF>
   </ITEM>
   <ITEM num="167">
      <ID>19579</ID>
      <LFDNR>32160</LFDNR>
      <BERUF>Archivar</BERUF>
   </ITEM>
   <ITEM num="168">
      <ID>19579</ID>
      <LFDNR>32161</LFDNR>
      <BERUF>Erzieher</BERUF>
   </ITEM>
   <ITEM num="169">
      <ID>20338</ID>
      <LFDNR>49766</LFDNR>
      <BERUF>Geograph</BERUF>
   </ITEM>
   <ITEM num="170">
      <ID>20338</ID>
      <LFDNR>49767</LFDNR>
      <BERUF>Statistiker</BERUF>
   </ITEM>
   <ITEM num="171">
      <ID>21044</ID>
      <LFDNR>654</LFDNR>
      <BERUF>Pianist</BERUF>
   </ITEM>
   <ITEM num="172">
      <ID>21044</ID>
      <LFDNR>655</LFDNR>
      <BERUF>Komponist</BERUF>
   </ITEM>
   <ITEM num="173">
      <ID>21044</ID>
      <LFDNR>656</LFDNR>
      <BERUF>Dirigent</BERUF>
   </ITEM>
   <ITEM num="174">
      <ID>21394</ID>
      <LFDNR>1106</LFDNR>
      <BERUF>Theologe</BERUF>
   </ITEM>
   <ITEM num="175">
      <ID>21394</ID>
      <LFDNR>1107</LFDNR>
      <BERUF>Philologe</BERUF>
   </ITEM>
   <ITEM num="176">
      <ID>21554</ID>
      <LFDNR>1095</LFDNR>
      <BERUF>Schriftsteller</BERUF>
   </ITEM>
   <ITEM num="177">
      <ID>21554</ID>
      <LFDNR>32765</LFDNR>
      <BERUF>Buchhändler</BERUF>
   </ITEM>
   <ITEM num="178">
      <ID>21791</ID>
      <LFDNR>728</LFDNR>
      <BERUF>Schriftsteller</BERUF>
   </ITEM>
   <ITEM num="179">
      <ID>21791</ID>
      <LFDNR>729</LFDNR>
      <BERUF>Journalist</BERUF>
   </ITEM>
   <ITEM num="180">
      <ID>21911</ID>
      <LFDNR>25354</LFDNR>
      <BERUF>Schriftsteller</BERUF>
   </ITEM>
   <ITEM num="181">
      <ID>21911</ID>
      <LFDNR>25355</LFDNR>
      <BERUF>Domkommissar</BERUF>
   </ITEM>
   <ITEM num="182">
      <ID>21952</ID>
      <LFDNR>30384</LFDNR>
      <BERUF>Schriftsteller</BERUF>
   </ITEM>
   <ITEM num="183">
      <ID>21952</ID>
      <LFDNR>30385</LFDNR>
      <BERUF>Schauspieler</BERUF>
   </ITEM>
   <ITEM num="184">
      <ID>21952</ID>
      <LFDNR>30386</LFDNR>
      <BERUF>Erzieher</BERUF>
   </ITEM>
   <ITEM num="185">
      <ID>21952</ID>
      <LFDNR>30387</LFDNR>
      <BERUF>Gutsverwalter</BERUF>
   </ITEM>
   <ITEM num="186">
      <ID>21994</ID>
      <LFDNR>834</LFDNR>
      <BERUF>Schauspielerin</BERUF>
   </ITEM>
   <ITEM num="187">
      <ID>21994</ID>
      <LFDNR>835</LFDNR>
      <BERUF>Sängerin</BERUF>
   </ITEM>
   <ITEM num="188">
      <ID>22069</ID>
      <LFDNR>41651</LFDNR>
      <BERUF>Archäologe</BERUF>
   </ITEM>
   <ITEM num="189">
      <ID>22069</ID>
      <LFDNR>41652</LFDNR>
      <BERUF>Bibliothekar</BERUF>
   </ITEM>
   <ITEM num="190">
      <ID>22069</ID>
      <LFDNR>41653</LFDNR>
      <BERUF>Philologe</BERUF>
   </ITEM>
   <ITEM num="191">
      <ID>22069</ID>
      <LFDNR>41654</LFDNR>
      <BERUF>Literaturhistoriker</BERUF>
   </ITEM>
   <ITEM num="192">
      <ID>22147</ID>
      <LFDNR>26128</LFDNR>
      <BERUF>Schriftsteller</BERUF>
   </ITEM>
   <ITEM num="193">
      <ID>22147</ID>
      <LFDNR>26129</LFDNR>
      <BERUF>Pädagoge</BERUF>
   </ITEM>
   <ITEM num="194">
      <ID>22164</ID>
      <LFDNR>50487</LFDNR>
      <BERUF>Schriftsteller</BERUF>
   </ITEM>
   <ITEM num="195">
      <ID>22164</ID>
      <LFDNR>51348</LFDNR>
      <BERUF>Journalist</BERUF>
   </ITEM>
   <ITEM num="196">
      <ID>22235</ID>
      <LFDNR>1097</LFDNR>
      <BERUF>Schriftsteller</BERUF>
   </ITEM>
   <ITEM num="197">
      <ID>22322</ID>
      <LFDNR>30165</LFDNR>
      <BERUF>Schriftsteller</BERUF>
   </ITEM>
   <ITEM num="198">
      <ID>22322</ID>
      <LFDNR>30166</LFDNR>
      <BERUF>Theaterleiter</BERUF>
   </ITEM>
   <ITEM num="199">
      <ID>22329</ID>
      <LFDNR>1103</LFDNR>
      <BERUF>Schauspieler</BERUF>
   </ITEM>
   <ITEM num="200">
      <ID>22329</ID>
      <LFDNR>1104</LFDNR>
      <BERUF>Dramatiker</BERUF>
   </ITEM>
   <ITEM num="201">
      <ID>22363</ID>
      <LFDNR>26132</LFDNR>
      <BERUF>Jurist</BERUF>
   </ITEM>
   <ITEM num="202">
      <ID>22363</ID>
      <LFDNR>26133</LFDNR>
      <BERUF>Schriftsteller</BERUF>
   </ITEM>
   <ITEM num="203">
      <ID>22390</ID>
      <LFDNR>30079</LFDNR>
      <BERUF>Abgeordneter</BERUF>
   </ITEM>
   <ITEM num="204">
      <ID>22390</ID>
      <LFDNR>30080</LFDNR>
      <BERUF>Philologe</BERUF>
   </ITEM>
   <ITEM num="205">
      <ID>22390</ID>
      <LFDNR>30081</LFDNR>
      <BERUF>Literaturhistoriker</BERUF>
   </ITEM>
   <ITEM num="206">
      <ID>22390</ID>
      <LFDNR>30082</LFDNR>
      <BERUF>Journalist</BERUF>
   </ITEM>
   <ITEM num="207">
      <ID>22472</ID>
      <LFDNR>1012</LFDNR>
      <BERUF>Handlungsgehilfe</BERUF>
   </ITEM>
   <ITEM num="208">
      <ID>22472</ID>
      <LFDNR>1013</LFDNR>
      <BERUF>Schriftsteller</BERUF>
   </ITEM>
   <ITEM num="209">
      <ID>22544</ID>
      <LFDNR>27800</LFDNR>
      <BERUF>Philologe</BERUF>
   </ITEM>
   <ITEM num="210">
      <ID>22544</ID>
      <LFDNR>27801</LFDNR>
      <BERUF>Publizist</BERUF>
   </ITEM>
   <ITEM num="211">
      <ID>22544</ID>
      <LFDNR>27802</LFDNR>
      <BERUF>Schriftsteller</BERUF>
   </ITEM>
   <ITEM num="212">
      <ID>22592</ID>
      <LFDNR>1018</LFDNR>
      <BERUF>Improvisator</BERUF>
   </ITEM>
   <ITEM num="213">
      <ID>22592</ID>
      <LFDNR>1019</LFDNR>
      <BERUF>Literaturhistoriker</BERUF>
   </ITEM>
   <ITEM num="214">
      <ID>22592</ID>
      <LFDNR>1020</LFDNR>
      <BERUF>Schriftsteller</BERUF>
   </ITEM>
   <ITEM num="215">
      <ID>22607</ID>
      <LFDNR>1021</LFDNR>
      <BERUF>Schriftsteller</BERUF>
   </ITEM>
   <ITEM num="216">
      <ID>22607</ID>
      <LFDNR>1022</LFDNR>
      <BERUF>Kritiker</BERUF>
   </ITEM>
   <ITEM num="217">
      <ID>22607</ID>
      <LFDNR>1023</LFDNR>
      <BERUF>Kabarettist</BERUF>
   </ITEM>
   <ITEM num="218">
      <ID>22681</ID>
      <LFDNR>21570</LFDNR>
      <BERUF>Theologe</BERUF>
   </ITEM>
   <ITEM num="219">
      <ID>22681</ID>
      <LFDNR>21571</LFDNR>
      <BERUF>Politiker</BERUF>
   </ITEM>
   <ITEM num="220">
      <ID>22681</ID>
      <LFDNR>21572</LFDNR>
      <BERUF>Dichter</BERUF>
   </ITEM>
   <ITEM num="221">
      <ID>22781</ID>
      <LFDNR>653</LFDNR>
      <BERUF>Schriftstellerin</BERUF>
   </ITEM>
   <ITEM num="222">
      <ID>22800</ID>
      <LFDNR>1056</LFDNR>
      <BERUF>Komponist</BERUF>
   </ITEM>
   <ITEM num="223">
      <ID>22898</ID>
      <LFDNR>1507</LFDNR>
      <BERUF>Übersetzerin</BERUF>
   </ITEM>
   <ITEM num="224">
      <ID>22898</ID>
      <LFDNR>1508</LFDNR>
      <BERUF>Reiseschriftstellerin</BERUF>
   </ITEM>
   <ITEM num="225">
      <ID>22898</ID>
      <LFDNR>1509</LFDNR>
      <BERUF>Schriftstellerin</BERUF>
   </ITEM>
   <ITEM num="226">
      <ID>22898</ID>
      <LFDNR>1510</LFDNR>
      <BERUF>Kritikerin</BERUF>
   </ITEM>
   <ITEM num="227">
      <ID>35180</ID>
      <LFDNR>108</LFDNR>
      <BERUF>Architekt</BERUF>
   </ITEM>
   <ITEM num="228">
      <ID>35180</ID>
      <LFDNR>109</LFDNR>
      <BERUF>Stecher</BERUF>
   </ITEM>
   <ITEM num="229">
      <ID>35180</ID>
      <LFDNR>40519</LFDNR>
      <BERUF>Zeichner</BERUF>
   </ITEM>
   <ITEM num="230">
      <ID>35180</ID>
      <LFDNR>40520</LFDNR>
      <BERUF>Denkmalpfleger</BERUF>
   </ITEM>
   <ITEM num="231">
      <ID>35181</ID>
      <LFDNR>110</LFDNR>
      <BERUF>Theologe</BERUF>
   </ITEM>
   <ITEM num="232">
      <ID>35183</ID>
      <LFDNR>111</LFDNR>
      <BERUF>Pfarrer</BERUF>
   </ITEM>
   <ITEM num="233">
      <ID>35184</ID>
      <LFDNR>20537</LFDNR>
      <BERUF>Mediziner</BERUF>
   </ITEM>
   <ITEM num="234">
      <ID>35185</ID>
      <LFDNR>112</LFDNR>
      <BERUF>Politiker</BERUF>
   </ITEM>
   <ITEM num="235">
      <ID>35186</ID>
      <LFDNR>113</LFDNR>
      <BERUF>Diplomat</BERUF>
   </ITEM>
   <ITEM num="236">
      <ID>35186</ID>
      <LFDNR>114</LFDNR>
      <BERUF>Kunstsammler</BERUF>
   </ITEM>
   <ITEM num="237">
      <ID>35187</ID>
      <LFDNR>115</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="238">
      <ID>35187</ID>
      <LFDNR>116</LFDNR>
      <BERUF>Zeichner</BERUF>
   </ITEM>
   <ITEM num="239">
      <ID>35187</ID>
      <LFDNR>117</LFDNR>
      <BERUF>Architekt</BERUF>
   </ITEM>
   <ITEM num="240">
      <ID>35188</ID>
      <LFDNR>118</LFDNR>
      <BERUF>Kaufmann</BERUF>
   </ITEM>
   <ITEM num="241">
      <ID>35189</ID>
      <LFDNR>20538</LFDNR>
      <BERUF>Stempelschneider</BERUF>
   </ITEM>
   <ITEM num="242">
      <ID>35189</ID>
      <LFDNR>20539</LFDNR>
      <BERUF>Medailleur</BERUF>
   </ITEM>
   <ITEM num="243">
      <ID>35190</ID>
      <LFDNR>119</LFDNR>
      <BERUF>Dichter</BERUF>
   </ITEM>
   <ITEM num="244">
      <ID>35191</ID>
      <LFDNR>120</LFDNR>
      <BERUF>Bergbaubeamter</BERUF>
   </ITEM>
   <ITEM num="245">
      <ID>35192</ID>
      <LFDNR>23181</LFDNR>
      <BERUF>Schauspieler</BERUF>
   </ITEM>
   <ITEM num="246">
      <ID>35192</ID>
      <LFDNR>23182</LFDNR>
      <BERUF>Regisseur</BERUF>
   </ITEM>
   <ITEM num="247">
      <ID>35194</ID>
      <LFDNR>121</LFDNR>
      <BERUF>Chemiker</BERUF>
   </ITEM>
   <ITEM num="248">
      <ID>35195</ID>
      <LFDNR>122</LFDNR>
      <BERUF>Jurist</BERUF>
   </ITEM>
   <ITEM num="249">
      <ID>35195</ID>
      <LFDNR>123</LFDNR>
      <BERUF>Politiker</BERUF>
   </ITEM>
   <ITEM num="250">
      <ID>35195</ID>
      <LFDNR>124</LFDNR>
      <BERUF>Offizier</BERUF>
   </ITEM>
   <ITEM num="251">
      <ID>35196</ID>
      <LFDNR>125</LFDNR>
      <BERUF>Botaniker</BERUF>
   </ITEM>
   <ITEM num="252">
      <ID>35197</ID>
      <LFDNR>126</LFDNR>
      <BERUF>Maler</BERUF>
   </ITEM>
   <ITEM num="253">
      <ID>35197</ID>
      <LFDNR>127</LFDNR>
      <BERUF>Zeichner</BERUF>
   </ITEM>
   <ITEM num="254">
      <ID>35198</ID>
      <LFDNR>128</LFDNR>
      <BERUF>Münzmeister</BERUF>
   </ITEM>
   <ITEM num="255">
      <ID>35199</ID>
      <LFDNR>129</LFDNR>
      <BERUF>Amtmann</BERUF>
   </ITEM>
   <ITEM num="256">
      <ID>35200</ID>
      <LFDNR>130</LFDNR>
      <BERUF>Mediziner</BERUF>
   </ITEM>
   <ITEM num="257">
      <ID>35201</ID>
      <LFDNR>131</LFDNR>
      <BERUF>Steuerbeamter</BERUF>
   </ITEM>
   <ITEM num="258">
      <ID>35202</ID>
      <LFDNR>132</LFDNR>
      <BERUF>Schauspielerin</BERUF>
   </ITEM>
   <ITEM num="259">
      <ID>35205</ID>
      <LFDNR>133</LFDNR>
      <BERUF>Kunsthändler</BERUF>
   </ITEM>
   <ITEM num="260">
      <ID>35205</ID>
      <LFDNR>134</LFDNR>
      <BERUF>Verleger</BERUF>
   </ITEM>
   <ITEM num="261">
      <ID>35205</ID>
      <LFDNR>135</LFDNR>
      <BERUF>Industrieller</BERUF>
   </ITEM>
   <ITEM num="262">
      <ID>35206</ID>
      <LFDNR>136</LFDNR>
      <BERUF>Schauspielerin</BERUF>
   </ITEM>
   <ITEM num="263">
      <ID>35206</ID>
      <LFDNR>137</LFDNR>
      <BERUF>Sängerin</BERUF>
   </ITEM>
   <ITEM num="264">
      <ID>35207</ID>
      <LFDNR>27615</LFDNR>
      <BERUF>Mediziner</BERUF>
   </ITEM>
   <ITEM num="265">
      <ID>35207</ID>
      <LFDNR>27616</LFDNR>
      <BERUF>Pharmazeut</BERUF>
   </ITEM>
   <ITEM num="266">
      <ID>35207</ID>
      <LFDNR>27617</LFDNR>
      <BERUF>Apotheker</BERUF>
   </ITEM>
   <ITEM num="267">
      <ID>35208</ID>
      <LFDNR>138</LFDNR>
      <BERUF>Politiker</BERUF>
   </ITEM>
   <ITEM num="268">
      <ID>35209</ID>
      <LFDNR>139</LFDNR>
      <BERUF>Musiker</BERUF>
   </ITEM>
   <ITEM num="269">
      <ID>35209</ID>
      <LFDNR>140</LFDNR>
      <BERUF>Schriftsteller</BERUF>
   </ITEM>
   <ITEM num="270">
      <ID>35210</ID>
      <LFDNR>141</LFDNR>
      <BERUF>Politiker</BERUF>
   </ITEM>
   <ITEM num="271">
      <ID>35211</ID>
      <LFDNR>20540</LFDNR>
      <BERUF>Politiker</BERUF>
   </ITEM>
   <ITEM num="272">
      <ID>35211</ID>
      <LFDNR>20541</LFDNR>
      <BERUF>Journalist</BERUF>
   </ITEM>