<?xml version = "1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE PROJEKT_BUG [
<!ELEMENT PROJEKT_BUG (ITEM)*>
<!ELEMENT ITEM (ID, REGISTEREINTRAG?)>
<!ATTLIST ITEM num CDATA #REQUIRED>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT REGISTEREINTRAG (#PCDATA)>
]>
<PROJEKT_BUG>
   <ITEM num="1">
      <ID>1502</ID>
      <REGISTEREINTRAG>David, Pierre Jean, gen. David d'Angers</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="2">
      <ID>2054</ID>
      <REGISTEREINTRAG>Förster, /Ernst/ Joachim</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="3">
      <ID>2475</ID>
      <REGISTEREINTRAG>Goethe, Johann Wolfgang (seit 1782 v.)</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="4">
      <ID>5327</ID>
      <REGISTEREINTRAG>Ramberg, Johann Heinrich</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="5">
      <ID>6002</ID>
      <REGISTEREINTRAG>Schmoll, Georg Friedrich</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="6">
      <ID>6782</ID>
      <REGISTEREINTRAG>Wilken, Caroline, geb. Tischbein</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="7">
      <ID>11085</ID>
      <REGISTEREINTRAG>Sachsen-Weimar-Eisenach, Ernst August I. Herzog von</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="8">
      <ID>11089</ID>
      <REGISTEREINTRAG>Hessen-Darmstadt, Henriette /Caroline/ Christine Philippine Louise Landgräfin von, geb. Prinzessin von Pfalz-Zweibrücken </REGISTEREINTRAG>
   </ITEM>
   <ITEM num="9">
      <ID>11093</ID>
      <REGISTEREINTRAG>Rußland, Natalia Alexejewna Großfürstin von, geb. Prinzessin /Wilhelmine/ Luise von Hessen-Darmstadt </REGISTEREINTRAG>
   </ITEM>
   <ITEM num="10">
      <ID>19271</ID>
      <REGISTEREINTRAG>Asher, David</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="11">
      <ID>19426</ID>
      <REGISTEREINTRAG>Bielschowsky, Albert</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="12">
      <ID>19443</ID>
      <REGISTEREINTRAG>Bissing, Henriette v., geb. Krohn </REGISTEREINTRAG>
   </ITEM>
   <ITEM num="13">
      <ID>19477</ID>
      <REGISTEREINTRAG>Bode, Friedrich /Wilhelm/</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="14">
      <ID>19764</ID>
      <REGISTEREINTRAG>Diezmann, Johann August</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="15">
      <ID>20510</ID>
      <REGISTEREINTRAG>Holtei, /Karl/ Eduard v. </REGISTEREINTRAG>
   </ITEM>
   <ITEM num="16">
      <ID>20869</ID>
      <REGISTEREINTRAG>Kurz, Hermann</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="17">
      <ID>21114</ID>
      <REGISTEREINTRAG>Maltzahn, Wendelin v.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="18">
      <ID>21911</ID>
      <REGISTEREINTRAG>Schmidt, Klamer (Clamor) Eberhard Karl</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="19">
      <ID>22069</ID>
      <REGISTEREINTRAG>Schöll, Gustav /Adolf/</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="20">
      <ID>22147</ID>
      <REGISTEREINTRAG>Sondershausen, Philipp /Karl/ Christian</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="21">
      <ID>22164</ID>
      <REGISTEREINTRAG>Springer, Robert</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="22">
      <ID>22390</ID>
      <REGISTEREINTRAG>Vollmer, Wilhelm</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="23">
      <ID>22592</ID>
      <REGISTEREINTRAG>Wolff, Oscar Ludwig /Bernhard/</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="24">
      <ID>22607</ID>
      <REGISTEREINTRAG>Wolzogen, Ernst v.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="25">
      <ID>22781</ID>
      <REGISTEREINTRAG>Förster-Nietzsche, Elisabeth, geb. Nietzsche</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="26">
      <ID>35181</ID>
      <REGISTEREINTRAG>Abegg, Johann Friedrich</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="27">
      <ID>35189</ID>
      <REGISTEREINTRAG>Abramson, Abraham</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="28">
      <ID>35204</ID>
      <REGISTEREINTRAG>Ackermann, M. A., geb. Schuman</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="29">
      <ID>35245</ID>
      <REGISTEREINTRAG>Albrecht, Christian Friedrich Heinrich</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="30">
      <ID>35247</ID>
      <REGISTEREINTRAG>Albrecht, Johann Georg</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="31">
      <ID>35248</ID>
      <REGISTEREINTRAG>Albrecht, Johann Carl</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="32">
      <ID>35259</ID>
      <REGISTEREINTRAG>Almendingen, Ludwig Harscher von</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="33">
      <ID>35260</ID>
      <REGISTEREINTRAG>Alopaeus, David Maximowitsch Graf v. </REGISTEREINTRAG>
   </ITEM>
   <ITEM num="34">
      <ID>35266</ID>
      <REGISTEREINTRAG>Althof, Ludwig Christoph</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="35">
      <ID>35282</ID>
      <REGISTEREINTRAG>Chaulieu, Guillaume Amfrye de</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="36">
      <ID>35295</ID>
      <REGISTEREINTRAG>André, Johann</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="37">
      <ID>35296</ID>
      <REGISTEREINTRAG>Andreae, Jean</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="38">
      <ID>35312</ID>
      <REGISTEREINTRAG>Anhalt-Dessau, Friedrich Erbprinz von</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="39">
      <ID>35333</ID>
      <REGISTEREINTRAG>Achenholtz, Johann Wilhelm v.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="40">
      <ID>35335</ID>
      <REGISTEREINTRAG>Arendt (Ahrndt, Arndt), Martin Friedrich</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="41">
      <ID>35346</ID>
      <REGISTEREINTRAG>Arndt, Ernst Moritz</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="42">
      <ID>35364</ID>
      <REGISTEREINTRAG>Arvelius, Martin Heinrich</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="43">
      <ID>35387</ID>
      <REGISTEREINTRAG>Aulhorn, Johann Adam</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="44">
      <ID>35391</ID>
      <REGISTEREINTRAG>Austin, Sarah, geb. Taylor</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="45">
      <ID>35406</ID>
      <REGISTEREINTRAG>Bach, Johann Sebastian</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="46">
      <ID>35408</ID>
      <REGISTEREINTRAG>Bach, Carl /Philipp Emanuel/</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="47">
      <ID>35415</ID>
      <REGISTEREINTRAG>Baden, Karl Friedrich (Markgraf, 1803 Kurfürst, 1806 Großherzog) von</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="48">
      <ID>35427</ID>
      <REGISTEREINTRAG>Baggesen, Jens Immanuel</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="49">
      <ID>35431</ID>
      <REGISTEREINTRAG>Bahrdt, Carl Friedrich</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="50">
      <ID>35444</ID>
      <REGISTEREINTRAG>Bancroft, George</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="51">
      <ID>35498</ID>
      <REGISTEREINTRAG>Basedow, Johann Bernhard</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="52">
      <ID>35545</ID>
      <REGISTEREINTRAG>Beaumarchais, Pierre Augustin Caron de</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="53">
      <ID>35553</ID>
      <REGISTEREINTRAG>Bechtolsheim, Johann Ludwig v. Mauchenheim, gen. </REGISTEREINTRAG>
   </ITEM>
   <ITEM num="54">
      <ID>35564</ID>
      <REGISTEREINTRAG>Becker, Carl</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="55">
      <ID>35571</ID>
      <REGISTEREINTRAG>Becker, /Wilhelm/ /Gottlieb/ Ernst</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="56">
      <ID>35576</ID>
      <REGISTEREINTRAG>Beethoven, Ludwig van</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="57">
      <ID>35610</ID>
      <REGISTEREINTRAG>Benecke, Georg Friedrich</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="58">
      <ID>35632</ID>
      <REGISTEREINTRAG>Berczy, Albert-Guillaume (eigentl. Johann Albrecht Ulrich Moll)</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="59">
      <ID>35635</ID>
      <REGISTEREINTRAG>Berendis, Hieronymus Dietrich</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="60">
      <ID>35642</ID>
      <REGISTEREINTRAG>Berg, Friederike Caroline v., geb. v. Häseler</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="61">
      <ID>35671</ID>
      <REGISTEREINTRAG>Berlichingen, Gottfried (Götz) von</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="62">
      <ID>35712</ID>
      <REGISTEREINTRAG>Bertram, Johann Baptist</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="63">
      <ID>35716</ID>
      <REGISTEREINTRAG>Bertuch, Carl</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="64">
      <ID>35717</ID>
      <REGISTEREINTRAG>Bervisson (Bervison), Wilhelmine</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="65">
      <ID>35726</ID>
      <REGISTEREINTRAG>Bethmann, Simon Moritz (v.)</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="66">
      <ID>35737</ID>
      <REGISTEREINTRAG>Beulwitz, Friedrich Wilhelm Ludwig v.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="67">
      <ID>35741</ID>
      <REGISTEREINTRAG>Beuther (Beuter), Anna Elisabeth, geb. Bachmann</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="68">
      <ID>35752</ID>
      <REGISTEREINTRAG>Beyme, Carl Friedrich v.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="69">
      <ID>35763</ID>
      <REGISTEREINTRAG>Bielke, Friedrich Wilhelm v. </REGISTEREINTRAG>
   </ITEM>
   <ITEM num="70">
      <ID>35768</ID>
      <REGISTEREINTRAG>Biester, Johann Erich</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="71">
      <ID>35777</ID>
      <REGISTEREINTRAG>Birkenstock, Johann Melchior v.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="72">
      <ID>35780</ID>
      <REGISTEREINTRAG>Birmann, Peter</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="73">
      <ID>35798</ID>
      <REGISTEREINTRAG>Blessig, Johann Lorenz</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="74">
      <ID>35801</ID>
      <REGISTEREINTRAG>Blöcker, Justus Ludewig</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="75">
      <ID>35809</ID>
      <REGISTEREINTRAG>Blücher, Gebhard Leberecht v., (seit 1814) Fürst von Wahlstatt</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="76">
      <ID>35812</ID>
      <REGISTEREINTRAG>Blümner, Heinrich</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="77">
      <ID>35817</ID>
      <REGISTEREINTRAG>Blum, Karl Ludwig</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="78">
      <ID>35820</ID>
      <REGISTEREINTRAG>Blumauer, Karl (eigentl. Johann Gottfried Bernhard)</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="79">
      <ID>35825</ID>
      <REGISTEREINTRAG>Blumenbach, Johann Friedrich</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="80">
      <ID>35828</ID>
      <REGISTEREINTRAG>Blumenstein, genannt Kayer, Wilhelm Johann v.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="81">
      <ID>35841</ID>
      <REGISTEREINTRAG>Bode, /Johann/ Joachim Christoph</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="82">
      <ID>35845</ID>
      <REGISTEREINTRAG>Bodmer, Johann Jacob</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="83">
      <ID>35849</ID>
      <REGISTEREINTRAG>Böckmann, Johann Lorenz</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="84">
      <ID>35853</ID>
      <REGISTEREINTRAG>Boehlendorff, Casimir Ulrich </REGISTEREINTRAG>
   </ITEM>
   <ITEM num="85">
      <ID>35862</ID>
      <REGISTEREINTRAG>Böhme, Johann Gottlob</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="86">
      <ID>35865</ID>
      <REGISTEREINTRAG>Böhmer, Auguste</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="87">
      <ID>35867</ID>
      <REGISTEREINTRAG>Böhmer, Johann Georg /Wilhelm/</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="88">
      <ID>35876</ID>
      <REGISTEREINTRAG>Börne, Carl /Ludwig/</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="89">
      <ID>35880</ID>
      <REGISTEREINTRAG>Börner, Carl Gustav</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="90">
      <ID>35882</ID>
      <REGISTEREINTRAG>Boethius, Anicius Manlius Severinus</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="91">
      <ID>35888</ID>
      <REGISTEREINTRAG>Böttiger, Carl August</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="92">
      <ID>35896</ID>
      <REGISTEREINTRAG>Bohl, Johanne Susanne, geb. Eberhard(t)</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="93">
      <ID>35899</ID>
      <REGISTEREINTRAG>Bohn, Friedrich</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="94">
      <ID>35902</ID>
      <REGISTEREINTRAG>Boie, Friedrich</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="95">
      <ID>35903</ID>
      <REGISTEREINTRAG>Boie, Heinrich Christian</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="96">
      <ID>35904</ID>
      <REGISTEREINTRAG>Boisserée, Maria, geb. de Tongre</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="97">
      <ID>35914</ID>
      <REGISTEREINTRAG>Bollmann, Ludwig (Lewis)</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="98">
      <ID>35916</ID>
      <REGISTEREINTRAG>Bolt, Johann /Friedrich/</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="99">
      <ID>35917</ID>
      <REGISTEREINTRAG>Bolza, Joseph Graf v.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="100">
      <ID>35932</ID>
      <REGISTEREINTRAG>Bopp, Franz</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="101">
      <ID>35960</ID>
      <REGISTEREINTRAG>Both, /Carl/ Friedrich v.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="102">
      <ID>35961</ID>
      <REGISTEREINTRAG>Both, /Rudolphine/ Hedwig Friederike v., geb. Brüning</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="103">
      <ID>35970</ID>
      <REGISTEREINTRAG>Bouilly, Jean Nicolas</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="104">
      <ID>35991</ID>
      <REGISTEREINTRAG>Branconi, Maria Antonia Marquise v., geb. v. Elsener</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="105">
      <ID>36000</ID>
      <REGISTEREINTRAG>Brandes, Johann Christian </REGISTEREINTRAG>
   </ITEM>
   <ITEM num="106">
      <ID>36004</ID>
      <REGISTEREINTRAG>Brant, Sebastian</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="107">
      <ID>36014</ID>
      <REGISTEREINTRAG>Braun, Peter v.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="108">
      <ID>36033</ID>
      <REGISTEREINTRAG>Breidenbach zu Breidenstein, /Karl/ Philipp Christian Johann Heinrich /Wilhelm/ v.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="109">
      <ID>36036</ID>
      <REGISTEREINTRAG>Breitenbach, Philipp Franz</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="110">
      <ID>36044</ID>
      <REGISTEREINTRAG>Breitinger, Johann Jacob</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="111">
      <ID>36046</ID>
      <REGISTEREINTRAG>Breitkopf, Christoph Gottlob</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="112">
      <ID>36047</ID>
      <REGISTEREINTRAG>Breitkopf, Johann Gottlob Immanuel</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="113">
      <ID>36053</ID>
      <REGISTEREINTRAG>Brenner, Wilhelm</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="114">
      <ID>36067</ID>
      <REGISTEREINTRAG>Brinckmann, Carl Gustav v.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="115">
      <ID>36069</ID>
      <REGISTEREINTRAG>Brion, Johann Jacob</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="116">
      <ID>36072</ID>
      <REGISTEREINTRAG>Brocchi, Giovanni Battista</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="117">
      <ID>36076</ID>
      <REGISTEREINTRAG>Brockhaus, Friedrich Arnold</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="118">
      <ID>36105</ID>
      <REGISTEREINTRAG>Brückner, Ernst Theodor Johann</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="119">
      <ID>36107</ID>
      <REGISTEREINTRAG>Brühl, Hans Moritz Graf v.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="120">
      <ID>36108</ID>
      <REGISTEREINTRAG>Brühl, Heinrich Graf v.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="121">
      <ID>36109</ID>
      <REGISTEREINTRAG>Brühl, Jenny Gräfin v., geb. v. Pourtalès </REGISTEREINTRAG>
   </ITEM>
   <ITEM num="122">
      <ID>36119</ID>
      <REGISTEREINTRAG>Brunnquell, Johann Daniel Wilhelm</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="123">
      <ID>36125</ID>
      <REGISTEREINTRAG>Brutus, Marcus Iunius</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="124">
      <ID>36158</ID>
      <REGISTEREINTRAG>Bürde, Samuel Gottlieb</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="125">
      <ID>36161</ID>
      <REGISTEREINTRAG>Bürger, Gottfried August</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="126">
      <ID>36164</ID>
      <REGISTEREINTRAG>Bürkli, Johann Heinrich</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="127">
      <ID>36169</ID>
      <REGISTEREINTRAG>Büttner, Christian Wilhelm</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="128">
      <ID>36174</ID>
      <REGISTEREINTRAG>Buff, Henrich Adam</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="129">
      <ID>36176</ID>
      <REGISTEREINTRAG>Buffon, Georges Louis Leclerc Comte de</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="130">
      <ID>36192</ID>
      <REGISTEREINTRAG>Buri, Ernst Carl /Ludwig/ Ysenburg v.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="131">
      <ID>36204</ID>
      <REGISTEREINTRAG>Bury, Isaak Pierre</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="132">
      <ID>36205</ID>
      <REGISTEREINTRAG>Bury, Catharina, geb. Tessonier</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="133">
      <ID>36218</ID>
      <REGISTEREINTRAG>Byron, George Gordon Baron, gen. Lord Byron</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="134">
      <ID>36222</ID>
      <REGISTEREINTRAG>Caesar, Gaius Julius</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="135">
      <ID>36223</ID>
      <REGISTEREINTRAG>Balsamo, Guiseppe, gen. Alessandro Graf Cagliostro</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="136">
      <ID>36236</ID>
      <REGISTEREINTRAG>Calvin, Johann (Jean Cauvin)</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="137">
      <ID>36243</ID>
      <REGISTEREINTRAG>Campe, Joachim Heinrich</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="138">
      <ID>36284</ID>
      <REGISTEREINTRAG>Carus, Friedrich August</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="139">
      <ID>36285</ID>
      <REGISTEREINTRAG>Carus, Carl Gustav</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="140">
      <ID>36297</ID>
      <REGISTEREINTRAG>Casti, Giovanni Battista (/Giambattista/), Abbate</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="141">
      <ID>36300</ID>
      <REGISTEREINTRAG>Castrop, Jean Antoine Joseph de </REGISTEREINTRAG>
   </ITEM>
   <ITEM num="142">
      <ID>36318</ID>
      <REGISTEREINTRAG>Cenci, Beatrice</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="143">
      <ID>36322</ID>
      <REGISTEREINTRAG>Cervantes Saavedra, Miguel de</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="144">
      <ID>36330</ID>
      <REGISTEREINTRAG>Chanorier, Jean</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="145">
      <ID>36358</ID>
      <REGISTEREINTRAG>Christ, Johann Friedrich</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="146">
      <ID>36367</ID>
      <REGISTEREINTRAG>Cicero, Marcus Tullius</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="147">
      <ID>36378</ID>
      <REGISTEREINTRAG>Claproth, Justus</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="148">
      <ID>36383</ID>
      <REGISTEREINTRAG>Claudius, Matthias</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="149">
      <ID>36386</ID>
      <REGISTEREINTRAG>Claus, Johann Andreas Daniel</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="150">
      <ID>36399</ID>
      <REGISTEREINTRAG>Clodius, Christian August</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="151">
      <ID>36401</ID>
      <REGISTEREINTRAG>Clodius, Christian August Heinrich</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="152">
      <ID>36411</ID>
      <REGISTEREINTRAG>Cogswell, Joseph Green</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="153">
      <ID>36421</ID>
      <REGISTEREINTRAG>Colman, George</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="154">
      <ID>36436</ID>
      <REGISTEREINTRAG>Congreve, William</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="155">
      <ID>36466</ID>
      <REGISTEREINTRAG>Cotta, Johann Friedrich</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="156">
      <ID>36473</ID>
      <REGISTEREINTRAG>Coudray, /Clemens Wenzeslaus/ Franz Joseph</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="157">
      <ID>36485</ID>
      <REGISTEREINTRAG>Cramer, Carl Friedrich</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="158">
      <ID>36493</ID>
      <REGISTEREINTRAG>Cranach, Lucas, d. Ä.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="159">
      <ID>36508</ID>
      <REGISTEREINTRAG>Cronegk, Johann Friedrich v.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="160">
      <ID>36509</ID>
      <REGISTEREINTRAG>Crugot, Martin</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="161">
      <ID>36512</ID>
      <REGISTEREINTRAG>Crusius, Siegfried Lebrecht</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="162">
      <ID>36514</ID>
      <REGISTEREINTRAG>Cumberland, Richard</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="163">
      <ID>36523</ID>
      <REGISTEREINTRAG>Czartoryski, /Adam/ /Kazimierz/ Joachim Ambrozy Marek Fürst </REGISTEREINTRAG>
   </ITEM>
   <ITEM num="164">
      <ID>36527</ID>
      <REGISTEREINTRAG>Dabelow, Christoph Christian v.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="165">
      <ID>36555</ID>
      <REGISTEREINTRAG>Dannecker, Johann Heinrich</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="166">
      <ID>36564</ID>
      <REGISTEREINTRAG>Daries, Joachim Georg</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="167">
      <ID>36571</ID>
      <REGISTEREINTRAG>Daßdorf, Carl Wilhelm</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="168">
      <ID>36599</ID>
      <REGISTEREINTRAG>Deinet, Johann Conrad</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="169">
      <ID>36610</ID>
      <REGISTEREINTRAG>Delph, Helene Dorothea</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="170">
      <ID>36621</ID>
      <REGISTEREINTRAG>Dentzel (Dantzel, Däntzel), Georg Friedrich Eduard</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="171">
      <ID>36645</ID>
      <REGISTEREINTRAG>Diede zum Fürstenstein, Wilhelm Christoph v.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="172">
      <ID>36656</ID>
      <REGISTEREINTRAG>Dietrich, Friedrich Gottlieb (eigentl. Johann Christian Gottfried)</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="173">
      <ID>36680</ID>
      <REGISTEREINTRAG>Dittmar, Siegismund Gottfried</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="174">
      <ID>36694</ID>
      <REGISTEREINTRAG>Döbereiner, Johann Wolfgang</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="175">
      <ID>36702</ID>
      <REGISTEREINTRAG>Doell, Friedrich Wilhelm Eugen</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="176">
      <ID>36755</ID>
      <REGISTEREINTRAG>Düntzer, Johann /Heinrich/ Joseph</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="177">
      <ID>36757</ID>
      <REGISTEREINTRAG>Dürckheim, Franz Christian Eckbrecht v.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="178">
      <ID>36758</ID>
      <REGISTEREINTRAG>Dürer, Albrecht</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="179">
      <ID>36772</ID>
      <REGISTEREINTRAG>Duhen, Jacques Joseph</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="180">
      <ID>36781</ID>
      <REGISTEREINTRAG>Du Manoir (Dumanoir), Jean-Louis Le Chanoine Comte</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="181">
      <ID>36782</ID>
      <REGISTEREINTRAG>Dumeiz, Damian Friedrich</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="182">
      <ID>36803</ID>
      <REGISTEREINTRAG>Duval, Alexandre</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="183">
      <ID>36805</ID>
      <REGISTEREINTRAG>Duvau, Louis /Auguste/</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="184">
      <ID>36823</ID>
      <REGISTEREINTRAG>Eckardt, /Johann/ Christian /Ludwig/</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="185">
      <ID>36828</ID>
      <REGISTEREINTRAG>Eckermann, Johann Peter</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="186">
      <ID>36837</ID>
      <REGISTEREINTRAG>Edling, Albert Cajetan Graf v.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="187">
      <ID>36838</ID>
      <REGISTEREINTRAG>Edling, Roxandra Skarlatowna Gräfin v., geb. Sturdza</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="188">
      <ID>36847</ID>
      <REGISTEREINTRAG>Egloffstein, Caroline v., geb. v. Aufseß</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="189">
      <ID>36865</ID>
      <REGISTEREINTRAG>Eichhorn, /Ambrosius/ Hubert Eduard</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="190">
      <ID>36866</ID>
      <REGISTEREINTRAG>Eichhorn, Johann Gottfried</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="191">
      <ID>36867</ID>
      <REGISTEREINTRAG>Eichhorn, Karl Friedrich</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="192">
      <ID>36868</ID>
      <REGISTEREINTRAG>Eichstädt, Heinrich Carl Abraham</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="193">
      <ID>36872</ID>
      <REGISTEREINTRAG>Eisenschmidt, Johann Adam /Heinrich/</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="194">
      <ID>36925</ID>
      <REGISTEREINTRAG>Erdmannsdorff, Friedrich Wilhelm v.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="195">
      <ID>36933</ID>
      <REGISTEREINTRAG>Erichson, Johann</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="196">
      <ID>36942</ID>
      <REGISTEREINTRAG>Ersch, Johann Samuel</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="197">
      <ID>36947</ID>
      <REGISTEREINTRAG>Eschenburg, Johann Joachim</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="198">
      <ID>36948</ID>
      <REGISTEREINTRAG>Escher vom Glas, Johannes</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="199">
      <ID>36956</ID>
      <REGISTEREINTRAG>Esperstedt, Johann Friedrich</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="200">
      <ID>36961</ID>
      <REGISTEREINTRAG>Ester, Quirin Joseph d’</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="201">
      <ID>36970</ID>
      <REGISTEREINTRAG>Ettling, Jean Jacques</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="202">
      <ID>36976</ID>
      <REGISTEREINTRAG>Everdingen, Allaert van</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="203">
      <ID>36977</ID>
      <REGISTEREINTRAG>Everett, Edward</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="204">
      <ID>36978</ID>
      <REGISTEREINTRAG>Ewald, Johann Ludwig</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="205">
      <ID>36984</ID>
      <REGISTEREINTRAG>Eyck (Eyk), Jan van</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="206">
      <ID>37000</ID>
      <REGISTEREINTRAG>Facius, Friedrich Wilhelm</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="207">
      <ID>37007</ID>
      <REGISTEREINTRAG>Falcke, Ernst Friedrich Hektor</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="208">
      <ID>37012</ID>
      <REGISTEREINTRAG>Falk, Rosalie</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="209">
      <ID>37021</ID>
      <REGISTEREINTRAG>Faust, Bernhard Christoph</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="210">
      <ID>37058</ID>
      <REGISTEREINTRAG>Fichard, Johann Karl v.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="211">
      <ID>37060</ID>
      <REGISTEREINTRAG>Fichte, Johann Gottlieb</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="212">
      <ID>37083</ID>
      <REGISTEREINTRAG>Firdausi (Ferdusi), Abu I-Kasim Mansur</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="213">
      <ID>37119</ID>
      <REGISTEREINTRAG>Flies, Eleonore, geb. Eskeles</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="214">
      <ID>37143</ID>
      <REGISTEREINTRAG>Forstenburg, /Carl/ Anton Ferdinand Graf v.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="215">
      <ID>37150</ID>
      <REGISTEREINTRAG>Foucquet, Marie Louise Eugénie Marquise de, geb. Blondel dite d'Aubers</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="216">
      <ID>37165</ID>
      <REGISTEREINTRAG>Franckenberg und Ludwigsdorf, /Sylvius/ Friedrich Ludwig v. </REGISTEREINTRAG>
   </ITEM>
   <ITEM num="217">
      <ID>37170</ID>
      <REGISTEREINTRAG>Frank, Johann /Peter/</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="218">
      <ID>37171</ID>
      <REGISTEREINTRAG>Frank, Joseph</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="219">
      <ID>37181</ID>
      <REGISTEREINTRAG>Franklin, Benjamin</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="220">
      <ID>37182</ID>
      <REGISTEREINTRAG>Frankreich, Franz I. König von</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="221">
      <ID>37185</ID>
      <REGISTEREINTRAG>Frankreich, Ludwig XIV. König von</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="222">
      <ID>37187</ID>
      <REGISTEREINTRAG>Frankreich, Ludwig XVI. König von</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="223">
      <ID>37191</ID>
      <REGISTEREINTRAG>Frankreich, Marie Antoinette Königin von, geb. Erzherzogin von Österreich</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="224">
      <ID>37201</ID>
      <REGISTEREINTRAG>Frege, Christian Gottlob</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="225">
      <ID>37202</ID>
      <REGISTEREINTRAG>Freiesleben, Johann Carl</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="226">
      <ID>37227</ID>
      <REGISTEREINTRAG>Fritsch, Friedrich August v.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="227">
      <ID>37228</ID>
      <REGISTEREINTRAG>Fritsch, Jacob Friedrich v.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="228">
      <ID>37232</ID>
      <REGISTEREINTRAG>Fritsch, Carl Wilhelm v.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="229">
      <ID>37233</ID>
      <REGISTEREINTRAG>Fritsch, Constanze Gräfin v.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="230">
      <ID>37239</ID>
      <REGISTEREINTRAG>Frölich, Heinrich</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="231">
      <ID>37242</ID>
      <REGISTEREINTRAG>Froriep, Ludwig Friedrich v.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="232">
      <ID>37249</ID>
      <REGISTEREINTRAG>Fuchs, Johann Friedrich</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="233">
      <ID>37250</ID>
      <REGISTEREINTRAG>Fuchs, Maximilian Heinrich</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="234">
      <ID>37265</ID>
      <REGISTEREINTRAG>Funck, Karl Wilhelm Ferdinand v.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="235">
      <ID>37293</ID>
      <REGISTEREINTRAG>Gall, Franz Joseph</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="236">
      <ID>37314</ID>
      <REGISTEREINTRAG>Garve, Christian</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="237">
      <ID>37318</ID>
      <REGISTEREINTRAG>Gaßner (Gaßener), Johann Joseph</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="238">
      <ID>37320</ID>
      <REGISTEREINTRAG>Gatto, /Franz/ Anton</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="239">
      <ID>37325</ID>
      <REGISTEREINTRAG>Gauß, Carl Friedrich</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="240">
      <ID>37328</ID>
      <REGISTEREINTRAG>Gautieri, Giuseppe</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="241">
      <ID>37349</ID>
      <REGISTEREINTRAG>Geisweiler, Constantin</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="242">
      <ID>37353</ID>
      <REGISTEREINTRAG>Gellert, Christian Fürchtegott</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="243">
      <ID>37356</ID>
      <REGISTEREINTRAG>Gemmingen, Eberhard Friedrich v.</REGISTEREINTRAG>
   </ITEM>
   <ITEM num="244">